### ISSUE TITLE
autogen.sh Error

### ISSUE THREAD

**Issue by zhangda89** [facebook/watchman#101]
davidzhang@davidzhang:~/nodejs$ brew install --HEAD watchman
==> Cloning https://github.com/facebook/watchman.git
Updating /Library/Caches/Homebrew/watchman--git
==> Checking out branch master
==> ./autogen.sh
      See the Autoconf documentation.
configure.ac:27: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:28: error: possibly undefined macro: AM_PROG_AS
configure.ac:34: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:75: error: possibly undefined macro: AM_PATH_PYTHON

READ THIS: https://git.io/brew-troubleshooting

**Comment by zhangda89** [comment]
what's wrong?

**Comment by wez** [comment]
Did you `brew install automake`?
What does `brew info automake` show?

**Comment by wez** [comment]
Run through the troubleshooting the link that you included in your original post above, as this sounds like a local-to-you build problem

**Comment by zhangda89** [comment]
automake: stable 1.15 (bottled)
https://www.gnu.org/software/automake/
/usr/local/Cellar/automake/1.15 (130 files, 3.2M) *
  Poured from bottle
From: https://github.com/Homebrew/homebrew/blob/master/Library/Formula/automake.rb
==> Dependencies
Build: xz ✔
Required: autoconf ✔

**Comment by zhangda89** [comment]
oh,i am sorry ,it's my wrong,i am doctor my brew and it is ok

**Comment by zhangda89** [comment]
hello.
davidzhang@davidzhang:~$ brew install --HEAD watchman
==> Cloning https://github.com/facebook/watchman.git
Updating /Library/Caches/Homebrew/watchman--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/watchman/HEAD --with-pcre
==> make
==> make install
🍺  /usr/local/Cellar/watchman/HEAD: 6 files, 196K, built in 41 seconds
davidzhang@davidzhang:~$ brew install --HEAD watchman
Warning: watchman-HEAD already installed
davidzhang@davidzhang:~$ brew link watchman
Warning: Already linked: /usr/local/Cellar/watchman/HEAD
To relink: brew unlink watchman && brew link watchman
davidzhang@davidzhang:~$ watchman -v
3.1.1
davidzhang@davidzhang:~$ 
===============================look
[Error: Watcher took too long to load
Try running `watchman` from your terminal
https://facebook.github.io/watchman/docs/troubleshooting.html]
Error: Watcher took too long to load
Try running `watchman` from your terminal
=======这个问题还是存在的

**Comment by wez** [comment]
I'm not sure what this is at the bottom; is that react native?  Sounds like you need to get a more recent version of it?
