### ISSUE TITLE
Unknown expression term "pcre"

### ISSUE THREAD

**Issue by bobzhang** [facebook/watchman#103]
when I run 
watchman -j < watchman.json

```json
[
    "trigger", ".", {
        "name": "html-build",
        "expression": ["pcre", 
                       "^[^.].*\\.(rst)$"
                       ],
        "command": ["make","-C", "..", "html"],
        "stderr" : ">./watchman.compile",
        "stdout" : ">./watchman.compile"
    }
]
```

**Comment by wez** [comment]
You need to install libpcre and recompile watchman to use pcre expressions.
You can use `["match", "*.rst"]` to achieve the same result as your pattern above:
https://facebook.github.io/watchman/docs/file-query.html#match-and-imatch
