### ISSUE TITLE
Operation not permitted after Mac Monterey upgrade

### ISSUE THREAD

**Issue by spiroalisandratos** [facebook/watchman#1038]
watchmanResponse: {
    error: 'std::__1::system_error: open: /Users/spiroalisandratos/Documents/VenyouDev/anotherTest: Operation not permitted',
    version: '20220611.225259.0'
  }
}

Node.js v18.4.0

**Comment by ShaunLWM** [comment]
I believe this is the same as https://github.com/facebook/watchman/issues/1030

**Comment by spiroalisandratos** [comment]
ok thanks.
