### ISSUE TITLE
Latest release is missing windows archive

### ISSUE THREAD

**Issue by rasaha91** [facebook/watchman#1046]
The [latest release](https://github.com/facebook/watchman/releases/tag/v2022.07.25.00) is missing the Windows archive. Looking at the actions page, it appears the [windows release](https://github.com/facebook/watchman/actions/workflows/getdeps_windows.yml) has been failing.

**Comment by xavierd** [comment]
Thanks for the report! I've sent a diff internally to fix this issue.

**Comment by xavierd** [comment]
https://github.com/facebook/watchman/commit/2aca3d0f78fdf04d19c6e80845a035c8302b81be should fix it.
