### ISSUE TITLE
Watchman fails to start in Fedora 36

### ISSUE THREAD

**Issue by pkrakesh** [facebook/watchman#1048]
I have installed watchman from binaries following these steps in the documentation
```
$ unzip watchman-*-linux.zip
$ cd watchman-vYYYY.MM.DD.00-linux
$ sudo mkdir -p /usr/local/{bin,lib} /usr/local/var/run/watchman
$ sudo cp bin/* /usr/local/bin
$ sudo cp lib/* /usr/local/lib
$ sudo chmod 755 /usr/local/bin/watchman
$ sudo chmod 2777 /usr/local/var/run/watchman
```

But when I try to invoke it the following error occurs:

```
terminate called after throwing an instance of 'std::system_error'
terminate called recursively
Aborted (core dumped)
```
Please help.

**Comment by IkKan** [comment]
+1

**Comment by Eznopot** [comment]
+1

**Comment by IkKan** [comment]
For anyone else seeing this issue on Fedora 36:

Installing watchman from binaries doesn't work but it looks like watchman is in the @fedora repo. So, just

1. Remove binaries from $PATH 
2. Install it with `sudo dnf install watchman`

And everything works like a charm...

**Comment by chadaustin** [comment]
We now build an RPM for Fedora 36. You can download it and follow the installation instructions at https://facebook.github.io/watchman/docs/install.html

I recommend against using the Fedora-provided Watchman, because it's old and missing bug and security fixes.
