### ISSUE TITLE
bind: No such file or directory

### ISSUE THREAD

**Issue by jamesarosen** [facebook/watchman#106]
I'm trying to run Watchman as follows:
```bash
sudo watchman\
  --log-level=2\
  --foreground\
  --logfile=/dev/stdout\
  --statefile=/etc/watchman/my-app.state\
  watch /path/to/my-project/
```
When I do, it outputs
```
1432763007: tid=2394625792 Using watcher mechanism inotify
1432763007: tid=2394625792 bind(/tmp/tmp.xq96eI2Grw/var/run/watchman/root): No such file or directory
```
then exits with status 1.

I'm sure `/etc/watchman/` exists and I have permission to write to it.

I'm running v3.1

**Comment by jamesarosen** [comment]
Or if I run it without `sudo`, then I get
```
1432763306: tid=3726362368 Using watcher mechanism inotify
1432763306: tid=3726362368 bind(/tmp/tmp.xq96eI2Grw/var/run/watchman/myuser): No such file or directory
```

**Comment by wez** [comment]
The error is that `/tmp/tmp.xq96eI2Grw/var/run/watchman/` doesn't exist, so watchman can't create a unix socket and bind to it.

It's not recommended to run watchman as root.  It should run as a regular user that has write permission to either the root of the repo or to the `.hg` or `.git` directory if present.

**Comment by jamesarosen** [comment]
Running it as myself just changes that to `/tmp/tmp.xq96eI2Grw/var/run/myuser` not existing. I can't quite figure out why it's looking for that directory.

My guess is that [this line](https://github.com/facebook/watchman/blob/v3.1/configure.ac#L59) is picking the directory. I don't see where `/tmp/tmp.xq96eI2Grw/` is coming from. If Watchman is making it up, why doesn't it create the directory?

**Comment by jamesarosen** [comment]
I'm building Watchman myself from source. I wonder if that prefix is somehow sneaking in at build time.

**Comment by wez** [comment]
The default prefix is usually /usr/local, so perhaps you're overriding that when you run configure?
Older versions of watchman would use your $TMP or $TMPDIR environment variable to locate this path.
You can force it to something else if you pass --sockname to the watchman binary (but you'd need to pass the same value to the client and the server).

**Comment by jamesarosen** [comment]
That's it! `./configure --prefix="\$BUILD_DIR"`
