### ISSUE TITLE
404 HTTP Error when retrieving zlib (Building from source)

### ISSUE THREAD

**Issue by DhiaAgrebi** [facebook/watchman#1067]
Downloaded the watchman source file about an hour ago and the issue still persists.
I'm building it from source using ./autogen.sh on Arch Linux.
Everything is fine except for the HTTP error as https://zlib.net/zlib-1.2.12.tar.gz is no longer available to download.

The package address is not at : https://zlib.net/fossils/zlib-1.2.12.tar.gz

**Comment by chadaustin** [comment]
Thank you - fix is coming soon. It should be landed by early next week.

**Comment by chadaustin** [comment]
Fixed in 9bcd7b1b12abeb566a1a37494d7ffb5f62692795
