### ISSUE TITLE
Nix build appears to fail in `fbcode_builder`

### ISSUE THREAD

**Issue by peterbecich** [facebook/watchman#1073]
Update: https://github.com/facebook/watchman/issues/1073#issuecomment-1321058283

-------------------

Hello, I am attempting to update the Nix package for Watchman, which is version 4.9: https://search.nixos.org/packages?channel=unstable&show=watchman&from=0&size=50&sort=relevance&type=packages&query=watchman

The build appears to fail here:
```
Traceback (most recent call last):
  File "/build/source/build/fbcode_builder/getdeps.py", line 1275, in <module>
    sys.exit(main())
  File "/build/source/build/fbcode_builder/getdeps.py", line 1258, in main
    return args.func(args)
  File "/build/source/build/fbcode_builder/getdeps.py", line 109, in run
    self.run_project_cmd(args, loader, manifest)
  File "/build/source/build/fbcode_builder/getdeps.py", line 575, in run_project_cmd
    cached_project = CachedProject(cache, loader, m)
  File "/build/source/build/fbcode_builder/getdeps.py", line 227, in __init__
    self.cache_file_name = "-".join(
TypeError: sequence item 1: expected str instance, NoneType found
```

which is:

https://github.com/facebook/watchman/blob/3e3b21c09d74f90b7342c26bbfa420c4e6b2da41/build/fbcode_builder/getdeps.py#L215-L236

The precise location of the error may be

https://github.com/facebook/watchman/blob/3e3b21c09d74f90b7342c26bbfa420c4e6b2da41/build/fbcode_builder/getdeps.py#L230

Can/should this be changed to 
```
self.ctx.get("os") or "none",
```
?

This error can be replicated by checking out https://github.com/peterbecich/nixpkgs/tree/update-watchman ,
then `cd` to `pkgs/development/tools/watchman`,
and `nix-build`

Thank you

**Comment by peterbecich** [comment]
This may have been resolved here: https://github.com/NixOS/nixpkgs/pull/181787

**Comment by kylesferrazza** [comment]
Builds in my PR, just finishing up the review process to get it merged into nixpkgs, but nothing to fix on this side -- this issue can be closed.
