### ISSUE TITLE
ReactNative: Watcher took too long to load 

### ISSUE THREAD

**Issue by chbfiv** [facebook/watchman#108]
I recommend adding
brew update to the steps before installing watchman for reactnative
http://facebook.github.io/react-native/docs/getting-started.html#content

https://facebook.github.io/watchman/docs/troubleshooting.html
resolved my issue (using watchman 3.1)

http://facebook.github.io/react-native/docs/troubleshooting.html#content
did not resolve my problem because it install watchman 3.2 which seems to have the issue again sadly.

**Comment by wez** [comment]
Please file the react native portion of this in the react native project.
Please elaborate on what you observed with the HEAD watchman itself here in this issue.
If possible, please try a watchman HEAD install again now so that we can infer the commit hash of the watchman version you're using.

**Comment by wez** [comment]
I'm closing this due to lack of information.  If you're still having problems, please re-open and provide the requested information.
