### ISSUE TITLE
docs: statedir appears to no longer default to /tmp

### ISSUE THREAD

**Issue by mread** [facebook/watchman#109]
At some point in the last few months watchman appears to look for a statedir in `/usr/local/var/`. Attempting to override it with  `--enable-statedir=/tmp` has no effect.

```
bind(/usr/local/var/run/watchman/mread): No such file or directory
```

**Comment by mread** [comment]
Correction - `--enable-statedir=/tmp` does appear to work. In which case there's probably just a mismatch between documentation and behaviour - it doesn't default to /tmp, it defaults to ${prefix}/var/run

**Comment by wez** [comment]
Thanks; we'll update the docs
