### ISSUE TITLE
watchman/cli: build failure on macOS with 2023.02.20.00

### ISSUE THREAD

**Issue by ZhongRuoyu** [facebook/watchman#1099]
Hi. While packaging watchman 2023.02.20.00 for Homebrew at https://github.com/Homebrew/homebrew-core/pull/123742, we encountered the following issue (full build log [here](https://github.com/Homebrew/homebrew-core/actions/runs/4223152811/jobs/7332641767), error starting [here](https://github.com/Homebrew/homebrew-core/actions/runs/4223152811/jobs/7332641767#step:6:1154)):

```
     Compiling watchmanctl v0.1.0 (/private/tmp/watchman-20230220-76673-1xd2pk6/watchman-2023.02.20.00/watchman/cli)
  error[E0583]: file not found for module `facebook`
    --> src/rage/mod.rs:33:1
     |
  33 | mod facebook;
     | ^^^^^^^^^^^^^
     |
     = help: to create the module `facebook`, create file "src/rage/facebook.rs" or "src/rage/facebook/mod.rs"
  
  error[E0432]: unresolved import `super::facebook::FbReporter`
    --> src/rage/stream.rs:13:9
     |
  13 | pub use super::facebook::FbReporter;
     |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `FbReporter` in `rage::facebook`
  
  Some errors have detailed explanations: E0432, E0583.
  For more information about an error, try `rustc --explain E0432`.
  error: could not compile `watchmanctl` due to 2 previous errors
  make[2]: *** [watchman/cli/CMakeFiles/watchmanctl.cargo] Error 101
  make[1]: *** [watchman/cli/CMakeFiles/watchmanctl.cargo.dir/all] Error 2
  make: *** [all] Error 2
```

This error was observed on a macOS 12 system with Apple Silicon. The Rust version is 1.67.1.

Our CMake invocation is:

```
cmake -S . -B build \
  -DENABLE_EDEN_SUPPORT=ON \
  -DWATCHMAN_VERSION_OVERRIDE=2023.02.20.00 \
  -DWATCHMAN_BUILDINFO_OVERRIDE=Homebrew \
  -DWATCHMAN_STATE_DIR=/opt/homebrew/var/run/watchman \
  -DCMAKE_INSTALL_PREFIX=/opt/homebrew/Cellar/watchman/2023.02.20.00 \
  -DCMAKE_INSTALL_LIBDIR=lib \
  -DCMAKE_BUILD_TYPE=Release \
  -DCMAKE_FIND_FRAMEWORK=LAST \
  -DCMAKE_VERBOSE_MAKEFILE=ON \
  -Wno-dev \
  -DBUILD_TESTING=OFF \
  -DCMAKE_OSX_SYSROOT=/Library/Developer/CommandLineTools/SDKs/MacOSX12.sdk
```

We believe that the error is with [this line](https://github.com/facebook/watchman/blob/v2023.02.20.00/watchman/cli/Cargo.toml#L32):

```toml
default = ["fb"]
```

Which should instead read:

```toml
default = []
```

**Comment by carlocab** [comment]
I haven't bisected (or tried a revert -- yet), but the only change in the CLI code is in this commit: https://github.com/facebook/watchman/commit/0b853de5e0a0d75dce36a0de32f5024ccb4acbdc

It looks like the `fb` feature is meant to be gated by the CMake cache variable `IS_FB_BUILD`:

https://github.com/facebook/watchman/blob/7f619ba5f170423744cb7778dccb0bb160f0a0d8/watchman/cli/CMakeLists.txt#L6-L10

However, 0b853de5e0a0d75dce36a0de32f5024ccb4acbdc makes it so that the `fb` feature is added by default. Presumably this feature only works for internal builds and not the open source one.

CC @fanzeyi

**Comment by carlocab** [comment]
> We believe that the error is with [this line](https://github.com/facebook/watchman/blob/v2023.02.20.00/watchman/cli/Cargo.toml#L32):
> 
> ```toml
> default = ["fb"]
> ```
> 
> Which should instead read:
> 
> ```toml
> default = []
> ```

Making this change allows our build to succeed.

**Comment by fanzeyi** [comment]
Ah sorry. I thought the CMake setting will override this. Will send a fix tomorrow.

**Comment by fanzeyi** [comment]
Should be fixed in https://github.com/facebook/watchman/commit/6b0361c3464efcb5b7db11937f0bd9f84c865914

**Comment by ZhongRuoyu** [comment]
Thanks @fanzeyi. I can confirm that this is fixed.
