### ISSUE TITLE
Commit 4464d43c357aba7f1358fd572542427dc6799a3d breaks build on linux

### ISSUE THREAD

**Issue by lym** [facebook/watchman#110]
Building the code against the current commit fails, on linux, with:

    .......
    CC       watchman-log.o
    log.c: In function ‘w_set_thread_name’:
    log.c:47:12: error: ignoring return value of ‘vasprintf’, declared with attribute warn_unused_result [-   Werror=unused-result]
    vasprintf(&name, fmt, ap);
            ^
    cc1: all warnings being treated as errors
    make[1]: *** [watchman-log.o] Error 1
    .........

When I check out commit 1d84df2f01eba45194e6d259df5c2fffecb660bf and rebuild, watchman gets installed. I noticed by going through the git logs that the commit in the title of this issue might be the cause of the breakage as it introduces the function `w_set_thread_name()` which contains the section at which `make` seems to be whining.

my system is:
Ubuntu linux 14.04LTS with ubuntu's packaged 3.13.0-44-generic kernel.

**Comment by wez** [comment]
Thanks for reporting this!

**Comment by lym** [comment]
It builds fine against the latest commit now :-)
