### ISSUE TITLE
Ubuntu packags missing since May

### ISSUE THREAD

**Issue by andrewnicols** [facebook/watchman#1150]
All releases since May are missing Ubuntu packages.

See an example of the failing build here: https://github.com/facebook/watchman/actions/runs/5505064162/jobs/10032023257

**Comment by xendarboh** [comment]
The failing build logs indicate `sudo` package is missing.
Looks like it could be fixed by adding `sudo` to this line:

https://github.com/facebook/watchman/blob/main/watchman/build/package/ubuntu-env/Dockerfile#L10

**Comment by chadaustin** [comment]
I've been meaning to look at this and haven't had a chance. @xendarboh I think you're on the right track. Want to put up a PR with that fix? We should be able to tell from the PR itself whether the GitHub Actions succeed.

**Comment by xendarboh** [comment]
@chadaustin PR submitted.
