### ISSUE TITLE
Installation guide

### ISSUE THREAD

**Issue by kuldeepaher01** [facebook/watchman#1153]
I wanted to install watchman for react native. I am getting redirected to https://github.com/facebook/watchman/releases/tag/v2023.07.24.00 when i click on ubuntu installation from prebuilt binaries, but I am not able to see any .deb only tar.gz and zip files are present I have spent 2 hours figuring out and couldn't install. Please add installation instructions clearly

**Comment by that-one-arab** [comment]
Hey man. I was doing the same thing.

Here's what worked for me:

- Follow the steps in [building from source](https://facebook.github.io/watchman/docs/install/#-building-from-source). This includes installing cargo, then compiling the project yourself. Keep in mind this might take a while
- cd into the newly created `built` directory that contains the compiled bins
- Run the following commands:
```sh
$ sudo mkdir -p /usr/local/bin /usr/local/var/run/watchman
$ sudo cp bin/* /usr/local/bin
$ sudo chmod 755 /usr/local/bin/watchman
$ sudo chmod 2777 /usr/local/var/run/watchman
```

**Comment by that-one-arab** [comment]
Hey I was doing the same thing.

Here's what worked for me:

- Follow the steps in [building from source](https://facebook.github.io/watchman/docs/install/#-building-from-source). This includes installing cargo, then compiling the project yourself. Keep in mind this might take a while
- cd into the newly created `built` directory that contains the compiled bins
- Run the following commands:
```sh
$ sudo mkdir -p /usr/local/bin /usr/local/var/run/watchman
$ sudo cp bin/* /usr/local/bin
$ sudo chmod 755 /usr/local/bin/watchman
$ sudo chmod 2777 /usr/local/var/run/watchman
```

**Comment by abhinav700** [comment]
@kuldeepaher01 Looks like they have abandoned the .deb approach. Last [this](https://github.com/facebook/watchman/releases/tag/v2023.05.01.00) is the last version that I could find the .deb package for.

**Comment by quux-aivar** [comment]
> @kuldeepaher01 Looks like they have abandoned the .deb approach. [this](https://github.com/facebook/watchman/releases/tag/v2023.05.01.00) is the last version that I could find the .deb package for.

It appears that the entire project has been abandoned. Fedora packages are not provided either.

Documentation states clearly:

> Warning: Do not install the Fedora-supplied Watchman package. It is old and missing security, bug, and performance fixes.

https://facebook.github.io/watchman/docs/install#fedora-prebuilt-rpms

Unfortunately, Fedora 39 RPM package is not available.

**Comment by jerryphm** [comment]
install via homebrew solved this problem

**Comment by kuldeepaher01** [comment]
> @kuldeepaher01 Looks like they have abandoned the .deb approach. [this](https://github.com/facebook/watchman/releases/tag/v2023.05.01.00) is the last version that I could find the .deb package for.

Thank you, after a year later im stuck here again lol

**Comment by sovetski** [comment]
this issue is closed but the documentation is not up to date...
