### ISSUE TITLE
Usage within Gulp

### ISSUE THREAD

**Issue by jeff-h** [facebook/watchman#117]
Sorry for the basic question, but I've not been able to find anything talking about how to use watchman from Gulp. Is it possible?

**Comment by wez** [comment]
I'm not familiar with gulp, but a quick search reveals this plugin:
https://www.npmjs.com/package/gulp-sane-watch/
sane can be configured to use watchman

**Comment by jeff-h** [comment]
I assumed Watchman would be much more widely used inside Gulp, but after posting my question here I did a whole lot of reading on a couple of Chokidar / Watchman threads and have a much better context on where things stand now.

Thanks for you reply!
