### ISSUE TITLE
Unable to install watchman on arch

### ISSUE THREAD

**Issue by schrodingersca8** [facebook/watchman#1186]
I am unable to install watchman on Arch Linux, I have tried nearly every possible way
1) AUR: getting error
2) clone and ./autogen.sh error
3) download .tar.gz and unzip: No bin directory to copy

Please help me.

**Comment by Dogfetus** [comment]
list your errors?

**Comment by schrodingersca8** [comment]
> list your errors?

Thanks for replying and apologies for not doing that.

Well, I installed brew on arch and installed watchman via that and it was really smooth.

**Comment by ArturC03** [comment]
I'm on arch and i it isnt working with brew, CMake returns error

```bash
CMake Error at CMakeLists.txt:15 (cmake_minimum_required):
  Compatibility with CMake < 3.5 has been removed from CMake.

  Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
  to tell CMake that the project requires at least <min> but has been updated
  to work with policies introduced by <max> or earlier.

  Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```
