### ISSUE TITLE
Tags out of date

### ISSUE THREAD

**Issue by whiteley** [facebook/watchman#119]
The [release notes](https://facebook.github.io/watchman/docs/release-notes.html) and the [releases](https://github.com/facebook/watchman/releases) are out of sync.

I see that the version scheme was discussed in #97 but the tags aren't mentioned. Are they meant to be authoritative for versions moving forward? I'd like to use them for packaging.

Thanks!

**Comment by wez** [comment]
I think @sid0 may have forgotten to push the tags for the last two releases

**Comment by sid0** [comment]
Pushed, thanks for catching this. I hate git.
