### ISSUE TITLE
installation error on Mac

### ISSUE THREAD

**Issue by wanghaisheng** [facebook/watchman#120]
edwin@edwindembp:/Users/edwin/Documents/workfolder/workspace/watchman  git:(master) $  brew install --HEAD watchman
==> Cloning https://github.com/facebook/watchman.git
Updating /Library/Caches/Homebrew/watchman--git
==> Checking out branch master
==> ./autogen.sh
==> ./configure --prefix=/usr/local/Cellar/watchman/HEAD --with-pcre
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/tmp/watchman20150717-47291-1qmdkrm':
configure: error: C compiler cannot create executables
See `config.log' for more details

READ THIS: https://git.io/brew-troubleshooting

**Comment by wez** [comment]
This isn't a watchman issue, it's a problem with your compilation environment.
Read the troubleshooting link at the bottom of what you included in your report and if that doesn't help, you should follow up with the folks at the homebrew project.

**Comment by wanghaisheng** [comment]
mac osx 10.10.4   xcode don`t have gcc installed.
solution would be 
brew install homebrew/versions/gcc5
brew link gcc


ln -sf /usr/local/Cellar/gcc/5.2.0/bin/gcc-5 /usr/local/Cellar/gcc/5.2.0/bin/gcc 
ln -sf /usr/local/Cellar/gcc/5.2.0/bin/g++-5 /usr/local/Cellar/gcc/5.2.0/bin/g++ 
ln -sf /usr/local/Cellar/gcc/5.2.0/bin/c++-5 /usr/local/Cellar/gcc/5.2.0/bin/c++ 
ln -sf /usr/local/Cellar/gcc/5.2.0/bin/cpp-5 /usr/local/Cellar/gcc/5.2.0/bin/cpp 
ln -sf /usr/local/Cellar/gcc/5.2.0/bin/gfortran-5 /usr/local/Cellar/gcc/5.2.0/bin/gfortran

add the following to ~/.zshrc

export PATH=/usr/local/Cellar/gcc/5.2.0/bin:$PATH
export DYLD_LIBRARY_PATH=/usr/local/Cellar/gcc/5.2.0/lib/gcc/5:$DYLD_LIBRARY_PATH

**Comment by sifat23** [comment]
Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

==> Installing dependencies for watchman: rust, boost, double-conversion, gflags, glog, libevent, lz4, snappy, folly, cpptoml, fizz, wangle, fbthrift and fb303
==> Installing watchman dependency: rust
Warning: A newer Command Line Tools release is available.
Update them from Software Update in System Preferences or run:
  softwareupdate --all --install --force

If that doesn't show you any updates, run:
  sudo rm -rf /Library/Developer/CommandLineTools
  sudo xcode-select --install

Alternatively, manually download them from:
  https://developer.apple.com/download/all/.
You should download the Command Line Tools for Xcode 11.3.1.

==> ./configure --prefix=/usr/local/Cellar/rust/1.59.0 --enable-vendor --release-channel=stable
==> make

here it stuck. Nothing would be happen if i wait decades... what should i do??

**Comment by amorozdna** [comment]
@sifat23 
Stuck forever on the same line (making Rust) for me too:
```
==> Installing dependencies for awscli: rust
==> Installing awscli dependency: rust
==> ./configure --prefix=/usr/local/Cellar/rust/1.59.0 --enable-vendor --release-channel=stable
==> make
```
