### ISSUE TITLE
how to install without root privileges ?

### ISSUE THREAD

**Issue by akabab** [facebook/watchman#124]
it seems necessary to have some root privileges to install watchman. Is it possible to do without ?
from source:
![screen shot 2015-08-06 at 13 44 24](https://cloud.githubusercontent.com/assets/6205705/9110831/48119f0c-3c41-11e5-8b5f-905b78c0b399.png)
from brew: I keep getting abort error when lauching watchman commands
![screen shot 2015-08-06 at 12 54 33](https://cloud.githubusercontent.com/assets/6205705/9110842/5c2f0e2a-3c41-11e5-991a-bf3f32e62df5.png)

So then I can't use react-native, having “Watcher took too long to load” error.

**Comment by wez** [comment]
Homebrew doesn't have watchman 3.7 yet (https://github.com/Homebrew/homebrew/pull/42519 is tracking that) and it sounds like there is something not quite right with your build environment.

Please try:

```
brew uninstall --force watchman
brew update
brew install watchman
```

You do not need to perform a `HEAD` install (and really should not right now, as we just landed a bunch of slightly experimental code in head).

If the brew build fails, it should suggest some troubleshooting steps to you.

Regarding root privileges, it is not strictly needed to have root privileges, but I have to ask why you don't have root access on your mac, as it seems unusual?

**Comment by stefanpenner** [comment]
I suspect homebrew hasn't been set up correctly. The following link: https://github.com/Homebrew/homebrew/blob/master/share/doc/homebrew/FAQ.md#why-does-homebrew-say-sudo-is-bad- may be of value.

**Comment by akabab** [comment]
@wez, I'm at school.

**Comment by wez** [comment]
@akabab in that case, I'd recommend that you do something like this:

```
cd watchman
./configure --prefix=$HOME
make
make install
PATH=$HOME/bin:$PATH
```

**Comment by akabab** [comment]
thanks @wez
