### ISSUE TITLE
can watch a directory with millions file in a short time?

### ISSUE THREAD

**Issue by xiedeacc** [facebook/watchman#1242]
I cannot find performance data from docs, so ask here

**Comment by xiedeacc** [comment]
it there any describtion about principle

**Comment by MichaelCuevas** [comment]
>can watch a directory with millions file in a short time?

No. Watchman must build up an in-memory view of the directory when a watch request is first made. It must crawl the entire directory to build up the index, and this crawling takes a significant amount of time and scales with the size of the directory. Watchman may also encounter other scaling issues at 1m+ files.

**Comment by xiedeacc** [comment]
ok, thanks
