### ISSUE TITLE
No root privilege,but the limit fs.inotify.max_user_watches was reached

### ISSUE THREAD

**Issue by zhengyang3** [facebook/watchman#132]
I am just a normal user , no root privilege,  the limit max_user_watches is  just 8192 , I made watchman working on a very large project , so it reached the limit .    It can work for me no longer  just say:  " "error": a non-recoverable condition has triggerred. ........increase the  fs.inotify.max.user.watches ........"
How can solve it with no root privilege???

**Comment by wez** [comment]
I'm sorry, but there is no way to raise that limit without root privileges.  Since watchman relies on OS filesystem change notifications there is no other way to make watchman work on a tree where the number of directories exceeds the `max_user_watches` system limit.
