### ISSUE TITLE
Installing watchman in Snow Leopard

### ISSUE THREAD

**Issue by Juanacv** [facebook/watchman#133]
Hello

I am trying to install watchman in Os X Snow Leopard and I am obtaining this error:

MACOSX_DEPLOYMENT_TARGET='10.6'
:debug:build Assembled command: 'cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0" && /usr/bin/make -j4 -w all'
:debug:build Executing command line:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0" && /usr/bin/make -j4 -w all 
:info:build make: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0'
:info:build /usr/bin/make  all-am
:info:build make[1]: Entering directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0'
:info:build   CC       watcher/watchman-fsevents.o
:info:build   CC       watchman-listener.o
:info:build   CC       tests_log_t-log.o
:info:build   CCLD     tests/argv.t
:info:build watcher/fsevents.c: In function ‘fsevents_thread’:
:info:build watcher/fsevents.c:229: error: ‘kFSEventStreamCreateFlagFileEvents’ undeclared (first use in this function)
:info:build watcher/fsevents.c:229: error: (Each undeclared identifier is reported only once
:info:build watcher/fsevents.c:229: error: for each function it appears in.)
:info:build make[1]: *** [watcher/watchman-fsevents.o] Error 1
:info:build make[1]: *** Waiting for unfinished jobs....
:info:build cc1: warnings being treated as errors
:info:build listener.c: In function ‘w_start_listener’:
:info:build listener.c:737: warning: ISO C90 forbids mixed declarations and code
:info:build make[1]: *** [watchman-listener.o] Error 1
:info:build make[1]: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0'
:info:build make: *** [all] Error 2
:info:build make: Leaving directory `/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0'
:info:build Command failed:  cd "/opt/local/var/macports/build/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/work/watchman-3.5.0" && /usr/bin/make -j4 -w all 
:info:build Exit code: 2
:error:build org.macports.build for port watchman returned: command execution failed
:debug:build Error code: CHILDSTATUS 601 2
:debug:build Backtrace: command execution failed
    while executing
"system -nice 0 $fullcmdstring"
    ("eval" body line 1)
    invoked from within
"eval system $notty $nice \$fullcmdstring"
    invoked from within
"command_exec build"
    (procedure "portbuild::build_main" line 8)
    invoked from within
"portbuild::build_main org.macports.build"
    ("eval" body line 1)
    invoked from within
"eval $procedure $targetname"
:info:build Warning: targets not executed for watchman: org.macports.activate org.macports.build org.macports.destroot org.macports.install
:notice:build Please see the log file for port watchman for details:
    /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_release_ports_sysutils_watchman/watchman/main.log

Any clue?

Thank you very much

**Comment by wez** [comment]
Ah, looks like you need to be on 10.7 or later for our fsevents support to work.

You may be able to get things working if you're up for a bit of hacking:

Follow the [manual build instructions](http://facebook.github.io/watchman/docs/install.html#installing-from-source), but stop after you have run configure.

Edit watchman.h and comment out the `HAVE_FSEVENTS` line.

Then continue with the `make`.

This should fall back to the kqueue/kevent watcher implementation.
Note that you will likely need to raise system limits for things to work well, because kqueue/kevent require that we open a file for each watched item.  The log file will tell you if that happens.

**Comment by wez** [comment]
I think this diff will resolve this properly:

```diff
diff --git a/watchman.h b/watchman.h
index c09b318..864e7f9 100644
--- a/watchman.h
+++ b/watchman.h
@@ -105,7 +105,11 @@ extern char *poisoned_reason;

 #ifdef HAVE_CORESERVICES_CORESERVICES_H
 # include <CoreServices/CoreServices.h>
-# define HAVE_FSEVENTS 1
+# if __ENVIRONMENT_MAC_OS_X_VERSION_MIN_REQUIRED__ < 1070
+#  define HAVE_FSEVENTS 0
+# else
+#  define HAVE_FSEVENTS 1
+# endif
 #endif

 // Helpers for pasting __LINE__ for symbol generation
```

**Comment by wez** [comment]
If you can confirm the above, I'll get this pushed

**Comment by Juanacv** [comment]
Another error:

cc1: warnings being treated as errors
ioprio.c: In function ‘adjust_ioprio’:
ioprio.c:29: warning: unused parameter ‘low’
make[1]: *** [watchman-ioprio.o] Error 1
make: *** [all] Error 2

Maybe I should update...

Thank you very much

**Comment by wez** [comment]
I just pushed f325fbc819f6111867f268a03dcc912d90b05595 with fixes for both of those, let's see how that works for you

**Comment by Juanacv** [comment]
Sorry, another error :(

cc1: warnings being treated as errors
listener.c: In function ‘w_start_listener’:
listener.c:936: warning: ISO C90 forbids mixed declarations and code
make[1]: *** [watchman-listener.o] Error 1
make: *** [all] Error 2

**Comment by wez** [comment]
Try this:

```diff
diff --git a/listener.c b/listener.c
index c563a2c..2377410 100644
--- a/listener.c
+++ b/listener.c
@@ -933,6 +933,7 @@ bool w_start_listener(const char *path)
     getrlimit(RLIMIT_NOFILE, &limit);

 # ifndef __OpenBSD__
+    {
     size_t len;

     len = sizeof(maxperproc);
@@ -940,6 +941,7 @@ bool w_start_listener(const char *path)
     w_log(W_LOG_ERR, "file limit is %" PRIu64
         " kern.maxfilesperproc=%i\n",
         limit.rlim_cur, maxperproc);
+    }
 # else
     maxperproc = limit.rlim_max;
     w_log(W_LOG_ERR, "openfiles-cur is %" PRIu64
```

**Comment by Juanacv** [comment]
It works but now I have this strange error, I think it would be better to update:

building 'pywatchman.bser' extension
creating build
creating build/temp.macosx-10.6-x86_64-2.6
creating build/temp.macosx-10.6-x86_64-2.6/pywatchman
gcc-4.2 -fno-strict-aliasing -fno-common -dynamic -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -Wno-error=unused-command-line-argument-hard-error-in-future -pipe -Wno-error=unused-command-line-argument-hard-error-in-future -I/System/Library/Frameworks/Python.framework/Versions/2.6/include/python2.6 -c pywatchman/bser.c -o build/temp.macosx-10.6-x86_64-2.6/pywatchman/bser.o
cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
cc1: error: -Werror=unused-command-line-argument-hard-error-in-future: No option -Wunused-command-line-argument-hard-error-in-future
error: command 'gcc-4.2' failed with exit status 1
make[1]: *** [py-build] Error 1
make: *** [all] Error 2

Thank you very much

**Comment by wez** [comment]
If you run:

```bash
./configure --without-python
make
````

then you can probably skip that error.

But yes: I would recommend upgrading to a more recent version of OS X if possible.

**Comment by Juanacv** [comment]
It works, finally, but, How this gonna affect the way watchman works? I wanted to use it together with ember 2.0 and I don't know what is the role of watchman

Thank you

**Comment by wez** [comment]
Your build will use the underlying kevent/kqueue system facility for file change notifications.  We used to use this by default in earlier versions of Watchman.  It is also used on FreeBSD and OpenBSD.   I ran our integration test on my 10.10 installation but with kevent enabled and it passed its tests, so you should have no functional problems.

You may however need to raise your system limits to accommodate watching the directories of interest.
The default limit on OS X is very low.  Watchman will try to raise it on startup; you'll see something like this in your log file:

```
2015-08-15T15:21:06,279: [listener] file limit is 256 kern.maxfilesperproc=10240
```

This means that you can watch up to `10240` (or whatever number you see on that line) total files and directories before you hit the system limit.  If Watchman is unable to raise the file limit to the system limit, you'll see another line with an error message.

If you hit the system limit, watchman will be unable to notify you of changes, which means that ember won't automatically rebuild things as you make changes.

You can raise the limit by following the instruction that are in red in this changeset:

https://github.com/facebook/watchman/commit/20dbfd48ffc5b41c506b12b79ce9c4d00e54d31d#diff-e94ba8063cbe3fc47d19c80ef488d161

**Comment by wez** [comment]
I've restored that information to our main docs:
http://facebook.github.io/watchman/docs/install.html#max-os-file-descriptor-limits

**Comment by Juanacv** [comment]
Thank you a lot for your help.

**Comment by wez** [comment]
You're welcome!
