### ISSUE TITLE
docs: mention python-dev and setuptools dependencies.

### ISSUE THREAD

**Issue by c4milo** [facebook/watchman#139]
A friend and I bumped into two issues following the installation instructions provided in the website. We were missing `setuptools` and `python-dev` headers. 

After running the following we got watchman to compile fine:

```
sudo apt-get install python-setuptools
sudo apt-get install python-dev
```

**Comment by wez** [comment]
Thanks for raising this, just noticed this the other day when testing on Solaris.  This kind of sneaked by because our CI systems have these installed already.  I'll update the docs.

**Comment by wez** [comment]
I pushed the doc update earlier today

**Comment by c4milo** [comment]
👍
