### ISSUE TITLE
Fire all triggers on multiple matches?

### ISSUE THREAD

**Issue by rameshdharan** [facebook/watchman#141]
I was surprised by this behavior: 

```
$ watchman watch-project test/
$ watchman -- trigger /tmp/test js_first '*.js' -- ls -l
$ watchman -- trigger /tmp/test js_second '*.js' -- ls
$ touch /tmp/test/foo.js
```

Inspection of the Watchman log shows that only the first trigger, js_first, was fired. If I unregister the first trigger, then the second one fires. 

Would it be possible to have a mode where all matching triggers are fired, or is that prohibitively difficult or expensive for some reason?

**Comment by rameshdharan** [comment]
This appears to be a regression in 3.7.0 (at least with the version installed by `brew install watchman`). 

I manually built version 3.5.0 from the release tag and it does not seem to exhibit the same behavior, i.e. all triggers are fired.

**Comment by wez** [comment]
Thanks for reporting this.  I can't reproduce this in master in our integration test suite.

We have an existing set of trigger tests that pass successfully (`test/integration/trigger.php`) and I put together this one https://gist.github.com/wez/ccc7969f6714030886ee that more closely matches what you describe.

Would you mind sending me your log file from the time where this wasn't working?

**Comment by wez** [comment]
@rameshdharan could you send me more info on this?  I'm afraid that I can't reproduce it.
