### ISSUE TITLE
Unable to talk to your watchman 

### ISSUE THREAD

**Issue by bitsoflogic** [facebook/watchman#143]
On Centos 6.7
```
$ watchman -v 
3.7.0

$ watchman watch ~/Projects/testapp/
2015-09-05T14:21:48,161: [cli] unable to talk to your watchman on /usr/local/var/run/watchman/bitsoflogic!

$ which watchman
/usr/local/bin/watchman
```
I've tried going through the installation process again and it appears to work without issue however it still isn't working.  My goal is to use this with ember-cli.

Thoughts?

**Comment by wez** [comment]
Can you take a look in and share your logs?
http://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

You may want to try running `watchman --foreground` (which runs the service in the foreground) and see if that adds any additional diagnostics over what you see in the logs

**Comment by bitsoflogic** [comment]
Thanks for the insights!  This led me to the fix; I needed to bump up my inotify configuration.

```
/etc/sysctl.conf

# for watchman
fs.inotify.max_user_watches = 32768
fs.inotify.max_queued_events = 32768
```
