### ISSUE TITLE
Accidentally uninstalled - now it won't reinstall

### ISSUE THREAD

**Issue by tgoldenberg** [facebook/watchman#153]
I accidentally uninstalled via `brew uninstall watchman`. Now if I try `brew install watchman`, all I get is 
codebuild: error: SDK "/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk" cannot be located.
otool: error: unable to find utility "otool", not a developer tool or in PATH
Error: Failure while executing: /usr/bin/otool -L /usr/bin/install_name_tool

What should I do?

**Comment by wez** [comment]
Sounds like a homebrew/Xcode configuration issue.  We can't directly help you with this, but you should probably start by running `brew doctor` and then reach out to the homebrew folks if that doesn't help you resolve it.
