### ISSUE TITLE
wathcman dosen`t support OS X10.11 ?

### ISSUE THREAD

**Issue by qmkCamel** [facebook/watchman#168]
Warning: You are using OS X 10.11.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.

This is the prompt info when I install the watchman.

**Comment by DomT4** [comment]
That's a `brew` error message, and one we removed almost three weeks ago now. Please `brew update`.

**Comment by qmkCamel** [comment]
Thanks .

**Comment by wez** [comment]
Was an issue with the brew environment being out of date
