### ISSUE TITLE
Dangling symlinks missed in OSX

### ISSUE THREAD

**Issue by bmdhacks** [facebook/watchman#172]
This is an OSX bug, but I figured I'd fill you guys in because it's causing Twitter all kinds of headaches.  Here's a repro:

```
#!/usr/bin/env bash

set -x

watchman watch .
watchman since . n:foo
ls -lh path0sym
mkdir path2 path3 path3/subp3
paths="path0 path2/file2 path3/file3 path3/subp3/file3"
(
  for p in $paths
    do
        echo "hello $p" >$p || exit 1
        ln -s "hello $p" ${p}sym || exit 1
    done
)
ls -lh path0sym
```

   watchman since . n:foo

Note that the second 'since' query doesn't return any of the *sym files that were created.  Change `"hello $p"` to `"$(basename $p)"` and it will work.

**Comment by wez** [comment]
Thanks for reporting.  I beefed up your script a bit and traced through.  We get absolutely no notifications from fsevents when a broken symlink is created, not even on the containing directory.

I don't think we'll have a great way to detect this with fsevents; the best we can do is to periodically poll and crawl the filesystem to discover this type of change.

```
$ git diff root.c
diff --git a/root.c b/root.c
index 5ff74e1..5637384 100644
--- a/root.c
+++ b/root.c
@@ -2051,7 +2051,7 @@ static const struct watchman_hash_funcs root_funcs = {
 void watchman_watcher_init(void) {
   watched_roots = w_ht_new(4, &root_funcs);

-#if HAVE_FSEVENTS
+#if HAVE_FSEVENTS_NOPE
   watcher_ops = &fsevents_watcher;
 #elif defined(HAVE_PORT_CREATE)
   // We prefer portfs if you have both portfs and inotify on the assumption
```

can you try the above patch?  That will make watchman use kqueue directly.
You'll probably want to bump up your limits per https://facebook.github.io/watchman/docs/install.html#max-os-file-descriptor-limits

**Comment by avsm** [comment]
According to an Apple Radar bug I filed, this should now be fixed in OSX 10.12 upwards:

> The original report on this issue, Bug ID 23193224, is closed.
> If you still see the issue in macOS 10.12, please file a new bug report.  The issue should be resolved there.

**Comment by wez** [comment]
Confirmed fixed; I'll be pushing a commit to re-enable the tests for this situation on macOS and will close out this issue.  Thanks for letting me know!

**Comment by wez** [comment]
https://github.com/facebook/watchman/commit/464d64308a39752dca6f51f313470cca75e2ad88
had a flubbed URL back to this, so here's the manual cross link.
