### ISSUE TITLE
pywatchman 1.2.0 not installing scripts

### ISSUE THREAD

**Issue by tony** [facebook/watchman#175]
FreeBSD 11-CURRENT
pip 7.1.2
Python 2.7.10

Steps to recreate

``pip install --user pywatchman`` or ``pip install pywatchman`` (via virtualenv)

Scripts are not available or installed to the ``bin`` of the environment.

The desired behavior of installing pywatchman should have ``watchman-wait`` and ``watchman-make`` available to the user via CLI, right?

**Comment by wez** [comment]
Thanks for reporting; I hadn't bumped up the pywatchman release yet, but did just now; pywatchman 1.3 should now be available and include these new tools.

**Comment by tony** [comment]
Upgraded, ``watchman-make`` and ``watchman-wait`` are now available.

```
$ watchman-make -p '**.py' --make ./run-tests.py -t test                                                                                               
Traceback (most recent call last):
  File "/usr/home/tony/study/python/tmuxp/.env/bin/watchman-make", line 171, in <module>
    required=['cmd-watch-project', 'wildmatch'])
  File "/usr/home/tony/study/python/tmuxp/.env/lib/python2.7/site-packages/pywatchman/__init__.py", line 504, in capabilityCheck
    'required': required or []})
  File "/usr/home/tony/study/python/tmuxp/.env/lib/python2.7/site-packages/pywatchman/__init__.py", line 488, in query
    self._connect()
  File "/usr/home/tony/study/python/tmuxp/.env/lib/python2.7/site-packages/pywatchman/__init__.py", line 398, in _connect
    self.sockpath = self._resolvesockname()
  File "/usr/home/tony/study/python/tmuxp/.env/lib/python2.7/site-packages/pywatchman/__init__.py", line 377, in _resolvesockname
    raise WatchmanError('"watchman" executable not in PATH (%s)', e)
pywatchman.WatchmanError: ('"watchman" executable not in PATH (%s)', OSError(2, 'No such file or directory'))
```

I'm confused. I was under the impression that installing from pip would preclude the need to have watchman compiled manually / installed via package manager.

What's the intention of pywatchman?

**Comment by tony** [comment]
The result I want to get is have a cross-platform file watcher that works straight from pip, including the OS-specific stuff. And maybe even building some wheels out of it.

It's been kind of a long journey trying to get the right solution for file watching in python:

- https://github.com/tony/watching-testrunner - heh, from a while ago, no support for File system events.
- https://github.com/jeffh/sniffer (requires manually installing other packages for OS, no FreeBSD support) - this is what I'm currently using
- entr(1) - http://entrproject.org/ https://bitbucket.org/eradman/entr/ - Currently experimenting with this. May be interesting to take a look at / you probably already seen it. You can pipe files to it via ``ls(1)``, ``find(1)``, etc.

**Comment by wez** [comment]
pywatchman allows you to build and ship python apps that make use of watchman if it is present on your system.  We don't bundle watchman with it because there are more complex configuration options for watchman; there are dependencies on things that are system and distribution specific that make it generally better to use something packaged by your distribution provider or built yourself.

In addition, the watchman model is to run a per-user daemon that aggregates watches in a central place.  If we were to bundle watchman in client packages such as pywatchman or the nodejs client, we run into some potentially hairy versioning and concurrency problems.

**Comment by wez** [comment]
I hear you on the ease of packaging aspect.

I'd love to hear your feedback on the tools themselves; if you install watchman from source on FreeBSD, and configure it with python support that will also install the python bindings and `watchman-wait` + `watchman-make`.

FYI: I'm traveling over the next couple of days and will likely have spotty internet access and a correspondingly slow response.

**Comment by tony** [comment]
I want to give users an easy way to bootstrap + load open source projects into a quasi-IDE with tmux - with a file watcher that can build/test already running in a pane.  I have a python script that helps bootstrap certain things (virtualenv, pip packages).  I'm considering just using docker/vagrant in these cases, but I have a gut sense letting them develop on their own environment helps catch platform-specific bugs you wouldn't otherwise catch (sheerly through allowing diverse variations in their setup).

Asking them to install watchman system package is feasible, however, I can't control the version of watchman their package manager has.

I do see a use case for having npm/gem/pip having watchman built out of the box as a library. You're probably aware of guard, grunt-contrib-watch, sniffer and a lot of libraries that are forced to reinvent the wheel. 

building from npm/gem/pip, just from a packaging standpoint. e.g. getting node-gyp, setuptools to do what autotools is doing would be quite a job to offer to support to across platforms.

That said, it's already impressive how ground area watchman covers with a minimal need for third party libraries.

> In addition, the watchman model is to run a per-user daemon that aggregates watches in a central place.

That would have to get figured out if watchman ever were to materialize in this fashion.

I'm reading through yours and @bhamiltoncx code, nice. It's rare to see lite abstractions these days when everyone else is strapping libuv and libevent2 on everything.
