### ISSUE TITLE
pybser attempts to raise an error it hasn't imported

### ISSUE THREAD

**Issue by DRMacIver** [facebook/watchman#179]
When validating too large integers in [_int_size](https://github.com/facebook/watchman/blob/master/python/pywatchman/pybser.py#L65), pybser attempts to raise RuntimeError. Unfortunately it hasn't imported RuntimeError, so it raises a NameError instead.

**Comment by sid0** [comment]
Oh, I think the `RuntimeException` just needs to be renamed to `RuntimeError`.

**Comment by DRMacIver** [comment]
Oops. I even wrote RuntimeError in my bug report when I meant RuntimeException. Sorry! I think you're right though.

**Comment by wez** [comment]
Thanks, fixed in master!
