### ISSUE TITLE
Off by one error in _int_size

### ISSUE THREAD

**Issue by DRMacIver** [facebook/watchman#180]
I noticed this when I was in the area from #179, but the \_int_size calculations have an off by one error: The smallest representable twos-complement integer in n bytes is -2^(n - 1), but this function treats it as if it were  - 2^(n - 1) - 1 (i.e. the negation of the largest reprsentable number).

This means that some numbers require one more byte to represent than is necessary (not a major deal) but also that it errors erroneously about -2^63.

**Comment by bhamiltoncx** [comment]
Good spot!

**Comment by wez** [comment]
Also found an issue in the native code on Windows; thanks for finding this!
Fixes have been pushed to master
