### ISSUE TITLE
Watchman `4.3.0` missing edits in ReactNative

### ISSUE THREAD

**Issue by pcottle** [facebook/watchman#194]
Hey Wez / Watchman peeps,

Just cross-reporting an issue from RN:
https://github.com/facebook/react-native/issues/4357

Had a bunch of issues with 4.3 making the packager think there were no edits. Downgrading to 4.1 solved a lot of it.

Think I was on 4.3 from the FB build, but switched over to the `brew` build to go down to 4.1

**Comment by wez** [comment]
@pcottle I am on PTO at the moment, but will need more info from you to do anything with this issue when I get back in about a week.  Can you re-instate 4.3 and if/when the issue repeats, please run the watchman-diag tool per our internal troubleshooting wiki page?  Will also need more information on the symptoms; the description is a bit thin.  Thanks!

**Comment by pcottle** [comment]
No worries -- super low pri since I'm unblocked and 4.3 isnt a common version. 

I'll reinstate and respond once I have a paste of `watchman-diag`
