### ISSUE TITLE
[Question] : How do I install one particular version of watchman

### ISSUE THREAD

**Issue by gs-akhan** [facebook/watchman#195]
tried ``` brew install watchman@x.x.x ``` doesn;t work .

Need help. thanks

**Comment by saurabhkukade** [comment]
have you tried installing from source? git checkout x.x.x will solve your problem.

**Comment by chadfurman** [comment]
Yes, if you clone down the full watchman repo, then checkout the tag that you need, you can install a specific version.  For example:
```
git clone https://github.com/facebook/watchman.git
cd watchman
git checkout v3.9.0
```
will put you on a version compatible with the current ember-cli.  Don't forget to restart your watchman server: ` watchman shutdown-server ; watchman`

**Comment by wez** [comment]
Why is 3.9 considered ember compatible and not the most recent release?  Are there issue(s) that should have been filed against watchman?

@stefanpenner?

**Comment by chadfurman** [comment]
No, I'm using an old version of ember beacuse of... uh... lets call it political reasons.  His master branch is good.  We already talked.

**Comment by wez** [comment]
:-/

The git instructions you posted will do the job for the OP, so I'm marking this issue as closed.

FWIW, I don't recommend running such an old version of watchman as we've fixed a number of issues since that version.

**Comment by sid0** [comment]
Yeah, I'd recommend backporting the bugfix in https://github.com/ember-cli/ember-cli/pull/5026 to whatever branch you're running. Watchman does not follow semantic versioning -- outside of bugfixes we don't do breaking changes. See https://facebook.github.io/watchman/docs/compatibility.html.
