### ISSUE TITLE
RFC: TCP Listener

### ISSUE THREAD

**Issue by wez** [facebook/watchman#204]
This issue is to track adding TCP based listener(s) to the watchman service.
Our model has been to use unix domain sockets where available so that we can dodge some authentication issues.

On Windows, we have a mostly-working layer that uses named pipes, but the model for these is rather different from unix domain sockets, due to the limiting APIs available in various clients.  Debugging on Windows is difficult due to lack of nice tools.

The high level idea to make things more pleasant and easier to work with by removing the named pipe stuff and replacing it with TCP sockets on Windows.  This has the nice side effect that we can also enable the same code on Unix systems and have it tested as part of our integration test suite, and it makes it possible to use comfortable system tracing and profiling tools to figure out problems that arise.

The idea is that we can come up with a simple scheme that looks enough like unix domain sockets that there won't be a massive change to the internals.  Here's the game plan:

* The server creates a regular file in place of the unix domain socket in the filesystem
* We'll refer to this file as the `sockfile` below
* The contents of the `sockfile` describe how to connect to the server over TCP
* Clients can stat the sockpath to determine whether it is a file or a socket and react accordingly (but can short cut that step on Windows where it can only be a file and not a socket)

I've really wanted to avoid any serious authentication code because it is notoriously tricky to get it right and to deal with various authentication schemes.  At this time we still only want to enable local connections to the server, but it is conceivable that we may want to enable some advanced remote/relay use cases with watchman in the future.  With that in mind, we'd like to be able to support more than a very basic authentication scheme.

To allow forwards compatibility, the file that was described above will be a JSON object with the following fields:

* `credentials` - describes the authentication credentials to be used.
* `listeners` - is an array listing the available endpoints

An example might look like this:

```json
{
   "credentials": {
      "username": "myname",
      "password": "secret"
   },
   "listeners": [
      "tcp:[::1]:1234",
      "tcp:127.0.0.1:1234"
   ]
}
```

The above shows how we might indicate that the watchman service is running on port 1234 on both IPv4 and IPv6 loopback addresses, and that the client should use the specified credentials when it connects.

## Accommodating authentication in the watchman protocol

When we start up a listener, we can annotate the default state as being implicit (`EXTERNAL` in the SASL terminology) or whether authentication is needed.  When authentication is needed, the client session will only allow a very limited selection of commands to be used; just those related to setting up an authenticated session.  Once authentication is complete, the whole command set is made available.

We should be able to support SASL rather than narrowly focusing on our immediate need.  That means that the authentication process would go something like:

* Client sends a version command requesting authentication capabilities
* If the server supports authentication, the version command will include a list of configured SASL mechanisms
* If the client is configured to use authentication, it selects the most appropriate mechanism and performs authentication via the new `authenticate` command

## The authenticate command

SASL allows for challenge-response authentication, where the client informs the server about the mechanism that it intends to use, and the server sends some kind of challenge string to initiate the credential exchange, then the client responds with the credential data.  For a simple password scheme, this is a bit chatty, so a more terse form can be used where the client just sends the credentials along with the mechanism.  The two examples are shown below:

```
C:> ["authenticate", {"mech": "PLAIN"}]
S:< {"authenticate": false, "challenge":""}
C:> ["authenticate",{"username":"myname", "password":"secret"}]
S:<{"authenticate": true, "identity":"myname"}
```

This is the preferred, less chatty, version:

```
C:> ["authenticate", {"mech": "PLAIN","username":"myname", "password":"secret"}]
S:<{"authenticate": true, "identity":"myname"}
```

I only really want to support this `PLAIN` use case for now, and to do so without *requiring* the use of something relatively heavyweight, such as libsasl, because I'd like to keep the number of dependencies low enough that we stand a chance of being able to build watchman on Windows without much fuss.

## Configuring credentials

I'd like to avoid maintaining the credentials persistently, so the initial thought is that we'd have the default (and only) mode of operation be that the watchman service would compute a randomized set of credentials when it is initialized and write those to the credentials section of the `sockfile`.  The `sockfile` would be readable only to the owner of the watchman process, which gives it similar properties to unix domain socket access control; the filesystem enforces access.

## What do we need to change and where?

* Plan to remove `stream_win.c`
* Add `stream_tcp.c` or adapt `stream_unix.c` to support TCP
* Add the `authenticate` command
* Add an authenticated status field in the server side watchman_client struct and reject unauthenticated commands
* Modify `listener.c` to bring up the TCP listener based on a global flag that defaults to true on Windows
* Initial TCP listener implementation will randomly assign a port (bind to port `0` and let the kernel assign it) and compute the credentials and generate the `sockfile`.  Future iterations can make this more configurable, but that is not necessary to support Windows.
* pywatchman and fb-watchman (nodejs client) will be updated to test whether the sockfile is a socket or file and adapt accordingly
* pywatchman changes will then need to be synced in to the hgwatchman repo (which may well be in the main mercurial repo by the time we're ready for this)

**Comment by indygreg** [comment]
This plan seems more than reasonable to me. I think a randomly generated password stored in a file only readable by the owner of the watchman process makes a lot of sense.

I'm tempted to call YAGNI on having a username (just go with an access token until you actually need a username). The "mech" attribute future proofs you, so you can easily add the username in under a different auth mechanism later.

**Comment by wez** [comment]
I was thinking that both the username and the password could be randomly generated.  The rationale is that I didn't really want to invent an new SASL mech and this seemed the easiest way to deal with it... without spending too much time looking around for alternatives :-)

**Comment by bhamiltoncx** [comment]
Mmm, I need to think over this with a big glass of wine.

If the eventual goal is to provide better hooks for debugging and performance analysis, I feel like what's much more important than the transport is the protocol. Chrome has great debugger and tracing protocols we could adopt:

https://developer.chrome.com/devtools/docs/debugger-protocol
https://www.chromium.org/developers/how-tos/trace-event-profiling-tool

They do use TCP/IP by default, but it appears they also support Unix domain sockets (at least, on Android):

http://peter.sh/experiments/chromium-command-line-switches/

Anyway, just rambling. I don't terribly mind making the transport general, but as you noticed, discovery can be a bugbear. Could we possibly limit the TCP/IP support to the Chrome debugging protocol and require developers who need it to just specify a port at runtime?

**Comment by wez** [comment]
The primary focus is to replace named pipes with something that can be used, tested and debugged without running windows.  I had't thought too much about a general debugging protocol.  Will take a read of those links and cogitate; thanks!

**Comment by bhamiltoncx** [comment]
It seems like introducing an entire authentication protocol might be overkill to avoid named pipes on Windows. They're not that complicated, and you can isolate their implementation pretty easily. :)

That said, I think a debugging / profiling pipeline would be splendid, and I agree TCP/IP makes sense for that.

**Comment by mwpastore** [comment]
Is there potential for this to enable a watchman listener running on a VM guest to receive events from a watchman daemon running on a VM host, for a directory that has been shared from the host to the guest via NFS or some other means?

**Comment by wez** [comment]
https://github.com/facebook/watchman/issues/201 is probably a better solution for the VM scenario

**Comment by wez** [comment]
We can solve the use cases that we have in mind without this, so I'm closing it out.  We can revisit this later if needs change.
