### ISSUE TITLE
NameError exception in pywatchman.capabilityCheck

### ISSUE THREAD

**Issue by mjpieters** [facebook/watchman#210]
From the [current HEAD of `python/pywatchman/__init__.py`](https://github.com/facebook/watchman/blob/master/python/pywatchman/__init__.py#L546-L559):

``` python
    def capabilityCheck(self, optional=None, required=None):
        """ Perform a server capability check """
        res = self.query('version', {
            'optional': optional or [],
            'required': required or []})

        if not self._hasprop(res, 'capabilities'):
            # Server doesn't support capabilities, so we need to
            # synthesize the results based on the version
            capabilities.synthesize(res, opts)
            if 'error' in res:
                raise CommandError(res['error'])

        return res
```

The variable `opts` is undefined anywhere; it isn't a local, a global or imported. Judging by the JavaScript version of the method from the [initial commit that added this code](https://github.com/facebook/watchman/commit/0fdbb1ede899e3f3b85f57141e1262618e583bd8), it should be `optional` instead of `opts`.

**Comment by wez** [comment]
Good eye; thanks!

How does this impact your upstreaming work for hgwatchman?

**Comment by mjpieters** [comment]
The patch I sent upstream contains a copy of pywatchman; I'll just refresh it next time I'm revising the patch. You could make it easier for me by updating the copy in hgwatchman on bitbucket. :-)
