### ISSUE TITLE
watchman pegs a CPU at 100% after returning from sleep on Mac OS X

### ISSUE THREAD

**Issue by ncalexan** [facebook/watchman#212]
Hi folks, this is vague 'cuz I don't understand it.  I  am running a Macbook Pro, Lat 2013, with two different external monitors (but not simultaneously.  That is, one external at home, one at work).  I frequently wake my device to discover a watchman process has pegged a CPU at 100%.  I have to manually kill the process.  I have a single consumer of watchman on my system, namely Mercurial's watchman integration extension (https://bitbucket.org/facebook/hgwatchman).  I'm filing this ticket here because it's the watchman process, and not the hg Python processes -- or not *obviously* the hg Python processes.

I am happy to do deeper investigation into this.  My guess is that some Instruments profiling will help, but any direction appreciated.

**Comment by ncalexan** [comment]
I've filed https://bitbucket.org/facebook/hgwatchman/issues/3/watchman-invoked-via-hgwatchman-pegs-a-cpu to investigate if this is an hgwatchman interaction or an independent watchman issue.

**Comment by wez** [comment]
Can you tell us which version of watchman you are using, and sample the watchman process?  You can do the latter from the Activity Monitor; highlight the watchman process and then use the gear icon to sample it.

Thanks!

**Comment by ncalexan** [comment]
On Mon, Feb 15, 2016 at 11:07 AM, Wez Furlong <notifications@github.com>
wrote:

> Can you tell us which version of watchman you are using, and sample the
> watchman process?
>
nalexander@chocho ~/M/gecko> brew list watchman
/usr/local/Cellar/watchman/3.1/bin/watchman
/usr/local/Cellar/watchman/3.1/share/doc/watchman-3.1.0/README.markdown
/usr/local/Cellar/watchman/3.1/var/run/ (4 files)

> You can do the latter from the Activity Monitor; highlight the watchman
> process and then use the gear icon to sample it.
>
I will do this the next time I witness the behaviour.  Thanks for the
snappy response!

**Comment by wez** [comment]
I'd recommend that you upgrade first:

```
brew update
brew install watchman
```

we have fixed a couple of issues where we might spin a CPU since 3.1; hopefully we got whatever was troubling you.  If it persists on the latest version, the process sample + your watchman log file (easiest way to find that is to `ps -ef | grep watchman` and see the logfile argument) is the best info that you can provide to help us fix it.

**Comment by ncalexan** [comment]
On Mon, Feb 15, 2016 at 1:45 PM, Wez Furlong <notifications@github.com>
wrote:

> I'd recommend that you upgrade first:
>
> brew update
> brew install watchman
>
> we have fixed a couple of issues where we might spin a CPU since 3.1;
> hopefully we got whatever was troubling you.
>
Thanks -- when I saw how old my watchman was, I updated right away.  Best
to close this, I think; I'll re-open if I see it with a modern watchman.
I'll consider filing to have hgwatchman yell if watchman is as dated as I
was.

> If it persists on the latest version, the process sample + your watchman
> log file (easiest way to find that is to ps -ef | grep watchman and see
> the logfile argument) is the best info that you can provide to help us fix
> it.
>
Thanks!

**Comment by wez** [comment]
OK, please re-open if the problem persists!
