### ISSUE TITLE
watchman -j hangs forever

### ISSUE THREAD

**Issue by bobzhang** [facebook/watchman#213]
```sh
jscomp>watchman shutdown-server
{
    "version": "3.1.0",
    "shutdown-server": true
}
jscomp>watchman -j < build.json



```

**Comment by wez** [comment]
What are the contents of build.json?
Does this also happen with the current version of watchman (4.4)? (https://facebook.github.io/watchman/docs/troubleshooting.html#ensure-that-you-are-on-the-best-available-version)
What OS is this running on?
What are the contents of your watchman log file? (https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs)

**Comment by bobzhang** [comment]
so I removed everything in the log file and restart, now it works, I guess maybe multiple watchman is running, and there was a deadlock
