### ISSUE TITLE
[Question]: how to install the 3.7.0-brew specific version?

### ISSUE THREAD

**Issue by toranb** [facebook/watchman#214]
I'm using the latest homebrew and when I `brew install watchman` I get 4.1.0 but I'm curious how to install 3.7.0 w/ that specific tag (using homebrew 0.9.5)

https://github.com/facebook/watchman/releases/tag/v3.7.0-brew

**Comment by wez** [comment]
We generally recommend running on the latest and greatest version (which is current 4.4 and available to you via homebrew if you run `brew update`).

Can I ask why you want to install an older version?

You can manually build and install watchman from a tag if you follow these instructions:
https://facebook.github.io/watchman/docs/install.html#installing-from-source

**Comment by toranb** [comment]
@wez thanks for the prompt reply! Honestly I was debugging some issues I was having w/ an older version of ember-cli today and wanted to see if a pre 4.x version of watchman worked better :)

thanks for the help today!
