### ISSUE TITLE
watchman-wait does't work with xargs

### ISSUE THREAD

**Issue by ptarjan** [facebook/watchman#230]
This works:

```
watchman-wait -m 0 .
# in another window `touch me`
me
```

This doesn't work:

```
watchman-wait -m 0 . | xargs echo
# in another window `touch me`
# nothing is printed
```

```
$ watchman --version
4.4.0
$ sw_vers -productVersion
10.11.3
```

**Comment by wez** [comment]
Wondering if this is a python output buffering issue... can you try:

`PYTHONUNBUFFERED=1 watchman-wait -m 0 . | xargs echo` ?

**Comment by ptarjan** [comment]
@wez sadly that didn't help. As another piece of data, if I use the `unbuffer` script before `watchman` it starts working. So yes, something with pipe buffering.

**Comment by wez** [comment]
:-/

I can't dig in to this right now, but if you're motivated in the meantime, it may that be a one liner to flush just after this line fixes it:

https://github.com/facebook/watchman/blob/master/python/bin/watchman-wait#L168

**Comment by ptarjan** [comment]
Good call, that worked. Thanks @wez. Hope you're doing well.
