### ISSUE TITLE
Completion of error handling

### ISSUE THREAD

**Issue by elfring** [facebook/watchman#234]
Would you like to add more error handling for return values from functions like the following?
- [malloc](http://pubs.opengroup.org/onlinepubs/9699919799/functions/malloc.html "Memory allocation") ⇒ [w_query_expr](https://github.com/facebook/watchman/blob/99dde8ee3f13233be097c036147748b2d7f8bfa7/query/match.c#L60)
- [pthread_mutex_init](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_mutex_init.html "Initialise a mutex.") ⇒ [fsevents_root_init](https://github.com/facebook/watchman/blob/718d41f7e044dbf59609f9edf5cc50e68c42132b/watcher/fsevents.c#L315)

**Comment by wez** [comment]
It's not high priority from our perspective, but we'll definitely review a pull request that improves this.

**Comment by elfring** [comment]
I suggest to avoid [ignorance of return values](https://cwe.mitre.org/data/definitions/252.html "Unchecked return values") a bit more. Would you like to detect every error situation as early as possible?

How do you think about to improve [static source code analysis](https://en.wikipedia.org/wiki/List_of_tools_for_static_code_analysis#C.2C_C.2B.2B "Tools for static code analysis") also for this software?

**Comment by sid0** [comment]
For return values, yes, absolutely -- we'd be happy to review patches that attack the problem, even if incrementally.

I have a bit of an academic background in static analysis, and the main problem with most tools is their bias towards on completeness over soundness -- a lot of static analysis tools will have some signal drowned out against a ton of false positive noise. It's only in the last 5 years that academics have started addressing this problem in earnest with tools like [Infer](http://fbinfer.com/). I don't know how good Infer's support for C is, though.

**Comment by elfring** [comment]
Are you interested to apply [aspect-oriented software development](http://aspectc.org/ "AspectC++")?
How do you think about to encapsulate error detection and corresponding exception handling as [a reusable aspect](https://en.wikipedia.org/wiki/Aspect_%28computer_programming%29 "Combination of a pointcut with advice") in your software?
