### ISSUE TITLE
Protect against spurious wakeups

### ISSUE THREAD

**Issue by elfring** [facebook/watchman#235]
I have seen that [no loop is used around a call](https://github.com/facebook/watchman/blob/718d41f7e044dbf59609f9edf5cc50e68c42132b/watcher/fsevents.c#L375 "Check fsevents_root_start()") of the function "[pthread_cond_wait](http://pubs.opengroup.org/onlinepubs/9699919799/functions/pthread_cond_wait.html "wait on a condition")".
Would you like to reuse anything from my message on the topic "[spurious wakeup](http://groups.google.de/group/comp.programming.threads/msg/bb8299804652fdd7 "Discussion about handling of spurious wakeups")"?

**Comment by wez** [comment]
It's not high priority from our perspective, but we'll definitely review a pull request that improves this.
