### ISSUE TITLE
Watchman seems unusable on OS X

### ISSUE THREAD

**Issue by wmertens** [facebook/watchman#236]
Creating a new issue becaus the existing ones don't seem to fit the bill entirely.

I installed nuclide on Atom 1.6 on OS X 10.11.4, and installed watchman 4.5.0 (via [Nix](http://nixos.org/nix/), [binaries](http://hydra.nixos.org/build/32398307) - [build log](http://hydra.nixos.org/build/33715218/log)). 

I have a few React projects with a fair amount of files in them (190780 in total across the dirs in the watchman watch list), and when I just use Atom like I did before installing Nuclide, my system starts to misbehave because the kernel file tables are full (necessitating restart).

I had to set `kern.maxfiles` to 30000 via sysctl just to be able to use the system normally, and even then watchman skips huge sets of my files with `[io <project dir>] opendir(<project subdir>/) -> Too many open files. Marking this portion of the tree deleted`. Instant search in Atom doesn't find all files.

So it seems to me that watchman is not doing the right thing when monitoring files on OS X, given that Atom without Nuclide works fine…

**Comment by wez** [comment]
How many files does watchman have open when you experience this condition?
This command will show you what it has open:

```
lsof -p `pgrep watchman`
```

it is typically a small set of around a dozen items per watched root, but may be slightly larger while it is crawling a tree.
These handles are short lived; even crawling a massive tree, I don't see more than 30 descriptors open in watchman.

Could you share the output from the above command with me?
Also the output from `watchman watch-list`.

If the list is short (as it should be), you can use `lsof` to look at all of the processes on your system and figure out where the descriptors are being used.

**Comment by wmertens** [comment]
```
$ lsof -p `pgrep watchman` | wc -l
   15009
```
:confused: 

When I look at the [Homebrew build](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/watchman.rb) versus the [Nixpkgs build](https://github.com/Homebrew/homebrew/blob/master/Library/Formula/watchman.rb) the only difference seems to be the build flag `--disable-dependency-tracking`.

Hmmm. The log says `Using watcher mechanism kqueue`, and the docs seem to indicate that the FSEvents queue should be used. I suppose there is a problem with the build on Nixpkgs, which tries to make it as pure as possible. @wez If you have any pointers to troubleshoot, that'd be great.

**Comment by wmertens** [comment]
Okay, it is definitely due to the Nixpkgs build not providing CoreServices at build time. Trying to fix that at https://github.com/NixOS/nixpkgs/issues/14309

Closing since everything works as designed…

**Comment by wez** [comment]
Ah, yeah, kqueue needs 1 descriptor per watched item, and it is unusual to see that when building on darwin.  Thanks for driving the follow up with the NixOS folks!
