### ISSUE TITLE
wrong-case unlink missed on OS X

### ISSUE THREAD

**Issue by dturner-tw** [facebook/watchman#237]
If I have a file named foo, but I unlink "FOO", watchman won't report any changes.

Note that "rm" won't trigger this, presumably because it looks up the correct case before issuing the unlink call.  But you can use os.unlink() from Python.

Please let me know if you need any more data.

Thanks.

**Comment by wez** [comment]
Is this with a current watchman release?

**Comment by dturner-tw** [comment]
4.3.0.

**Comment by swollenmember** [comment]
Your fired not

**Comment by wez** [comment]
We haven't seen this happen, and it's been almost a year, and we did some work on canonical path resolution in the intervening time, so let's just close this out.
