### ISSUE TITLE
Can't run on osx

### ISSUE THREAD

**Issue by bbnnt** [facebook/watchman#238]
Keep hitting this one, reinstalled everything from homebrew, reinstalled node, npm, installed watchman head… :

```
/Volumes/Untitled/Users/administrateur/Library/LaunchAgents/com.github.facebook.watchman.plist: Could not find specified service
/Volumes/Untitled/Users/administrateur/Library/LaunchAgents/com.github.facebook.watchman.plist: Path had bad ownership/permissions
```
Here's the plist file, in case it could add infos (https://gist.github.com/bbnnt/fe80632839b972456272068ae75efbb6)

watchman 4.5.0, yosemite with osx version 10.10.5
Ended up running it in the frontend with `watchman --foreground`, which works pretty well

**Comment by wez** [comment]
is `administrateur` your regular user account or is it the localized administrator account for your system?
Are you running `sudo watchman`?  If so, you should not do that as watchman is intended to run as you.
Was this system re-imaged or restored from a backup?

**Comment by wez** [comment]
I will close this issue next week if there is no feedback from you. If you're no longer having problems with this, please don't hesitate to close the issue for yourself.
