### ISSUE TITLE
ERROR unable to resolve root 

### ISSUE THREAD

**Issue by alexandref93** [facebook/watchman#240]
I worked for a few days and everything worked normal, until today, ran the command react-native run-android and the error happened, as if he did not find the project ... I updated the watchman, but the error persists...

![](https://cloud.githubusercontent.com/assets/890738/14300886/cdfe9c72-fb69-11e5-8ca6-2917c1d658f9.png)

I opened issue in the react-native, but reported to me that this would be a Watchman issue....  :(

**Comment by wez** [comment]
Possibly a case sensitivity issue?  Does https://stackoverflow.com/questions/35715904/react-native-watchmanresponse-unable-to-resolve-root sound similar, and does the resolution also solve your issue?

**Comment by AgtLucas** [comment]
@alexandref93 

Which version of `Node.js` are you using?

Maybe updating `React Native` to the latest one... 🤔

**Comment by alexandref93** [comment]
in fact, it was just rename the folder to downcase... resolved
