### ISSUE TITLE
error in ubuntu 14.04

### ISSUE THREAD

**Issue by nuan-nuan** [facebook/watchman#241]
I install watchman into ubuntu 14.04，the watchman branch is v4.1.0,  but  is have a error and the following is the same，i try other branch is same error.

this is my error messages

➜ /home/code/github/watchman git:(8bb8f8f) >sudo make install
cd python && /usr/bin/python ./setup.py clean build_py -c -d . build_ext -i
running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
removing 'build'
running build_py
running build_ext
building 'pywatchman.bser' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pywatchman
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/usr/include/python2.7 -c pywatchman/bser.c -o build/temp.linux-x86_64-2.7/pywatchman/bser.o
pywatchman/bser.c:31:20: fatal error: Python.h: No such file or directory
 #include <Python.h>
                    ^
compilation terminated.
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
make: *** [py-build] Error 1

**Comment by sid0** [comment]
http://facebook.github.io/watchman/docs/install.html#installing-from-source

> For python support, you will also need setuptools and may need to install a python-dev or python-devel package.

**Comment by nuan-nuan** [comment]
@sid0 
thank you

**Comment by AsaAyers** [comment]
> You may optionally build watchman with pcre and python support.

I found this issue because I thought I would have to opt into python support. Since it's optional and I don't develop for python I was going to skip it.
