### ISSUE TITLE
Multiple watchman processes taking IO 100%

### ISSUE THREAD

**Issue by v3ss0n** [facebook/watchman#244]
Hi , 

When creating a project with ember-cli 
`ember new projname`
or 
running atom.io project hitting 100% I/O at watchman.
Happening everytime. How can i debug?

**Comment by wez** [comment]
Did you run through https://facebook.github.io/watchman/docs/troubleshooting.html first?

Can you provide some more information about your system?
The output from the following commands will help give better advice:

```
uname -a
watchman watch-list
watchman version
```

It would be great to see your watchman logs too; can you share them in a gist?
https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

**Comment by wez** [comment]
Closing out due to lack of information

**Comment by v3ss0n** [comment]
the problem is fixed after removing watch list entries with node_modules.

**Comment by v3ss0n** [comment]
This is still recurring . Watchman is taking 100% io , observed in Atom-Nuclide and emberjs (whatever packages that watchman uses)

**Comment by v3ss0n** [comment]
```
v3ss@hexcode ~ $ watchman watch-del-all
{
    "version": "3.5.0",
    "roots": [
        "/home/v3ss/workspace/ondr.co/chat.ondr.co/client/node_modules/ember-cli-moment-shim",
        "/home/v3ss/workspace/ondr.co/chat.ondr.co/client"
    ]

```

**Comment by morhook** [comment]
I think that `ember` using 'a lot' of files on it's process. I've bumped the kernel parameters several times so-far. Is this something we should report on `ember` project or on this repo?

**Comment by wez** [comment]
Please upgrade to the latest version of watchman; `4.7.0` is current.
