### ISSUE TITLE
Installation failure on MAC

### ISSUE THREAD

**Issue by wangbourne** [facebook/watchman#249]
I'm using el captitan. when trying to install watchman, i got following erros:

==> Downloading https://github.com/facebook/watchman/archive/v3.3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/watchman-3.3.0.tar.gz
==> ./autogen.sh
      See the Autoconf documentation.
configure.ac:27: error: possibly undefined macro: AM_PROG_CC_C_O
configure.ac:28: error: possibly undefined macro: AM_PROG_AS
configure.ac:34: error: possibly undefined macro: AM_CONDITIONAL
configure.ac:75: error: possibly undefined macro: AM_PATH_PYTHON

READ THIS: https://git.io/brew-troubleshooting

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:369:in `open'
	from /usr/local/Library/Homebrew/utils.rb:399:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:431:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:176:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:172:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:215:in `dump'
	from /usr/local/Library/brew.rb:151:in `rescue in <main>'
	from /usr/local/Library/brew.rb:65:in `<main>'

**Comment by yashshah** [comment]
I'm also facing the same problem. @wangbourne were you able to solve it?

**Comment by wez** [comment]
```
$ brew update
$ brew install watchman
```
