### ISSUE TITLE
watchman error on deleted vcs dir

### ISSUE THREAD

**Issue by dturner-tw** [facebook/watchman#25]
If you watch a directory that contains a vcs directory, and then later delete that directory, watchman does not detect this, so it continues to attempt to use that directory for cookies, and thus nothing works.

(This is probably an edge case, but it is worth reporting)

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wez** [comment]
Proposed approach to tackle this is check for ENOTDIR when creating a cookie file fails, then re-compute the cookie dir location

**Comment by wez** [comment]
Finally fixed this(!)

**Comment by bitriddler** [comment]
Running this command `watchman watch-del /path/to/dir` fixed the issue for me
