### ISSUE TITLE
aclocal not found

### ISSUE THREAD

**Issue by ericntd** [facebook/watchman#254]
I followed the instructions on React Native getting started page and here's what I got:
```
➜  watchman git:(e656697) ./autogen.sh 
./autogen.sh: 9: ./autogen.sh: aclocal: not found
./autogen.sh: 10: ./autogen.sh: autoheader: not found
./autogen.sh: 11: ./autogen.sh: automake: not found
./autogen.sh: 12: ./autogen.sh: autoconf: not found
```
I'm using Linux Mint 17.3 64 bit.
Here are the instructions from React Native website:

> git clone https://github.com/facebook/watchman.git
> cd watchman
> git checkout v4.5.0  # the latest stable release
> ./autogen.sh
> ./configure
> make
> sudo make install

**Comment by wez** [comment]
You need to install some other dependencies first.  Please see https://facebook.github.io/watchman/docs/install.html#installing-from-source
