### ISSUE TITLE
Support for multiple patterns in matchman-make

### ISSUE THREAD

**Issue by aexmachina** [facebook/watchman#268]
It would be great to provide multiple `--pattern` arguments to matchman-make in order to watch multiple directories. Is there any other way to achieve this?

**Comment by wez** [comment]
It does this already, just list out multiple patterns after the `-p`.  I agree that it feels like you should be able to use `-p` multiple times, but this is how the argparse argument parser works in python.

```
watchman-make -h
...
  -p PATTERN [PATTERN ...], --pattern PATTERN [PATTERN ...]
                        Define filename matching patterns that will be used to
                        trigger the next --target definition. The pattern
                        syntax is wildmatch style; globbing with recursive
                        matching via '**'. --pattern is reset to empty after
                        each --target argument.
```

**Comment by aexmachina** [comment]
Great, thanks for that.
