### ISSUE TITLE
INSTALL requirements, man page

### ISSUE THREAD

**Issue by sspreitzer** [facebook/watchman#30]
Hi there

I am thinking about to package watchman for Debian and what I came across are two questions;
- What are the exact dependencies? aka INSTALL file with build requirements and instructions
- Can you create a man page?

Kind regards
Sascha

**Comment by Polve** [comment]
I'm interested in knowing that too

**Comment by shirishag75** [comment]
same here.

**Comment by Envek** [comment]
FYI, I'm successfully packaged watchman with [fpm](https://github.com/jordansissel/fpm):
```
gem install fpm
git clone https://github.com/facebook/watchman.git
cd watchman
git checkout v4.1.0
sudo apt-get install python-dev
./autogen.sh
./configure --prefix=/usr
make
mkdir dist
make install DESTDIR=./dist
fpm -s dir -t deb -n watchman -C ./dist -v 4.1.0 .

**Comment by Daniel15** [comment]
Thanks @Envek! fpm does look pretty useful, and your steps worked perfectly for me (except I swapped `4.1.0` for `4.5.0`, the latest version right now). fpm reminds me of [checkinstall](http://www.asic-linux.com.mx/~izto/checkinstall/) except more flexible.
