### ISSUE TITLE
C/C++ client support

### ISSUE THREAD

**Issue by dayvsonlima** [facebook/watchman#300]

**Comment by sid0** [comment]
Watchman is not designed to be used as a library -- the only stable interfaces are the CLI and socket interfaces. Could you tell us a bit more about your use case?

**Comment by dayvsonlima** [comment]
I would like to compile specific modules in an application in C when one of its directory file is changed on a web framework

**Comment by sid0** [comment]
In that case please use the socket interface. We do not provide API or ABI compatibility for the actual binary or any libraries we ship.

We have wrappers over the interfaces for several languages (Python, Node.JS, soon C++), but not one in C at the moment.

**Comment by dayvsonlima** [comment]
OK, thank you!

**Comment by wez** [comment]
It's a reasonable request for a way to access watchman from compiled code.  We have a C++ client in the works, but no plans for supporting a C client ourselves today.

If you can share a bit more about your use case we may be able to give you some good advice in the meantime.

**Comment by wez** [comment]
https://github.com/facebook/watchman/commit/37822086f20f40e14d2c8777af489c23e00bff41
is the commit where our C++ client landed.
