### ISSUE TITLE
Add way to subscribe to file open events

### ISSUE THREAD

**Issue by marcusmotill** [facebook/watchman#312]
To my knowledge the subscribe event is only fired when a file is modified.  It would be helpful for me to have a way to get an event when a file is opened or the `atime` changes.  Thanks.  If this already exists I would appreciate any information.

**Comment by wez** [comment]
Sorry, but this is incompatible with the way that watchman works and is unlikely to be something that we will ever add.

The TL;DR as to why is that our purpose is to inform about observable changes to files.  File open events are not in this category of event and are not something that we can portably or reliably inform a client about.

There's some more background here in this answer to a question asking for more granularity of information about why something was marked as changed: http://stackoverflow.com/a/35753594/149111

**Comment by marcusmotill** [comment]
Thanks Wez
