### ISSUE TITLE
Support watching new directories in watchman-make

### ISSUE THREAD

**Issue by ipmb** [facebook/watchman#319]
I'd like to use `watchman-make` to watch for any changes to a directory recursively. This pattern is close:

`--pattern dir dir/**`

I would like the following command to trigger a build, but it does not:

`mkdir dir/new_dir; touch dir/new_dir/test.txt`

**Comment by wez** [comment]
You need to quote the pattern otherwise your shell interprets it.

Note the difference between these two cases:

```
$ watchman-make --pattern bin/* -t foo
# Relative to /data/users/wez/arcanist
# Changes to files matching bin/arc bin/arc.bat will execute `make foo`
# waiting for changes
```

```
$ watchman-make --pattern 'bin/*' -t foo
# Relative to /data/users/wez/arcanist
# Changes to files matching bin/* will execute `make foo`
# waiting for changes
```

In your case:

```
--pattern 'dir/**'
```

**Comment by ipmb** [comment]
Doh! Thank you, that works as expected :)
