### ISSUE TITLE
Having lots of trouble getting watchman to work

### ISSUE THREAD

**Issue by boxxxie** [facebook/watchman#32]
i'm trying to use watchman in a make file so i can issue `make watch` and have it lint my code.

```
JSHINT=./node_modules/jshint/bin/jshint
JSHINTFLAGS=

js_files=$(shell find src -name '*.js')
jshint: $(js_files)
    $(JSHINT) $(JSHINTFLAGS) $?
# .PHONY just tells make that these rules don't produce files. So if there is a
# file called "jshint", it won't interpret that file as the output of the
# jshint recipe.
.PHONY: jshint

watch:
    watchman watch $(shell pwd)/src
    watchman -- trigger $(shell pwd)/src remake '*.js' -- make jshint
```

when i do this i get triggers for the right dir, however i don't see any output on the console.

we also looked at the watchman log output to see if the files were changing, and they are. 
`watchman --persistent --server-encoding=json log-level debug`
log at https://gist.github.com/nurey/9916489

also, when i run `watchman find $(pwd)/src '*.js'` i get the file back that i want to be watched.

```
watchman find $(pwd)/src '*.js'
{
    "version": "2.9.5",
    "clock": "c:1396363466:31774:1:46",
    "files": [
        {
            "dev": 2050,
            "gid": 1000,
            "name": "imageupload.js",
            "exists": true,
            "size": 14890,
            "mode": 33188,
            "uid": 1000,
            "mtime": 1396364671,
            "ctime": 1396364671,
            "ino": 2498402,
            "nlink": 1,
            "oclock": "c:1396363466:31774:1:33",
            "new": true,
            "cclock": "c:1396363466:31774:1:1"
        }
    ]
}
```

really sorry to be posting an issue like this, but i could really use some working examples. the example on your readme that uses `ls -l` doesn't work for my either.

**Comment by sertaconay** [comment]
Hello.
Even this doesn't work in make file. Why? But watchman-make works well.
```
watchman -- trigger ~/www jsfiles '*.js' -- ls -l
