### ISSUE TITLE
watchman writes incorrect path to com.github.facebook.watchman.plist file when installing via brew

### ISSUE THREAD

**Issue by kageiit** [facebook/watchman#357]
When installing watchman via brew with

`brew install watchman --HEAD`, it writes

`<string>/usr/local/Cellar/watchman/HEAD/libexec/bin/watchman</string>` to the `com.github.facebook.watchman.plist` file

while in fact, the real location is something like

`<string>/usr/local/Cellar/watchman/HEAD-39b814a/libexec/bin/watchman</string>`

This leads to watchman hanging indefinitely on OSX with an error like

`launchd checkin failed: No such process` in the watchman logs

**Comment by wez** [comment]
The plist is generated using the path returned from `_NSGetExecutablePath` and is generated by watchman itself when it decides that it needs to spawn the server process.  `brew install` doesn't do anything with the plist.

I'm not sure how things got in a bad state for you, but these steps might help get things in the right state:

1. `launchctl unload path/to/com.github.facebook.watchman.plist`
2. remove the plist file
3. `watchman version`

Can you try that and let us know how things go?

**Comment by kageiit** [comment]
What i did instead was uninstall the head version and installed 4.6.0.

Then i updated the plist to the correct patch and rebooted.

That seemed to have fixed it.

**Comment by wez** [comment]
OK, I'll close this out as I think it is a one-off.  If it comes back, please re-open this and we can figure out what the trigger was!

**Comment by mekf** [comment]
I think I ran into the same issue. I upgraded watchman and running `npm start` in a react-native project hangs indefinitely. I ran `watchman version` and it hangs too.

It seems to be fixed with running launchtl unload, remote the plist, and then reinstall watchman

**Comment by wez** [comment]
Tracking the follow up for this in #358
