### ISSUE TITLE
Examples?

### ISSUE THREAD

**Issue by williamcotton** [facebook/watchman#36]
I've been googling around for some examples on how to use this, but I can't find anything...

Don't get me wrong, the documentation seems extensive, I just wish it had a for examples.

Any blog posts that someone can point me to? 

Better yet, wanna show me a complete example that say, watches a `jsx/` folder and compiles the React components while also watching a `sass/` folder and compiling to a css file?

**Comment by michaelprescott** [comment]
Landed here looking for the same thing.  Documentation is good, and a variety of usage examples would be very helpful.

**Comment by janosh** [comment]
Looks like the examples situation still hasn't improved. I'm trying to figure out how to access the names of files that triggered a command in said command. Seems simple enough.
