### ISSUE TITLE
Watchman hangs silently when the state directory is corrupted

### ISSUE THREAD

**Issue by sandlerr** [facebook/watchman#369]
Hi maintainers,
Thanks for producing this extremely useful tool! I'm using it for an Ember.JS project with very many files on OSX 10.11.6. Recently my `$USER-state` directory must have gone into a bad state, causing many watchman commands to hang on v4.7.0 and v4.6.0, although `watchman version` worked only on v4.6.0.

I didn't save the corrupt data but if anyone is interested in at least making this fail loudly I have `gdb` output:

```
Thread 1 (Thread 0x1803 of process 69116):
#0  0x00007fff882eb362 in read () from /usr/lib/system/libsystem_kernel.dylib
#1  0x00000001034318df in fill_buffer (jr=0x7fff5c7d01a0, stm=0x7fac7b401f50) at json.c:70
#2  0x0000000103431e63 in read_and_detect_pdu (jr=0x100000, stm=0x7fff5c7d01a0, jerr=0x7fac7b401f50) at json.c:247
#3  0x000000010343194b in w_json_buffer_passthru (jr=0x7fac7b401f50, output_pdu=is_json_pretty, output_pdu_buf=0x7fff5c7d01a0, stm=0x100000) at json.c:406
#4  0x0000000103443f94 in try_command (cmd=<optimized out>, timeout=<optimized out>) at main.c:862
#5  0x0000000103443234 in main (argc=<optimized out>, argv=<optimized out>) at main.c:1043
```

and `strace` output: https://gist.github.com/sandlerr/6074dbee1663524593e553e39088430d

**Comment by paramaggarwal** [comment]
Try this: https://github.com/ember-cli/ember-cli/issues/6275#issuecomment-248399996

**Comment by sandlerr** [comment]
Thanks @paramaggarwal I should have mentioned that this did indeed solve the problem.

**Comment by sandlerr** [comment]
I suppose this is another instance of https://github.com/ember-cli/ember-cli/issues/6259 and https://github.com/facebook/watchman/issues/358 etc.

**Comment by wez** [comment]
Most likely the same issue as #358, which is something we can't easily detect since launchd is the thing that didn't behave as requested.

Closing this in favor of #358
