### ISSUE TITLE
Error: No available formula with the name "watchman"

### ISSUE THREAD

**Issue by Arkanine** [facebook/watchman#372]
Hello,
When I try to install watchman by brew install watchman I receive:

Every time I try to install something, I receive:
Error: No available formula with the name "wget" 
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
Error: No formulae found in taps.

Please help me to figure out what is a cause of this err?

**Comment by wez** [comment]
Sounds like you need to update homebrew (try; `brew update`).  This is not a watchman issue; please follow up with the homebrew folks.

**Comment by PrasathRavichandran** [comment]
Please enter this in the terminal

`brew doctor`

and then this

`git -C $(brew --repo homebrew/core) checkout master`

Then, install the watchman package using the cmd,

`brew update`
`brew install watchman`

It will work fine 👍
