### ISSUE TITLE
fsmonitor mercurial extension not responding

### ISSUE THREAD

**Issue by shubham2892** [facebook/watchman#374]
I was trying to clone the mozilla repository and mercurial was configured to use the [fsmonitor](https://www.mercurial-scm.org/wiki/FsMonitorExtension) extension. Cloning freezes at "updating to branch default". On removing the extension from .hgrc file it works fine. I am using watchman 4.7.0 on Mac OS 10.12.1 Beta (16B2548a).

**Comment by wez** [comment]
There's not a lot of info to go on here, and like any good problem, there are several layers of complexity to untangle.

Let's look at the basic watchman configuration first of all.

Below, `$REPO` is the path to the root of your mozilla repository clone (the directory that contains the `.hg` directory).

Please run the following commands and share the output:

1. `time watchman watch-project $REPO`
2. `watchman watch-list`
3. `time watchman find $REPO .hg`

Please collect your watchman log file into a gist or pastebin and share it with me.  https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs has information on how to locate your log files.

Re-enable the fsmonitor extension and run:

* `time hg status --profile`

If it takes longer than a handful of seconds to run, please collect a sample of both the watchman server process and the python process that is behind your `hg` command.  You can do this by opening Activity Monitor, selecting the `watchman` process in the list and clicking on the gear icon in the toolbar and choosing "Sample Process".  Repeat this for the python process for hg.

Please share the samples in a gist/pastebin.

**Comment by shubham2892** [comment]
Hi Wez,
On executing any watchman command, I don't get any response as in terminal freezes including the commands you mentioned above. Same is the case when I run `time hg status --profile` with fsmonintor enabled.

Sharing the [sample process](https://gist.github.com/shubham2892/8d2968a341dd4a08f2e1e5a556bb4d87) for `time hg status --profile` with fsmonitor enabled. Please do let me know what else you need.

**Comment by wez** [comment]
I wonder if you're hitting this upgrade issue: https://github.com/facebook/watchman/issues/358

**Comment by shubham2892** [comment]
That worked very well. Thanks for the help.
