### ISSUE TITLE
strlen may slow

### ISSUE THREAD

**Issue by kaitian521** [facebook/watchman#382]
in log.cpp

```
if (len2 == -1) {
    // Truncated.  Ensure that we have a NUL terminator
    buf[sizeof(buf)-1] = 0;
  }

  len = (int)strlen(buf);
```

maybe below is better

```
  if (len2 == -1) {
    // Truncated.  Ensure that we have a NUL terminator
    buf[sizeof(buf)-1] = 0;
    perror("vsnprintf error: ");
  } else{
    //  assume that len is less than sizeof(buf) - 1
    len += len2;
  }
```
am I wrong?

**Comment by sid0** [comment]
Possibly, but

1. `strlen` is highly optimized on modern architectures.
2. All else being equal, it's clearer than the alternatives.

So if you can demonstrate a measurable impact your case becomes more solid.

**Comment by wez** [comment]
I have some pending changes to log.cpp that render this moot
