### ISSUE TITLE
Watch takes too long to load and after some time connection is lost 

### ISSUE THREAD

**Issue by abhitheawesomecoder** [facebook/watchman#383]
Watch takes too long to load and after some time connection is lost on ubuntu 16.04. Also, how can I uninstall watchman ?
![watchman](https://cloud.githubusercontent.com/assets/3944526/19891324/95481b00-a065-11e6-86a4-b92a99898389.png)

**Comment by wez** [comment]
Haave you run through the troubleshooting guide?
https://facebook.github.io/watchman/docs/troubleshooting.html

If so, please share your logs.

**Comment by abhitheawesomecoder** [comment]
Yes I have spend 2 days troubleshooting everything i found on web related to watchman troubleshooting. Here I am attaching the log
[log.txt](https://github.com/facebook/watchman/files/565685/log.txt)

**Comment by wez** [comment]
From the logs, the problem (and a link to resolve it) was:

```
2016-11-02T10:00:37,250: [io /home/USER/react-native/Element] A non-recoverable condition has triggered.  Watchman needs your help!
The triggering condition was at timestamp=1478060334: inotify-add-watch(/home/USER/react-native/Element/node_modules/babel-preset-react-native/node_modules/babel-plugin-transform-es2015-modules-commonjs/node_modules/babel-runtime/node_modules/core-js/fn/function/virtual) -> The user limit on the total number of inotify watches was reached; increase the fs.inotify.max_user_watches sysctl
All requests will continue to fail with this message until you resolve
the underlying problem.  You will find more information on fixing this at
https://facebook.github.io/watchman/docs/troubleshooting.html#poison-inotify-add-watch
```
