### ISSUE TITLE
Watchman package manager fails to watch repository updates in react-native simulators

### ISSUE THREAD

**Issue by emmajam** [facebook/watchman#384]
###  Description 
react-native run-ios, successfully builds app and starts it on the iOS simulator.
react-native run-android on android av emulator successfully starts the app on the emulator.

However as I make changes to my code they do not appear on either simulator. When I reload with cmd+R the changes are still not shown.

If I exit out of the simulator and start it back up again, the changes are shown.

### Reproduction

react-native run-android || react-native run-ios ... make live changes to code, see no change.

package manager seems to be failing to watch and update changes

### Versions

* watchman version: 4.7.0
* React Native version: 0.36.0
* React Native Cli Version: 1.0.0
* Operating System: MacOS Sierra 10.12.1

**Comment by wez** [comment]
Did you run through the troubleshooting guide?
Best place to start is looking at the logs:

https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

Please share your logs; there's not enough information here to get a sense of what is going wrong for you without them.
