### ISSUE TITLE
om.github.facebook.watchman.plist for write: Not a directory

### ISSUE THREAD

**Issue by BitsOnCoffee** [facebook/watchman#386]
Hi,

I'm getting this:

    ERROR  watchman--no-pretty get-sockname returned with exit code null 2016-11-10T00:24:43,261: [cli] Failed to open /Users/myuser/Library/LaunchAgents/com.github.facebook.watchman.plist for write: Not a directory

Seems like the file is missing. I tried to reinstall several times, didn't help.

Thanks

**Comment by BitsOnCoffee** [comment]
Ok, so the problem was I had a file ~/Library/LaunchAgents pointing to homebrew.mxcl.postgresql instead of the folder.
So I just moved homebrew.mxcl.postgresql to a temp folder, deleted ~/Library/LaunchAgents, created a ~/Library/LaunchAgents folder and copied homebrew.mxcl.postgresql into it.

com.github.facebook.watchman.plist was created for the first time I ran watchman.

**Comment by anil826** [comment]
same issue any help !

**Comment by arronmabrey** [comment]
Same issue. Seems like maybe an issue with homebrew or the postgres formula
