### ISSUE TITLE
Watchman cli not responding

### ISSUE THREAD

**Issue by heldertb** [facebook/watchman#388]
Running on macOS Sierra, wanting to start up my react-native project and noticed that nothing was happening. I narrowed it down to the watchman process not doing anything.
I tried removing and reinstalling it (`brew remove watchman && brew install watchman`) but the outcome was the same.
running `watchman watch-del-all` doesn't do anything either
I just saw that the build is also failing. any connection?

**Comment by heldertb** [comment]
Updated macOS and it started working again, weird

**Comment by brunolemos** [comment]
For anyone coming to this issue, here is the fix: https://github.com/facebook/watchman/issues/358#issuecomment-247105934
