### ISSUE TITLE
Compiling on solaris11.3 gives an error

### ISSUE THREAD

**Issue by njhnb** [facebook/watchman#389]
Hi,

Here's the output from the make

nico@devnull:/sources/watchman$ make
\make  all-am
make[1]: Entering directory `/sources/watchman'
  CC       thirdparty/libart/src/art.o
"thirdparty/libart/src/art.c", line 418: warning: statement not reached
"thirdparty/libart/src/art.c", line 458: warning: statement not reached
  AR       libart.a
  CC       thirdparty/libtap_a-tap.o
  AR       libtap.a
  CC       thirdparty/wildmatch/wildmatch.o
  AR       libwildmatch.a
  CC       thirdparty/jansson/libwmanjson_a-dump.o
  CC       thirdparty/jansson/libwmanjson_a-error.o
  CC       thirdparty/jansson/libwmanjson_a-hashtable.o
  CC       thirdparty/jansson/libwmanjson_a-load.o
  CC       thirdparty/jansson/libwmanjson_a-memory.o
  CC       thirdparty/jansson/libwmanjson_a-pack_unpack.o
  CC       thirdparty/jansson/libwmanjson_a-strbuffer.o
  CC       thirdparty/jansson/libwmanjson_a-strconv.o
  CC       thirdparty/jansson/libwmanjson_a-utf.o
  CC       thirdparty/jansson/libwmanjson_a-value.o
  AR       libwmanjson.a
  CC       watchman-argv.o
  CC       watchman-envp.o
  CC       watchman-spawn.o
  CC       watchman-opt.o
  CC       watchman-cfg.o
  CC       watchman-clockspec.o
  CC       watchman-checksock.o
  CC       watchman-fstype.o
  CC       watchman-log.o
"log.c", line 78: warning: implicit function declaration: dprintf
"log.c", line 124: warning: syntax error:  empty declaration
  CC       watchman-ignore.o
  CC       watchman-json.o
  CC       watchman-bser.o
"bser.c", line 692: warning: statement not reached
  CC       watchman-expflags.o
  CC       watchman-hash.o
  CC       watchman-ht.o
  CC       watchman-ioprio.o
  CC       watchman-opendir.o
  CC       watchman-pending.o
  CC       watchman-perf.o
"perf.c", line 233: warning: statement not reached
  CC       watchman-stream.o
  CC       watchman-stream_stdout.o
  CC       watchman-stream_unix.o
  CC       watchman-timedlock.o
  CC       cmds/watchman-find.o
  CC       cmds/watchman-info.o
  CC       cmds/watchman-log.o
  CC       cmds/watchman-query.o
  CC       cmds/watchman-since.o
  CC       cmds/watchman-reg.o
  CC       cmds/watchman-state.o
  CC       cmds/watchman-subscribe.o
  CC       cmds/watchman-trigger.o
  CC       cmds/watchman-watch.o
  CC       cmds/watchman-debug.o
"cmds/debug.c", line 135: warning: syntax error:  empty declaration
  CC       query/watchman-base.o
  CC       query/watchman-dirname.o
  CC       query/watchman-parse.o
"query/parse.c", line 26: warning: argument #1 is incompatible with prototype:
	prototype: pointer to const void : "watchman_hash.h", line 20
	argument : pointer to function(pointer to struct w_query {long refcnt, _Bool case_sensitive, _Bool empty_on_fresh_instance, _Bool dedup_results, pointer to struct watchman_string {..} relative_root, pointer to struct watchman_string {..} relative_root_slash, pointer to struct w_query_path {..} paths, unsigned long npaths, pointer to struct watchman_glob_tree {..} glob_tree, int glob_flags, pointer to pointer to struct watchman_string {..} suffixes, unsigned long nsuffixes, unsigned int sync_timeout, unsigned int lock_timeout, pointer to struct w_clockspec {..} since_spec, pointer to struct w_query_expr {..} expr, pointer to char errmsg, pointer to struct  {..} query_spec}, pointer to struct  {enum  {JSON_NULL(7), JSON_FALSE(6), JSON_TRUE(5), JSON_REAL(4), JSON_INTEGER(3), JSON_STRING(2), JSON_ARRAY(1), JSON_OBJECT(0)} type, unsigned long refcount}) returning pointer to struct w_query_expr {long refcnt, pointer to function(pointer to struct w_query_ctx {..}, pointer to struct watchman_file {..}, pointer to void) returning _Bool evaluate, pointer to function(pointer to void) returning void dispose, pointer to void data}
"query/parse.c", line 54: warning: assignment type mismatch:
	pointer to function(pointer to struct w_query {long refcnt, _Bool case_sensitive, _Bool empty_on_fresh_instance, _Bool dedup_results, pointer to struct watchman_string {..} relative_root, pointer to struct watchman_string {..} relative_root_slash, pointer to struct w_query_path {..} paths, unsigned long npaths, pointer to struct watchman_glob_tree {..} glob_tree, int glob_flags, pointer to pointer to struct watchman_string {..} suffixes, unsigned long nsuffixes, unsigned int sync_timeout, unsigned int lock_timeout, pointer to struct w_clockspec {..} since_spec, pointer to struct w_query_expr {..} expr, pointer to char errmsg, pointer to struct  {..} query_spec}, pointer to struct  {enum  {JSON_NULL(7), JSON_FALSE(6), JSON_TRUE(5), JSON_REAL(4), JSON_INTEGER(3), JSON_STRING(2), JSON_ARRAY(1), JSON_OBJECT(0)} type, unsigned long refcount}) returning pointer to struct w_query_expr {long refcnt, pointer to function(pointer to struct w_query_ctx {..}, pointer to struct watchman_file {..}, pointer to void) returning _Bool evaluate, pointer to function(pointer to void) returning void dispose, pointer to void data} "=" pointer to void
  CC       query/watchman-eval.o
  CC       query/watchman-glob.o
  CC       query/watchman-intcompare.o
  CC       query/watchman-type.o
  CC       query/watchman-suffix.o
  CC       query/watchman-match.o
  CC       query/watchman-pcre.o
  CC       query/watchman-name.o
  CC       query/watchman-fieldlist.o
  CC       query/watchman-since.o
  CC       query/watchman-empty.o
  CC       watcher/watchman-auto.o
  CC       watcher/watchman-fsevents.o
  CC       watcher/watchman-inotify.o
  CC       watcher/watchman-kqueue.o
  CC       watcher/watchman-portfs.o
"watcher/portfs.c", line 174: improper member use: path
"watcher/portfs.c", line 174: improper member use: name
"watcher/portfs.c", line 178: undefined struct/union member: st
"watcher/portfs.c", line 178: warning: argument #3 is incompatible with prototype:
	prototype: pointer to struct stat {unsigned long st_dev, unsigned long st_ino, unsigned int st_mode, unsigned int st_nlink, unsigned int st_uid, unsigned int st_gid, unsigned long st_rdev, long st_size, struct timespec {..} st_atim, struct timespec {..} st_mtim, struct timespec {..} st_ctim, int st_blksize, long st_blocks, array[16] of char st_fstype} : "watcher/portfs.c", line 127
	argument : pointer to int
"watcher/portfs.c", line 205: warning: argument #1 is incompatible with prototype:
	prototype: pointer to struct  {int d_fd, int d_loc, int d_size, pointer to char d_buf} : "/usr/include/dirent.h", line 77
	argument : pointer to struct watchman_dir_handle {}
"watcher/portfs.c", line 209: undefined symbol: root
"watcher/portfs.c", line 209: warning: improper pointer/integer combination: arg #1
cc: acomp failed for watcher/portfs.c
make[1]: *** [watcher/watchman-portfs.o] Error 2
make[1]: Leaving directory `/sources/watchman'
make: *** [all] Error 2

Any questions lett me know via email or phone perhaps ?
NL 06-34114005

**Comment by wez** [comment]
Solaris support is known to be broken, as noted here:

https://facebook.github.io/watchman/docs/install.html#system-requirements

> Watchman used to support the following systems, but no one is actively maintaining them. The core of the code should be OK, but they likely don't build. We'd love it if someone would step forward to maintain them: ...
> Solaris

The biggest problem with maintaining the Solaris port is that we don't run on that platform and there is no continuous build infrastructure for Solaris, so in the absence of an active maintainer the code rots and stops working.

I was actually considering removing the code for Solaris this morning :-(

**Comment by njhnb** [comment]
Damn u got 2 be joking ? ;-)
Hate it that solaris support is going down the drain like that but it indeed seems to be the trend :-(

**Comment by njhnb** [comment]
trying to build firefox on solaris11.3 and need watchman/mercurial :-)

**Comment by sid0** [comment]
Would you be interested in taking over maintenance? Without a maintainer and without CI it's hard to keep project support for a platform alive.

**Comment by njhnb** [comment]
Hmm... ok I know I wont be switching to any other unix real soon haha.... have been runnning solaris since 2.5.1

There is no other way to get firefox compiled properly on solaris11.3 is there ?
I really need watchman ?

**Comment by sid0** [comment]
I'm not sure, honestly. Our good friends at Mozilla would be able to give you a better answer.

**Comment by wez** [comment]
@njhnb if its just for the mercurial integration with watchman, you can turn off the fsmonitor extension in your `~/.hgrc` file:

```
[extensions]
fsmonitor=!
```

**Comment by njhnb** [comment]
Thanks for that but still fails hahaha... solaris support is poor nowadays.

Might be interested in taking over maintenance though...

**Comment by wez** [comment]
re: maintenance, that would be very welcome.  We'll gladly take patches that help with this!
