### ISSUE TITLE
Add compatible versions of Python and license info in setup.py

### ISSUE THREAD

**Issue by jorgesumle** [facebook/watchman#396]
There is no way for people who browse PyPi to know the compatible versions. Also add the license info.

**Comment by wez** [comment]
We support python 2.6 and up.
The license is in https://github.com/facebook/watchman/blob/master/python/LICENSE.

Would you mind submitting a PR to add this info?

**Comment by jorgesumle** [comment]
This should be done by the packager or a experienced contributor, not by a person who doesn't know anything about the repository.
