### ISSUE TITLE
Upgrade to Sierra OS breaks Homebrew

### ISSUE THREAD

**Issue by mperez-bluechip** [facebook/watchman#397]
After upgrading to Sierra, I try to run 'brew install watcman' and get following errors: 

Error: You must `brew link autoconf` before watchman can be installed
Mannys-MacBook-Pro:~ [me]$ brew link autoconnf
Error: No such keg: /usr/local/Cellar/autoconnf
Mannys-MacBook-Pro:~ [me]$ brew link autoconf
Linking /usr/local/Cellar/autoconf/2.69... 
Error: Could not symlink share/autoconf/Autom4te/C4che.pm
Target /usr/local/share/autoconf/Autom4te/C4che.pm
already exists. You may want to remove it:
  rm '/usr/local/share/autoconf/Autom4te/C4che.pm'

**Comment by wez** [comment]
This is not a watchman issue; this is a local-to-you issue with your toolchain and homebrew.  I suggest that you follow up with the homebrew folks.

**Comment by mperez-bluechip** [comment]
Thank you Wez
