### ISSUE TITLE
shutdown-server shows incorrect version number

### ISSUE THREAD

**Issue by rmaz** [facebook/watchman#407]
`watchman --version` outputs `4.7.0`, `watchman shutdown-server` outputs:

```lang=json
{
    "version": "4.6.0",
    "shutdown-server": true
}
```

not an earth shaker admittedly.

**Comment by wez** [comment]
That just means that the running version of the watchman server was 4.6.0 and you had a newer client binary installed.   The `--version` flag shows the version of the watchman.exe that you're running, whereas the json output from various commands shows the server version.

If `watchman version` doesn't agree with `watchman --version` it means that you should run `watchman shutdown-server ; watchman version` to re-launch the watchman server.

**Comment by rmaz** [comment]
Interesting. If I try `watchman shutdown-server ; watchman version` I get:

```
{
    "version": "4.6.0",
    "shutdown-server": true
}
{
    "version": "4.6.0"
}
```

But `watchman --version` gives `4.7.0`. Explicitly killing the process has the same effect.

**Comment by wez** [comment]
Are you on a mac using homebrew?  You may be experiencing something like this issue: https://github.com/facebook/watchman/issues/358

**Comment by rmaz** [comment]
Yes and yes, `launchctl unload -F ~/Library/LaunchAgents/com.github.facebook.watchman.plist` does the trick.
