### ISSUE TITLE
Watchman does nothing

### ISSUE THREAD

**Issue by PaulBGD** [facebook/watchman#416]
I'm using it with react native and it just doesn't respond to any commands except help or version. I've tried reinstalling it multiple times.

All commands that have to do with its actual function don't work, such as `watchman shutdown-server`

Version 4.7.0 on macOS Sierra

**Comment by wez** [comment]
Can you share a paste of the exact output you're seeing from the watchman commands you're running?

Did you run through the troubleshooting guide?

https://facebook.github.io/watchman/docs/troubleshooting.html

Can you share information from your log file?

https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

**Comment by PaulBGD** [comment]
Hi, I read through the troubleshooting guide and since no commands work and there's no output from watchman (I've left it running for 30 minutes) I can't find anything that applies to me.

I couldn't find my log in the brew installation place like it said in the troubleshooting page, but I found it at `/usr/local/var/run/watchman/paul-state`.
I checked the log and it only had entries from 2016, plus the version at the top was 4.6.0 (one version below my current.)

After deleting this folder and recreating it, watchman functions as expected. I guess this issue is fixed for me, but I'm not quite sure why.

**Comment by wez** [comment]
I suspect that you hit https://github.com/facebook/watchman/issues/358

**Comment by PaulBGD** [comment]
Yeah looks like it, I copied down my logs but they're all 3 months + old with no errors so I don't think they're very helpful.

**Comment by wez** [comment]
OK, let's close this and chalk it up to another case of #358.
