### ISSUE TITLE
Installation failed for the latest version

### ISSUE THREAD

**Issue by skaushikWebuy** [facebook/watchman#421]
make  all-am
make[1]: Entering directory '/home/sachin/works/watchman'
make[1]: *** No rule to make target 'thirdparty/jansson/dump.c', needed by 'thirdparty/jansson/libwmanjson_a-dump.o'.  Stop.
make[1]: Leaving directory '/home/sachin/works/watchman'
Makefile:914: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wez** [comment]
Sounds like you had previously built watchman in that checkout before we moved to c++, and now the deps produced by automake don't match up.

You conceptually want to run `make distclean` here, but if that also doesn't work out, `git clean -dfx` may help tidy things up.

You will then need to rerun `autogen.sh` and `configure`.
