### ISSUE TITLE
Appveyor builds fail because of failure to install php

### ISSUE THREAD

**Issue by otrempe** [facebook/watchman#423]
I was glad to see some green build for Windows about a month ago on appveyor.

However, builds are not running properly since ~15 days because php install via chocolatey systematically fails.

It looks like chocolatey now needs a checksum to verify the package integrity.

**Comment by wez** [comment]
This is fixed, but there seems to be some test failures on appveyor that keeps us red.  I'll close out this issue and will look at addressing the others outside of this.
