### ISSUE TITLE
Warnings / Errors when running watchman

### ISSUE THREAD

**Issue by vanniktech** [facebook/watchman#426]
I was trying around with [okbuck](https://github.com/uber/okbuck) and when using it in conjunction with watchman, I get the following errors / warnings from watchman.

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
KeyError: 'files'
```

I'm using Watchman 4.7.0, which I installed via homebrew. Is there any other information I can give you? I also opened an issue already on okbuck site - https://github.com/uber/okbuck/issues/255 - however it seems like I am the only one facing this problem.

**Comment by wez** [comment]
That stack trace doesn't look like it is coming from watchman, but rather from some python code.
Can you give some more context on what that is?  I'm unfamiliar with okbuck and its wrapper scripts.

As to the error message that is bubbling up there, my hunch is that either:

* you are using the mercurial fsmonitor extension and that it is generating `state-enter` and `state-leave` events that are not being handled correctly by something in python that is using the subscription interface to watchman
* something in python is not correctly handling some error cases

Please share your watchman logs too: https://facebook.github.io/watchman/docs/troubleshooting.html#where-are-the-logs

**Comment by vanniktech** [comment]
I don't think that I'm using the `mercurial fsmonitor extension` extension. I've got Python 2.7.13 as well as Python 3.6.0 installed on my mac.

About the logs I've tried searching for them however I can't. Are those enabled by default? I also don't quite know how I can  set `--logfile` since I'm using watchman over okbuck which does all of the configuration.

**Comment by vanniktech** [comment]
I found one file under `/usr/local/var/run/watchman/nik-state/log` which contains:

> 2017-01-25T19:26:50,722: [client=0x7fb4b1443170:stm=0x7fb4b1442c40] send_error_response: ["query", "/Users/nik/tmp/okbuck", {"since": "n:okbuck_trig", "expression": ["allof", ["type", "f"], ["anyof", ["imatch", "**/*.gradle", "wholename"], ["imatch", "**/gradle-wrapper.properties", "wholename"], ["imatch", "**/lint.xml", "wholename"], ["imatch", "**/src/**/AndroidManifest.xml", "wholename"]]], "fields": ["name"]}] failed: unable to resolve root /Users/nik/tmp/okbuck: directory /Users/nik/tmp/okbuck is not watched

> 2017-01-25T19:26:50,736: [client=0x7fb4b12ad600:stm=0x7fb4b12ac5b0] send_error_response: ["query", "/Users/nik/tmp/okbuck", {"since": "n:okbuck_source_roots", "expression": ["allof", ["type", "d"], ["anyof", ["imatch", "**/src/**/java", "wholename"], ["imatch", "**/src/**/res", "wholename"], ["imatch", "**/src/**/resources", "wholename"]]], "fields": ["new", "exists", "name"]}] failed: unable to resolve root /Users/nik/tmp/okbuck: directory /Users/nik/tmp/okbuck is not watched

**Comment by wez** [comment]
If you run `watchman watch-project /Users/nik/tmp/okbuck` what does it output?

**Comment by vanniktech** [comment]
When executed from my home directory:

```
{
    "version": "4.7.0",
    "watch": "/Users/nik",
    "watcher": "fsevents",
    "relative_path": "tmp/okbuck"
}
```

**Comment by wez** [comment]
OK, I think you're having a problem because you most likely have a .git dir in your home directory.  Watchman sees that as the most appropriate point to initiate a watch (this is controlled by the `root_files` configuration setting).

I think this will sort things out for you:

```
watchman watch-del-all
touch /Users/nik/tmp/okbuck/.watchmanconfig
```

The `.watchmanconfig` file trumps any of the things that might be listed in the `root_files` config and should force the watch to be created in the okbuck project dir.

**Comment by vanniktech** [comment]
@wez yes I have a git directory / repository in my ~

About the file an empty one is enough? I'll try later as I'm on my mobile right now

**Comment by wez** [comment]
I think just touching it will be fine.  If that doesn't work you can make it hold an empty json object:

```
echo '{}' >  /Users/nik/tmp/okbuck/.watchmanconfig
```

**Comment by vanniktech** [comment]
This does work. Amazing. Thank you a lot for all of your help. Feel free to close this issue.
