### ISSUE TITLE
Wrong evaluation in since expression command?

### ISSUE THREAD

**Issue by DLT1412** [facebook/watchman#430]
Since command return true if the specified time property of the file is greater than the since value.
But when pass timestamps as argument in since command to compare with cclock or oclock, it return true if since value is greater than time property of file.
In since.cpp: 
```
    switch (field) {
      case since_what::SINCE_OCLOCK:
      case since_what::SINCE_CCLOCK: {
        const auto& clock =
            (field == since_what::SINCE_OCLOCK) ? file->otime() : file->ctime();
        if (since.is_timestamp) {
          return since.timestamp > clock.timestamp;
        }
        if (since.clock.is_fresh_instance) {
          return file->exists();
        }
```
I see compare return true when since.timestamp (since value) is greater than clock.timestamp (time property of file). It must be less than, or I misunderstood somewhere?

**Comment by wez** [comment]
Ooh, I think you're right.  If you're comparing oclock/cclock values though, we'd recommend using the clock value instead of timestamps.  I think that's why we haven't noticed this issue before.

**Comment by wez** [comment]
I've queued up the fix for this, along with an integration test, and this should get sync'd up here in the next day or so.  This is the trivial fix:

```
@@ -37,7 +37,7 @@
         const auto& clock =
             (field == since_what::SINCE_OCLOCK) ? file->otime() : file->ctime();
         if (since.is_timestamp) {
-          return since.timestamp > clock.timestamp;
+          return clock.timestamp > since.timestamp;
         }
         if (since.clock.is_fresh_instance) {
           return file->exists();
```

**Comment by DLT1412** [comment]
Thanks so much :+1:
