### ISSUE TITLE
art.t segfaults when thirdparty/libart/tests/words.txt doesn't exist and glibc=2.19

### ISSUE THREAD

**Issue by geeknik** [facebook/watchman#434]
Compiled watchman with afl-clang-fast and ASan. Was not able to determine if this test should be segfaulting when the file doesn't exist. Test completes successfuly when the file is found.

`ASAN_SYMBOLIZER_PATH=/usr/lib/llvm-3.5/bin/llvm-symbolizer ASAN_OPTIONS=symbolize=1 ./art.t`
```
1..84
not ok 1 - can't find test data file thirdparty/libart/tests/words.txt
#     Failed test (tests/art_test.cpp:open_test_file() at line 35)
ASAN:SIGSEGV
=================================================================
==23029==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x7fd0f7382e0b bp 0x7ffe745d9750 sp 0x7ffe745d91a0 T0)
    #0 0x7fd0f7382e0a in fgets /build/glibc-qK83Be/glibc-2.19/libio/iofgets.c:42
    #1 0x4c8bde in test_art_insert() /root/watchman/tests/art_test.cpp:46:10
    #2 0x4d8075 in main /root/watchman/tests/art_test.cpp:420:3
    #3 0x7fd0f733ab44 in __libc_start_main /build/glibc-qK83Be/glibc-2.19/csu/libc-start.c:287
    #4 0x4c88cc in _start (/root/watchman/tests/art.t+0x4c88cc)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /build/glibc-qK83Be/glibc-2.19/libio/iofgets.c:42 fgets
==23029==ABORTING
```

If this is a glibc issue, there isn't an upstream bug report.

**Comment by wez** [comment]
The test is designed to be run from the root of the watchman repo, and that is how the test harness runs it.  It is fine for it to fault if the file isn't found; the test has to have that file in order to pass anyway, so a fault accurately reflects failure.
