### ISSUE TITLE
PCRE invalid escape

### ISSUE THREAD

**Issue by cerealbeer** [facebook/watchman#439]
Hello,

I am trying to enable **pcre**, so I ran:

```
sudo apt install libpcre3 libpcre3-dev
sudo ./configure --with-pcre=/usr/bin/pcre-config
...
checking for PCRE using /usr/bin/pcre-config... 8.38
checking pcre.h usability... yes
checking pcre.h presence... yes
checking for pcre.h... yes
...
sudo make
...
CC       query/watchman-pcre.o
...
sudo make install
```

And it finishes successfully, but when I run:

```
watchman -j <<-EOT                                 
["query", "/tmp", {
    "since": "n:whatever",
    "expression": ["allof",
        ["ipcre", "\.(jpg|png)$", "basename"],
        ["type", "f"]
    ]
}]
EOT
```

I get:

`failed to parse command from stdin: invalid escape near '"\.'`

If I try a simpler expression like `(jpg|png)$` it works fine, but I cannot write complex expressions. The system is Ubuntu 16.04: Linux HN 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:49:39 UTC 2017 i686 i686 i686 GNU/Linux

The strace of watchman: [debug.txt](https://github.com/facebook/watchman/files/828059/debug.txt)

What could I do?
Thanks for your attention.

**Comment by wez** [comment]
You need to escape the backslash for this to be proper JSON:

`\\.(jpg|png)$`

**Comment by cerealbeer** [comment]
Thank you for your reply!

By doing that I got the same error message:

```
watchman -j <<-EOT
["query", "/tmp", {
    "since": "n:whatever",
    "expression": ["allof",
        ["ipcre", "\\.(jpg|png)$", "basename"],
        ["type", "f"]
    ]
}]
EOT
failed to parse command from stdin: invalid escape near '"\.'
```

I added a third backslash `\\\.(jpg|png)$` and it executed, without returning results:

```
EOT
{
    "version": "4.7.0",
    "clock": "c:1488987321:10391:1:9261",
    "is_fresh_instance": false,
    "files": []
}
```

So I loaded **pcretest** and got this error:

`pcretest: error while loading shared libraries: libpcre.so.1: cannot open shared object file: No such file or directory`

After doing `sudo ldconfig` and rebuilding watchman I got it working, but I have to use `\\\`. Is it correct to escape like this? In pcretest works fine like this:

```
PCRE version 8.40 2017-01-11

  re> /\.(jpg|png)/
data> image.jpg
 0: .jpg
 1: jpg
```

**Comment by wez** [comment]
Ah, well there are two layers of quoting that you need to account for:

1. Your shell
2. JSON

You need to have sufficient backslashes that your shell passes `\\` to watchman so that it can then be parsed as json.

FWIW, you may want to use the `suffix` term for this particular use case instead.  https://facebook.github.io/watchman/docs/expr/suffix.html

**Comment by cerealbeer** [comment]
I see,

in my case it's bash, I will try `suffix` too, thank you very much!
