### ISSUE TITLE
Windows: Endless loop in InMemoryView::ioThread

### ISSUE THREAD

**Issue by otrempe** [facebook/watchman#444]
Hi!

I am currently struggling debugging the watchman process being caught in an endless loop within InMemoryView::ioThread.

I could not identify the exact cause of the problem and reproduce it systematically.

I generally observe it while compiling a large Visual Studio solution for which the output directory is under a watched root. If I add the output directory to "ignore_dirs", it seems to be just worse.

I also observed it while doing some rebases with mercurial.

I tried to debug what's going on. I was first suprised to see that files under my ignore_dirs entry were still stat-ed. Why?

Then I realized the files were endlessly "stolen" from the pending collection ( coll->stealItems(); ) and re-added to the collection in the last "if" of "InMemoryView::statPath". So I guess this is why the pending collection is never entirely processed, hence the endless loop.

I thought it might be related to the presence of symlinks in the tree, but real files are also caught in the this loop.

I am willing to put some effort to fix this, but I would need some help to start in the right direction  given my limited background playing in the watchman source code.

This is a major showstopper for me to roll out watchman to 70+ Windows users.

**Comment by wez** [comment]
I think I might have a fix for this sitting in my tree.  I need to get this cleaned up a bit before I can land it.  I'll see if I can get it in better shape to at least share with you.

**Comment by otrempe** [comment]
That's great news. We can run watchman with this custom patch for a few days and if it works properly, I can turn it into a pull request.

**Comment by otrempe** [comment]
Hi @wez, any progress on this?

If you don't plan to land the patch soon, you could send me a draft, so I can validate it fixes the problem. And maybe I could clean it on my side...

**Comment by wez** [comment]
I'm (finally!) looking at windows stuff this week; let's see whether we can sort this out at the same time

**Comment by wez** [comment]
OK, those changes should now all be in the most recent build, and this link should always resolve to the most recent build if you just want to try it out quickly without building it yourself:

https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D

**Comment by otrempe** [comment]
Awesome! I played with it this afternoon and it seems to work perfectly. I deploy it immediately to a few developers. If we don't have issues within a few days, we will roll it out to the whole team. I expect some very happy co-workers next week!

**Comment by wez** [comment]
How's this working out for you?  Can we close this issue?

**Comment by otrempe** [comment]
After almost a week using the most recent build (8 developers), I think we can close this issue. We did not observed any strange behavior. Thank you!

We are now investigating another issue with ignore_dirs where an ignored directory is actually not ignored. If we can fix this, we will submit a pull request, otherwise, we'll open a new issue.

**Comment by wez** [comment]
Great; thanks for confirming!
