### ISSUE TITLE
Erlang bindings

### ISSUE THREAD

**Issue by steakknife** [facebook/watchman#446]
Would be great.

Bonus points for Elixir bindings/usage.

**Comment by wez** [comment]
Erlang support isn't on our radar so this is unlikely to happen unless someone is willing to implement it and contribute it along with integration tests that can be run in existing CI (Travis and/or Circle) in order to keep the bindings in working order.

**Comment by wez** [comment]
I'm going to close this out because it isn't on our roadmap.  If someone wants to add it, great!
