### ISSUE TITLE
Where can I find docs on watchman configuration?

### ISSUE THREAD

**Issue by EugenMayer** [facebook/watchman#448]
Hello, trying to migrate http://docker-sync.io to watchdog, currently using unox.

Any chance you could outline how excludes would work ( https://github.com/EugenMayer/docker-sync/issues/297 ). I found https://github.com/facebook/watchman/commit/56fcdbac15bd6cda1790c13aa9b05bf9fa3cd237 but yet not other docs.

Thanks !

**Comment by sid0** [comment]
See http://facebook.github.io/watchman/docs/config.html for documentation on config options.
