### ISSUE TITLE
Error building watchman 

### ISSUE THREAD

**Issue by nabeelomer** [facebook/watchman#449]
I am trying to build watchman, I executed the commands:
```zsh
git clone https://github.com/facebook/watchman.git
git checkout 2ab4a0fd6e1adcc75df72d6adcbbaead123eea91
./autogen.sh
./configure
make
```
But I get the error:
```
ChildProcess.cpp: In lambda function:
ChildProcess.cpp:269:71: error: throw will always call terminate() [-Werror=terminate]
             watchman::to<std::string>("failed to chdir to ", savedCwd));

```

**Comment by wez** [comment]
You can use `./configure --enable-lenient` to cause the compiler to not treat that as an error.
Why are you building from that commit hash rather than one of our branches?

**Comment by nabeelomer** [comment]
@wez Thanks, I'll use `./configure --enable-lenient`. I'm building from the commit hash because that is the hash of the v4.8.0-rc1 release. Should I be building from master?

**Comment by joseluisq** [comment]
@nabeelomer 
As @wez says you can try to build from some branch. Check out this thread https://github.com/facebook/watchman/issues/432

**Comment by wez** [comment]
The source of these compilation problems have been resolved in master, so I'm closing this out.
