### ISSUE TITLE
Website header's "Support" link only works from the main page, not any "Docs" page

### ISSUE THREAD

**Issue by cpick** [facebook/watchman#454]
If you're on the [main page](https://facebook.github.io/watchman/) then clicking on the "Support" link up in the header will correctly bring you to: https://facebook.github.io/watchman/support.html

However, if you're within one of the ["Docs" pages](https://facebook.github.io/watchman/docs/install.html) then the relative link will be broken as it erroneously tries to send you to something like the following to 404 out: https://facebook.github.io/watchman/docs/support.html

It looks like the needs to be made absolute or more context aware.

**Comment by gauravkumar28** [comment]
https://github.com/facebook/watchman/pull/456/files

**Comment by wez** [comment]
Really fixed by https://github.com/facebook/watchman/commit/5e99349a22daab444e2f78761603a6b9b620fa1f which has now pushed.  Thanks for reporting this!
