### ISSUE TITLE
[Windows] Watchman unable to watch some directories

### ISSUE THREAD

**Issue by benpeart** [facebook/watchman#460]
Watchman apparently cannot watch some directories:

E:\ost2>watchman watch-project E:\ost2
{
    "version": "4.9.0",
    "error": "unable to resolve root E:/ost2: unable to lstat \"E:/ost2\" 22"
}

E:\vso.old\src>watchman watch-project e:\vso.old\src
{
    "version": "4.9.0",
    "watch": "E:/vso.old/src",
    "watcher": "win32"
}

**Comment by wez** [comment]
is there any more context available in the log file?  The file can be found at `%TEMP%\%USERNAME%-state\log`

**Comment by wez** [comment]
is there a more restrictive ACL set on ost2?  Can you get a filemon (or whatever the equivalent tool is these days!) trace of watchman when it tries to examine that folder?

**Comment by benpeart** [comment]
[log.zip](https://github.com/facebook/watchman/files/988277/log.zip)
[Procmon.Logfile.zip](https://github.com/facebook/watchman/files/988393/Procmon.Logfile.zip)

**Comment by wez** [comment]
Ah, interesting.  Looks like we're walking up to the root and trying to QueryNameInformationFile on `E:`, which fails.

I'm currently doing some work on our filesystem functions and will test this case.

**Comment by wez** [comment]
I'm able to successfully `watchman watch-project c:\python27` locally with the changes I have queued up for review here, so things are looking good.  I'm just waiting on some internal code review before I push those changes.

**Comment by wez** [comment]
My changes are pushed.   I also figured out how to link to the most recent master build from appveyor:

https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D
