### ISSUE TITLE
Example of a  react-native workflow with watchman?

### ISSUE THREAD

**Issue by nodox** [facebook/watchman#463]
Can we add example `.watchconfig` files?

The documentation is missing examples of how to use watchman in a real project. I understand what watchman does but I'm not sure how to incorporate it into my workflow to do something as simple. Which is daunting as I'm new to react-native ecosystem.

**Comment by wez** [comment]
In general you don't need to provide a `.watchmanconfig` file as things should just work.
Watchman configuration becomes more important as the size (number of files and folders) of your directory tree becomes extremely large.

I'm afraid that the folks that work on watchman don't really know very much about react-native, so if you have questions about that, you're better served by talking to the folks on the react-native project.
