### ISSUE TITLE
watchman doesn't work on windows 7

### ISSUE THREAD

**Issue by bochen2014** [facebook/watchman#475]
I am using `relay-modern` which relies on `watchman` in its compilation process. 
I downloaded watchman from 
>http://bit.ly/watchmanwinalpha

and it actually works quite well on my windows 10 machine (office dev machine)
tonight I spent almost 2 hours trying to find out why I couldn't compile `graphql` liternals on my home windows 7 machine, and I finally pinpoint  to `watchman` ( I thought it was npm package issues)
![image](https://cloud.githubusercontent.com/assets/8207081/26587093/afe8ff0e-4594-11e7-9c41-fb9534732bfc.png)

it seems that `watchman.exe` communicate with `fb-watchman` via socket and for some reason, `queryfiles` always return an empty array causing no files being compiled by `relay-compiler`

does anybody else get the same problem?

**Comment by wez** [comment]
Can you try a build from master?  There have been some recent fixes for win7 (https://github.com/facebook/watchman/commit/1bf0e4d321c11c43ebce71bb9fed0c12b1d7845f is the most recent).

Steps to find the latest build (you can skip to step 4 to get going, but for the benefit of someone else finding this issue in the future, I've included the steps below):

1. Go to the appveyor project: https://ci.appveyor.com/project/wez/watchman
2. Click on one of the jobs at the bottom (eg: today the most recent one is https://ci.appveyor.com/project/wez/watchman/build/job/fa1hlfi4fuxajdpc)
3. Click on the artifacts tab (https://ci.appveyor.com/project/wez/watchman/build/job/fa1hlfi4fuxajdpc/artifacts)
4. Download watchman.zip: https://ci.appveyor.com/api/buildjobs/fa1hlfi4fuxajdpc/artifacts/watchman.zip

There are some more changes in our internal review queue for windows that should improve things in general, and it's on my todo list to make it easier to find and download the master builds

**Comment by mlabrum** [comment]
Seems this may be happening with react-native too, I've downloaded the latest watchman via your above links and I keep getting
`Cannot find entry file index.android.js in any of the roots"
```
error: bundling: Error
    at DependencyGraph._getAbsolutePath (C:/tmp/test/test/node_modules/react-native/packager/src/node-haste/index.js:272:11)
    at DependencyGraph.getDependencies (C:/tmp/test/test/node_modules/react-native/packager/src/node-haste/index.js:216:26)
    at Resolver.getDependencies (C:/tmp/test/test/node_modules/react-native/packager/src/Resolver/index.js:106:27)
    at _resolverPromise.then.resolver (C:/tmp/test/test/node_modules/react-native/packager/src/Bundler/index.js:561:62)
    at process._tickCallback (internal/process/next_tick.js:109:7)
```

**Comment by wez** [comment]
@mlabrum are you running windows 7?  If not, please open a separate issue and include your watchman logs.  You can find the logs in `%TEMP%\%USER%-state\log` on windows systems.

**Comment by bochen2014** [comment]
I can confirm that [this build](https://ci.appveyor.com/api/buildjobs/kcl3jeagtytirksa/artifacts/watchman.zip) works fine on my windows7 box. thanks @wez  !

**Comment by wez** [comment]
@bochen2014 good to hear!  I have some more windows changes pushing today, but that build you tried has the most significant windows specific changes

**Comment by wez** [comment]
@mlabrum please open a separate issue if the latest build doesn't work for you.

https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D
