### ISSUE TITLE
fails to start if TMP variable has a trailing backslash

### ISSUE THREAD

**Issue by galki** [facebook/watchman#485]
* downloaded watchman from https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D
* saved watchman inside C:\Users\peter\[folder]\[folder]
* updated PATH variable
* removed all local and global npm watchman packages

Environment: Windows 10 Pro
Shell: Powershell (tried bash as well)
`$ watchman -v` returns 4.9.0 
`$ watchman -h` also works
`$ watchman [any other command]` returns something like this:
```
2017-06-09T12:27:50,563: [] while computing statefile: failed to create C:\Users\peter\AppData\Local\Temp\/peter-state: Invalid argument
```
#### what i noticed
double clicking watchman.exe creates a `peter-state` folder in `C:\Users\peter\AppData\Local\Temp` (not sure about the forward slash)

**Comment by wez** [comment]
Can you share the list of environmental variables in the command prompt where you're running that?
I'm not sure how to do that from powershell, but in cmd.exe you'd just run `set`.

I'm most interested in the TMPDIR and/or TMP variables, as well as the USER variable; these control the generation of the state dir.

**Comment by galki** [comment]
In powershell I ran `echo $Env:TEMP` and it output `C:\Users\peter\AppData\Local\Temp\` 

The USER var does not appear to be set. 
Perhaps it's the USERNAME var (my current user is `peter`)

This is what I got from calling set in cmd.exe
```
ALLUSERSPROFILE=C:\ProgramData
APPDATA=C:\Users\peter\AppData\Roaming
CommonProgramFiles=C:\Program Files\Common Files
CommonProgramFiles(x86)=C:\Program Files (x86)\Common Files
CommonProgramW6432=C:\Program Files\Common Files
COMPUTERNAME=BLONDEOWL
ComSpec=C:\WINDOWS\system32\cmd.exe
FPS_BROWSER_APP_PROFILE_STRING=Internet Explorer
FPS_BROWSER_USER_PROFILE_STRING=Default
FP_NO_HOST_CHECK=NO
HOMEDRIVE=C:
HOMEPATH=\Users\peter
LOCALAPPDATA=C:\Users\peter\AppData\Local
LOGONSERVER=\\BLONDEOWL
MAGICK_HOME=C:\Program Files (x86)\ImageMagick-6.9.1-Q16\modules\coders
NUMBER_OF_PROCESSORS=4
OneDrive=C:\Users\peter\OneDrive
OS=Windows_NT
Path=C:\Users\peter\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files\Docker\Docker\Resources\bin;C:\Python27\;C:\Python27\Scripts;C:\Program Files (x86)\ImageMagick-6.9.1-Q16;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\phalcon-tools;C:\Users\peter\Projects\_programs\watchman;C:\xampp7\php;C:\ProgramData\ComposerSetup\bin;C:\Users\peter\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Program Files (x86)\Yarn\bin;C:\Program Files\Git\cmd;C:\Program Files\Jq;C:\Program Files (x86)\ImageMagick-6.9.1-Q16;C:\WINDOWS\system32;C:\WINDOWS;C:\WINDOWS\System32\Wbem;C:\WINDOWS\System32\WindowsPowerShell\v1.0\;C:\Program Files (x86)\Windows Live\Shared;C:\Program Files\TortoiseGit\bin;C:\HashiCorp\Vagrant\bin;C:\xampp\php;C:\Users\peter\Projects\_programs\watchman;C:\phalcon-tools;C:\ProgramData\ComposerSetup\bin;C:\Users\peter\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\Python27\Scripts;C:\Users\peter\AppData\Local\Microsoft\WindowsApps;C:\Users\peter\AppData\Local\Google\Cloud SDK\google-cloud-sdk\bin;C:\Users\peter\AppData\Roaming\Composer\vendor\bin;C:\Users\peter\AppData\Local\Yarn\.bin;C:\Program Files\Jq
PATHEXT=.COM;.EXE;.BAT;.CMD;.VBS;.VBE;.JS;.JSE;.WSF;.WSH;.MSC;.SH
PROCESSOR_ARCHITECTURE=AMD64
PROCESSOR_IDENTIFIER=Intel64 Family 6 Model 69 Stepping 1, GenuineIntel
PROCESSOR_LEVEL=6
PROCESSOR_REVISION=4501
ProgramData=C:\ProgramData
ProgramFiles=C:\Program Files
ProgramFiles(x86)=C:\Program Files (x86)
ProgramW6432=C:\Program Files
PROMPT=$P$G
PSModulePath=;C:\Users\peter\AppData\Local\Google\Cloud SDK\google-cloud-sdk\platform\PowerShell;
PUBLIC=C:\Users\Public
SESSIONNAME=Console
SystemDrive=C:
SystemRoot=C:\WINDOWS
TEMP=C:\Users\peter\AppData\Local\Temp
TMP=C:\Users\peter\AppData\Local\Temp
USERDOMAIN=blondeowl
USERDOMAIN_ROAMINGPROFILE=blondeowl
USERNAME=peter
USERPROFILE=C:\Users\peter
VBOX_MSI_INSTALL_PATH=C:\Program Files\Oracle\VirtualBox\
windir=C:\WINDOWS
```

**Comment by wez** [comment]
Can you try removing the trailing slash from the TMP variable and see if that helps things?

**Comment by wez** [comment]
oh, in cmd you don't have a trailing backslash, but you do in powershell?

can you run `watchman version` from cmd?  It should print the version info in json format if it is successful.

**Comment by galki** [comment]
Appears to be so. `watchman version` in cmd prints
```
{
    "version": "4.9.0",
    "buildinfo": "5e99349a22daab444e2f78761603a6b9b620fa1f 2017-06-08T22:08:19.0000000Z"
}
```
and watchman commands work as well. 

But it would really help if the powershell problem can be fixed!

**Comment by galki** [comment]
would really appreciate a fix for this because windows docker uses powershell - losing docker automation functionality :(

do any other windows users have temp solutions?

**Comment by wez** [comment]
A temp solution is to amend the TMP variable before running commands that depend on watchman.  I know it's not super convenient!

https://github.com/facebook/watchman/issues/510 is a related issue; we'll likely fix both at the same time, but it depends on having the bandwidth to address the issue.

We'd welcome a pull request if you feel up to resolving this for yourself!

**Comment by galki** [comment]
i went for your TMP solution and it worked - thank you!

i tool a quick look at the watchman code and figured all that needs to be done is removing any backslashes after https://github.com/facebook/watchman/blob/d9c1db79b2eaf1bbdfe25a89926c5900da551a8b/main.cpp#L737 - but lack of experience prevents me from making a quick test

ill be looking forward to the fix. thanks again!

**Comment by galki** [comment]
btw this is my current js solution. i run it before executing code that relies on watchman
```node
const shell = require('shelljs')

if (process.env.TERM === 'msys' && process.env.TMP.endsWith('\\')) {
  shell.env['TMP'] = process.env.TMP.substr(0, process.env.TMP.length - 1)
}
```

**Comment by wez** [comment]
Should finally be resolved by https://github.com/facebook/watchman/commit/74797da25b0aba18d4558d270244450ab3747be4
