### ISSUE TITLE
'your system lacks libtoolize' error when installing

### ISSUE THREAD

**Issue by ravin-kt** [facebook/watchman#486]
When I try to install watchman using: 
`brew install --HEAD watchman`

I get the message: 

```
./autogen.sh
your system lacks libtoolize
```

I know that I have `libtoolize` and `libtool`
Running `which libtoolize` gives me:
`/Users/<myusername>/libtoolize`

Running `which libtool` gives me:
`/usr/bin/libtool`

I have already seen issue #432 and I am still unable to get past the libtoolize error.

**Comment by wez** [comment]
You need to `brew install libtool`.   The macOS `libtool` is not the same as the autotools `libtool` which is installed as `glibtool` (and `glibtoolize`).

This should happen automatically as part of the deps in the homebrew recipe.

**Comment by ravin-kt** [comment]
After I `brew install libtool` it gives me the warning: `Warning: libtool 2.4.6_1 is already installed` and still produces the same result asked in the original question.

**Comment by netdevjamie** [comment]
Same issue here. I installed libtool `brew install libtool` and still get "./autogen.sh

your system lacks libtoolize
"
when trying to run `brew install --HEAD watchman`

**Comment by wez** [comment]
This should be fixed in homebrew now; update brew and run `brew install --HEAD watchman`

**Comment by nikhilgoswami** [comment]
On mac you need glibtool see [https://facebook.github.io/watchman/docs/install.html#installing-from-source](https://facebook.github.io/watchman/docs/install.html#installing-from-source)

**Comment by vitrum** [comment]
If you just update to macOS High Sierra version 10.13, you can try reinstall Command Line Tools.

**Comment by aaronplanell** [comment]
In Linux run `sudo apt-get install libtool`.

**Comment by narshi** [comment]
Go for this "sudo apt install linuxbrew-wrapper" , it works
