### ISSUE TITLE
Path had bad ownership/permissions 

### ISSUE THREAD

**Issue by ickma** [facebook/watchman#488]
Each time I ran `watchman watch xxx` or  `launchctl load ~/ibrary/LaunchAgents/com.github.facebook.watchman.plist`,it kept show `~/Library/LaunchAgents/com.github.facebook.watchman.plist: Path had bad ownership/permissions`.      
other infomation: i moved my home dir to an extenal hard disk,i think this is wht the issue happend ,but i don't know how to sovle.

**Comment by wez** [comment]
You should be able to solve this by running `rm ~/Library/LaunchAgents/com.github.facebook.watchman.plist`

**Comment by ickma** [comment]
I did running `rm ~/Library/LaunchAgents/com.github.facebook.watchman.plist`,but still the same error:`/Volumes/SSD/nick/Library/LaunchAgents/com.github.facebook.watchman.plist: Path had bad ownership/permissions`

**Comment by ickma** [comment]
@wez, i solved this problem, the way is, set `ignore ownership on this volume` to my external SSD in which there is my home dir.Then, everything is correct now!

**Comment by wez** [comment]
I suspect that the right way to fix you local permission problem would be to reset the ownership to match your current creds, possibly by chowning the files/dirs that got moved.  I don't want to suggest performing a broad chown in case it has other negative side effects; it's worth noting that disabling ownership (or opening up the read/write permissions) on a volume can weaken the security of your system.

This isn't actually a watchman issue: watchman is surfacing that something is broken with the access control settings on your migrated volume.
