### ISSUE TITLE
Why does function spawnError in NodeJs print to console

### ISSUE THREAD

**Issue by JayChandler** [facebook/watchman#491]
Currently there is no possibility to supress the console.error call in the spawnError function. This way i will always have output to the console! Should error display not be handled by the consumer ? 

Thx

**Comment by wez** [comment]
Ideally, yep, the consumer would do the responsible thing with the error information.  In practice most integrations swallowed this low level error and we got problem reports that were very hard to diagnose.
For example: it is common for folks to have globally installed the `watchman` package from npm (which is not the Facebook watchman service!) and then run into problems attempting to use the `fb-watchman` client.

I'd like to keep this error logging as the default behavior, but would be happy to accept a PR that allows turning it off if you really want it to change.

**Comment by wez** [comment]
I'm going to close out this question.  If you'd like to change the behavior per my comment above, please send us a PR!
