### ISSUE TITLE
Unable to track the creation of directories

### ISSUE THREAD

**Issue by JayChandler** [facebook/watchman#492]
Why does this not work ? I want to track changes for all directories ( including creation and deletion ) underneath a given root directory. Is this not possible with watchman ?

```
var sub = {
    expression: ["allof", ["type", "d"]],
    fields: ["name", "size", "mtime_ms", "exists", "type"]
};

client.command(['subscribe', "D:/", 'config', sub],
    function(error, resp) {
        if (error) {
            console.log(error);
            return;
        }
    }
);
```

**Comment by wez** [comment]
Can you elaborate on what you mean by not working?  Are you getting errors?  Is it not producing the results you expect?

Please also include the output from `watchman version`.

**Comment by wez** [comment]
When you get a chance to respond with the requested information, please do so and re-open this issue then.
