### ISSUE TITLE
I get MSVCP140.dll error when testing if watchman is working

### ISSUE THREAD

**Issue by erlendureyv** [facebook/watchman#494]
Hi,

I followed the instructions on http://facebook.github.io/watchman/docs/install.html for Windows but I keep getting MSVCP140.dll error when testing if watchman is working by running watchman -v via command prompt (with administrative privileges).  I am using Windows 8.1 Version 6.3 Build 9600 according to winver via command prompt.

Regards, Erlendur

![image](https://user-images.githubusercontent.com/29660165/27486380-eed4f900-581f-11e7-9d98-1547e856cbd9.png)

**Comment by wez** [comment]
Can you try the advice from this page?

https://answers.microsoft.com/en-us/windows/forum/windows_10-performance/msvcp140dll-is-missing-in-my-win-10/1c65d6b0-68b8-4b59-b720-3e6a33038389

**Comment by wez** [comment]
@erlendureyv: did the comment above help you resolve this issue?

**Comment by erlendureyv** [comment]
Hi,
I have not had the time to test it.  Should be able to do so in the next few days.
Regards, Erlendur


Sent from my Samsung Galaxy smartphone.
-------- Original message --------From: Wez Furlong <notifications@github.com> Date: 03/07/2017  19:42  (GMT-05:00) To: facebook/watchman <watchman@noreply.github.com> Cc: erlendureyv <erlendur.eyvindarson@gmail.com>, Mention <mention@noreply.github.com> Subject: Re: [facebook/watchman] I get MSVCP140.dll error when testing if
  watchman is working (#494) 
@erlendureyv: did the comment above help you resolve this issue?

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  




{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/facebook/watchman","title":"facebook/watchman","subtitle":"GitHub repository","main_image_url":"https://cloud.githubusercontent.com/assets/143418/17495839/a5054eac-5d88-11e6-95fc-7290892c7bb5.png","avatar_image_url":"https://cloud.githubusercontent.com/assets/143418/15842166/7c72db34-2c0b-11e6-9aed-b52498112777.png","action":{"name":"Open in GitHub","url":"https://github.com/facebook/watchman"}},"updates":{"snippets":[{"icon":"PERSON","message":"@wez in #494: @erlendureyv: did the comment above help you resolve this issue?"}],"action":{"name":"View Issue","url":"https://github.com/facebook/watchman/issues/494#issuecomment-312750374"}}}

**Comment by wez** [comment]
Closing this on the assumption that switching to static linkage fixed it.
