### ISSUE TITLE
Watchman hold handles to files preventing delete

### ISSUE THREAD

**Issue by benpeart** [facebook/watchman#507]
I see this frequently when using "git difftool" and bcompare as well as when trying to run the git test suite, watchman is holding handles to files which prevents the file/folder from being deleted.  I've verified it is watchman by 1) using the handle tool which identifies the watchman process as well as 2) shutting down the watchman server which then releases the handle and allows the file to be removed.

I've been sitting on this for some time trying to get a consistent repro but while it happens frequently, I've never found a consistent repro so decided to file it anyway.  Below is one recent interaction that demonstrates the issue:

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ sh t0004-unwritable.sh
rm: cannot remove '/usr/src/git/t/trash directory.t0004-unwritable': Device or resource busy
FATAL: Cannot prepare test area

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ watchman shutdown-server
{
    "version": "4.9.0",
    "shutdown-server": true
}

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ sh t0004-unwritable.sh
ok 1 - setup
ok 2 # skip write-tree should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY)
ok 3 # skip commit should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY)
ok 4 # skip update-index should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY)
ok 5 # skip add should notice unwritable repository (missing SANITY,POSIXPERM of POSIXPERM,SANITY)
# passed all 5 test(s)
1..5

**Comment by wez** [comment]
is the opened handle always the root of the watch, or is it some arbitrary handle under that tree?

**Comment by benpeart** [comment]
I see it most often holding a handle to an actual file.  The most common repro is when I run a "git difftool" which is configured (on my machine) to show the differences using Beyond Compare.  A temporary file (mangled_filename.TMP) is created and passed to BC. When BC exits, it attempts to delete the temporary file but Watchman is holding a handle to it so the delete fails leaving the temporary file in the working directory.

**Comment by benpeart** [comment]
Here is another repro that demonstrates both problems I'm currently seeing frequently and the associated log file.  Hope you can figure this out fix it as I'm having difficulty making progress on the git/watchman integration.

warning: unable to unlink .git/objects/1c/tmp_obj_AXZS49: Invalid argument
error: unable to write sha1 filename .git/objects/1c/7dd505b507b74be779cd4956e03a999fa17ce3: Invalid argument
fatal: git-write-tree: error building trees
2017-08-12T16:11:20,440: [cli] unable to talk to your watchman on \\.\pipe\watchman-Ben! (Invalid argument)
fatal: Failed to resolve 'HEAD' as a valid ref.
[...]

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ sh t1012-read-tree-df.sh -v -i -d
rm: cannot remove '/usr/src/git/t/trash directory.t1012-read-tree-df': Device or resource busy
FATAL: Cannot prepare test area

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ handle "trash directory.t1012-read-tree-df"

Handle v4.0
Copyright (C) 1997-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

cmd.exe            pid: 34420  type: File            3C: C:\git-sdk-64\usr\src\git\t\trash directory.t1012-read-tree-df
watchman.exe       pid: 58836  type: File            40: C:\git-sdk-64\usr\src\git\t\trash directory.t1012-read-tree-df
watchman.exe       pid: 58836  type: File           238: C:\git-sdk-64\usr\src\git\t\trash directory.t1012-read-tree-df

Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ pskill watchman

PsKill v1.15 - Terminates processes on local or remote systems
Copyright (C) 1999-2012  Mark Russinovich
Sysinternals - www.sysinternals.com

Process watchman killed.


Ben@BenPeart-HP MINGW64 /usr/src/git/t (fsmonitor)
$ handle "trash directory.t1012-read-tree-df"

Handle v4.0
Copyright (C) 1997-2014 Mark Russinovich
Sysinternals - www.sysinternals.com

No matching handles found.

[log.zip](https://github.com/facebook/watchman/files/1219901/log.zip)

**Comment by wez** [comment]
We haven't had this bubble up since then, so considering this to be closed
