### ISSUE TITLE
“[cli] unable to talk to your watchman on \\.\pipe\watchman-Ben! (Invalid argument)”

### ISSUE THREAD

**Issue by benpeart** [facebook/watchman#508]
This is another error I've been running fairly regularly.  It seems to be timing related because if I try the operation a 2nd time, it typically succeeds.  I can get it to happen pretty much every time I try to run the git test suite using multiple threads. 

I've attached a log file that captured one of these errors:

[log.zip](https://github.com/facebook/watchman/files/1183904/log.zip)

**Comment by wez** [comment]
Hrmm, it wouldn't surprise me if that "invalid argument" reason isn't totally accurate (it goes through some error code mapping).   We can do a better job at propagating the underlying error code up.  I don't think we have enough context in what we're emitting from the client here to understand what is really going wrong, so we need to make this better.

**Comment by benpeart** [comment]
It's easy to repro - just run the git test suite in parallel - when you have a build for me to try, let me know and I can capture logs again.

**Comment by mlabrum** [comment]
I'm also seeing this every now and then
```
Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2017-08-08T09:57:15,590: [cli] unable to talk to your watchman on \\.\pipe\watchman-Matt! (Invalid argument)
```

let me know if I can provide any logs for this

```
watchman version
{
    "version": "4.9.0",
    "buildinfo": "1b907b831fa4d19411a2063b0da4afeadc4e9613 2017-07-26T03:07:45.0000000Z"
}
```

**Comment by kumarharsh** [comment]
+1. It seems the 4.9.0 build is flaky on Windows. Seems to run fine from command-line, but while running it from vscode (for example), it works on first start, but on subsequent restarts of the editor, the plugin never connects to the watchman server.

```
2017-09-12T11:38:48,952: [cli] unable to talk to your watchman on \\.\pipe\watchman-kumar! (Invalid argument)
```

**Comment by kumarharsh** [comment]
@wez seems to be the same in 4.9.1

**Comment by wez** [comment]
I believe that we root-caused and fixed this in 650f39d2ae188000eda17b7d2c56d4b4f6ce984f  (and introduced an issue that got fixed in ddceae9b7e498286a9c131f4943abc8ef470b311).  Can you try the latest build from appveyor? https://ci.appveyor.com/project/wez/watchman/build/job/epl3mue1cf868dpc/artifacts

**Comment by benpeart** [comment]
I'm seeing _much_ improved behavior of Watchman with today's build.  I'm not seeing the pipe errors, perf is hovering between 5% and 10% of the CPU, and, so far, I'm not seeing it cause the git test suite to fail due to holding handles to files and folders.

**Comment by wez** [comment]
I'm going to call this one done, thanks for working through it with me!
