### ISSUE TITLE
Failed to create state directory on startup on Windows

### ISSUE THREAD

**Issue by indygreg** [facebook/watchman#510]
At https://bugzilla.mozilla.org/show_bug.cgi?id=1385380, a user is seeing an error message running `watchman.exe version`: `failed to create /tmp\kats-state: Not a directory`.

Apparently the user doesn't have any environment variables related to temporary directories set. Yes, this is a bit wonky and their environment is likely buggy. However, main.cpp is currently falling back to `/tmp` on Windows (`watchman_tmp_dir = get_env_with_fallback("TMPDIR", "TMP", "/tmp");`). The use of `/tmp` as a default path name on Windows is not ideal and is likely causing this failure. IIRC `/tmp` will likely get translated to `c:\tmp`, which most likely doesn't exist. We'll likely want the default to be `%LOCALAPPDATA%\Temp` (at least for modern versions of Windows).

**Comment by wez** [comment]
We should probably do something with `GetTempPath` to resolve the appropriate temp path to use on windows

**Comment by BryanCrotaz** [comment]
Agree - env variable is not the right way to get temp path on windows:

https://msdn.microsoft.com/en-us/library/windows/desktop/aa364992(v=vs.85).aspx

**Comment by wez** [comment]
Should finally be resolved by https://github.com/facebook/watchman/commit/74797da25b0aba18d4558d270244450ab3747be4
