### ISSUE TITLE
[packager] Hangs on: `index.ios.js` [development, non-minified, hmr disabled] 0%

### ISSUE THREAD

**Issue by joshuakelly** [facebook/watchman#511]
Please see this issue for react-native. Seems to be related to watchman.

https://github.com/facebook/react-native/issues/15332

**Comment by wez** [comment]
There's not a lot of information in this or the linked report.  

Please run through https://facebook.github.io/watchman/docs/troubleshooting.html

and report back with the version of watchman that you are using (`watchman version`) and provide your watchman log file.

**Comment by dluksza** [comment]
I've tested this with watchman 4.7.0 and 4.9.0, both versions are affected.

**Comment by danielfarrell** [comment]
Running `launchctl unload -F $HOME/Library/LaunchAgents/com.github.facebook.watchman.plist` fixed this problem for me locally.  Just FYI.

**Comment by dluksza** [comment]
@danielfarrell, thanks! this also fiexed this issue for me

**Comment by xiaoDC** [comment]
@danielfarrell this way does work! Thank you!

**Comment by wez** [comment]
based on @danielfarrell's workaround, can I assume that those of you that were affected by this were previously running watchman version < 4.8?

**Comment by danielfarrell** [comment]
I keep it up to date with brew and am still on 4.7.0.

**Comment by ilovezfs** [comment]
8% of users are passing `--HEAD` so we cannot necessarily rule out that some users were coming from >= 4.8.0-rc1, but, yes, the stable spec is still 4.7.0.

**Comment by wez** [comment]
ok, then this is my fault for not officially bumping the homebrew spec to 4.8 yet.  Sorry!

@ilovezfs: I think we're going to need to reinstate that workaround in the homewbrew recipe until I bump the version and folks have migrated to it.  I'm going tag 4.9 by the end of next week; I ran out of bandwidth to do the 4.8 public tag, so homebrew will go from 4.7 -> 4.9.

**Comment by ilovezfs** [comment]
@wez reinstated in https://github.com/Homebrew/homebrew-core/pull/16380.

**Comment by wez** [comment]
Thanks!

**Comment by krischow** [comment]
Having the same issue after updated watchman by brew. Thanks @danielfarrell !

**Comment by dmackinn** [comment]
Another thanks to @danielfarrell you saved my bacon. Had this same issue with 4.7.0

**Comment by wez** [comment]
This should have been taken care of when 4.9 got rolled to homebrew recently, so I'm closing this out.
