### ISSUE TITLE
Homebrew Watchman (4.7.0_1) Breaks Jest

### ISSUE THREAD

**Issue by ecbrodie** [facebook/watchman#512]
I think the latest version of Watchman available for download on Homebrew (I'm using MacOS 10.12.5) is breaking my ability to run my test suite using Jest. I will run a `jest` command and the command will hang indefinitely without any feedback. Even using `--verbose` will not print any information. Jest will work if I pass in the `--no-watchman` flag or I uninstall Watchman from my system. This also means that I can no longer test in watch mode using `jest --watch`.

My hunch is that the latest pushes to the [Watchman Homebrew formula](https://github.com/Homebrew/homebrew-core/blob/master/Formula/watchman.rb) (2 days before time of writing this issue) has caused some sort of MacOS breakage. Unsure if it is due to another Homebrew package I have installed or if there is some incompatibility with MacOS that has not been accounted for. Regardless, this is a concerning issue for me, losing my ability to run tests in watch made.

**Comment by ecbrodie** [comment]
I just tried to install the HEAD version from Homebrew, via `brew install --HEAD watchman`. I am still running into the same issue.

**Comment by wez** [comment]
try the solution from here:

https://github.com/facebook/watchman/issues/511#issuecomment-319764222

**Comment by ecbrodie** [comment]
Oh noes, I deleted that file in my attempts to unblock myself from this issue (pulls hair)

**Comment by ecbrodie** [comment]
Okay, I confirm that it is functioning well again after I restarted my computer. Thanks @wez . Should the Homebrew formula delete and unload that launchctl file automatically?

**Comment by wez** [comment]
Yeah, it was doing that, but the code to do that got removed from the homebrew recipe a couple of days ago.  We'll get this straightened out.  I'm going to close this issue in favor of #511 so that we have fewer places to track this issue.

**Comment by ecbrodie** [comment]
Sounds good, thanks
