### ISSUE TITLE
watchman doesn't build because of error in stat.c

### ISSUE THREAD

**Issue by Nomis101** [facebook/watchman#515]
I've tried to install watchman via Macports, which didn't work because of an error. Than I've downloaded the source and tried to build and install it manually, same error. The error is:

> CC       root/watchman-warnerr.o
> root/stat.c:188:13: error: logical not is only applied to the left hand side of
>       this bitwise operator [-Werror,-Wlogical-not-parentheses]
>         if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
>             ^                         ~
> root/stat.c:188:13: note: add parentheses after the '!' to evaluate the bitwise
>       operator first
>         if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
>             ^
>              (                                                            )
> root/stat.c:188:13: note: add parentheses around left hand side expression to
>       silence this warning
>         if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
>             ^
>             (                        )
> 1 error generated.
> make[1]: *** [root/watchman-stat.o] Error 1
> make[1]: *** Waiting for unfinished jobs....
> make: *** [all] Error 2

This is on macOS 10.13 (17A315i) and Xcode 9 beta.

**Comment by wez** [comment]
We don't maintain the macports port, so I don't know much about what is going on there.  I recommend using homebrew to install watchman on macOS.

You can pass the `--enable-lenient` flag to configure to prevent warnings from being promoted to errors and that should let you make progress if you want to compile the code for yourself.

**Comment by Nomis101** [comment]
Thanks, but homebrew gives me the same error. I can fix the warning/error if I change the specific line in stat.c to
`if ((!root->watcher_ops->flags) & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {`

**Comment by wez** [comment]
FWIW, this issue was fixed months ago, but we haven't tagged a release in a while.  We're running through the steps for that today.

**Comment by wez** [comment]
this should get rolled out to homebrew in the next day or so:
https://github.com/Homebrew/homebrew-core/pull/16547
