### ISSUE TITLE
error in 4.9.0 on Windows

### ISSUE THREAD

**Issue by BryanCrotaz** [facebook/watchman#519]
Works perfectly for a while, then starts emitting errors. Only way to fix is to reboot.

Windows 10, using ember 2.13.2 which uses watchman.
Also noticed thousands of watchman processes running

```
Error: watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2017-08-17T17:40:24,577: [cli] unable to talk to your watchman on \\.\pipe\watchman-Owner! (Invalid argument)

    at ChildProcess.<anonymous> (C:\projects\sc-pp-frontend\node_modules\fb-watchman\index.js:198:18)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:877:16)
    at Socket.<anonymous> (internal/child_process.js:334:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:498:12)
```

**Comment by wez** [comment]
Can you share your watchman logs?  You should be able to find them at: `%TEMP%\%USERNAME%-state\log`

**Comment by BryanCrotaz** [comment]
[log - Copy.txt](https://github.com/facebook/watchman/files/1232345/log.-.Copy.txt)
[state - Copy.txt](https://github.com/facebook/watchman/files/1232346/state.-.Copy.txt)

**Comment by BryanCrotaz** [comment]
after multiple errors:
[log - Copy.txt](https://github.com/facebook/watchman/files/1232357/log.-.Copy.txt)
[state - Copy.txt](https://github.com/facebook/watchman/files/1232358/state.-.Copy.txt)

**Comment by wez** [comment]
it looks like multiple copies of the server are all starting up at the same time.  That shouldn't be possible as we do some locking/checking that should prevent that sort of thing, but bugs happen.  If ember is concurrently initiating watches for a couple of things at basically the same time then we might see this sort of behavior.

What I'd suggest is shutting down your ember app and also watchman (I believe that something like `taskkill /IM watchman.exe /F` should kill all watchman proccesses) then:

Run `watchman watch-project c:/projects/sc-pp-frontend` to launch the server and start watching your project.

Wait for that to return before you start up your ember app.

Hopefully you'll see things behave more rationally.  If you can confirm that this resolves the issue then we'll re-title it to reflect a startup/locking race condition.

**Comment by BryanCrotaz** [comment]
Are you using a global mutex as a lock, or a file system object?

**Comment by wez** [comment]
One thing that we can't see from the logs is whether the original watchman process is still running when the others start up.  I wonder if it is terminating; something must be triggering the server processes to get spawned.  It would be great if you could make a note of the process id from the stable portion and then see if that is still running when things go awry.

**Comment by BryanCrotaz** [comment]
I've certainly seen a few thousand processes running simultaneously after getting errors

**Comment by BryanCrotaz** [comment]
Your suggestion didn't fix it

**Comment by BryanCrotaz** [comment]
After this failure I only have one watchman

**Comment by BryanCrotaz** [comment]
Ran again, failed. 
Watchman process was not restarted. It's running at 10% CPU which seems excessive

**Comment by wez** [comment]
I wonder if there are two different issues for you?  

One is the error surfaced in ember, and the other is the concurrent server processes?

It sounds like you're not seeing the latter any more, so we need to focus on the former.

This command will generate a ton of debug logging; can you leave this running until you replicate the error in ember, then compress and share the logs?

```
watchman --server-encoding=json --persistent log-level debug > debuglogs.txt
```

Take care that debuglogs.txt is **not** under the `sc-pp-frontend` dir, or you'll create a feedback loop as the log files is written to!

**Comment by wez** [comment]
We fixed a number of things since this was opened, and it's been a while since we heard from you, so I'm closing this out.
