### ISSUE TITLE
macport does not declare the pkgconfig as a dependency

### ISSUE THREAD

**Issue by jsg2021** [facebook/watchman#523]
Tried updating to 4.9.0, and configure failed. So, tried cloning the repo & building from source... autogen failed telling me it couldn't find 'pkg-config'... had a hunch, and installed the pkgconfig port, then tried to install watchman again through macports and it installed successfully.

**Comment by wez** [comment]
Can you file an issue with the macports folks?  We don't directly maintain that port

**Comment by jsg2021** [comment]
ok
