### ISSUE TITLE
Update docs to indicate that v4.9.0 is the current release

### ISSUE THREAD

**Issue by misbell** [facebook/watchman#536]
root/stat.c:188:13: note: add parentheses around left hand side expression to
      silence this warning
        if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
            ^
            (                        )
1 error generated.
make[1]: *** [root/watchman-stat.o] Error 1
make: *** [all] Error 2
michaels-MacBook-Pro-Early-2015:watchman michaelisbell$ sudo make
Password:
/Applications/Xcode.app/Contents/Developer/usr/bin/make  all-am
  CC       root/watchman-stat.o
root/stat.c:188:13: error: logical not is only applied to the left hand side of
      this bitwise operator [-Werror,-Wlogical-not-parentheses]
        if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
            ^                         ~
root/stat.c:188:13: note: add parentheses after the '!' to evaluate the bitwise
      operator first
        if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
            ^
             (                                                            )
root/stat.c:188:13: note: add parentheses around left hand side expression to
      silence this warning
        if (!root->watcher_ops->flags & WATCHER_HAS_PER_FILE_NOTIFICATIONS) {
            ^
            (                        )
1 error generated.
make[1]: *** [root/watchman-stat.o] Error 1

**Comment by wez** [comment]
You're building an old version of watchman.  v4.9.0 is the current release.

**Comment by wez** [comment]
I see that our docs don't reflect this; we'll get those fixed and pushed.  In the meantime:

```
git checkout v4.9.0
```

and then retry your build!

**Comment by wez** [comment]
Also: since you're on the mac, I'd recommend using homebrew to install/update watchman

**Comment by misbell** [comment]
thanks everyone, using brew now as recommended. all is well.
