### ISSUE TITLE
compile watchman (macOS)

### ISSUE THREAD

**Issue by GanLuo96214** [facebook/watchman#545]
```
> ./autogen.sh
pkg-config appears to be missing (not available to autoconf tools)
please install the pkg-config package for your system.
```

```
> pkg-config --version
0.28
```

**Comment by GanLuo96214** [comment]
```
> pkg-config --version
0.28
```

**Comment by wez** [comment]
Sorry for the very late response, but it sounds like you don't have autoconf/automake/libtool correctly installed.

We recommend using brew to install watchman on macOS.   We have some instructions here on building from source:

https://facebook.github.io/watchman/docs/install.html#installing-from-source

I'm closing this issue as it has been open for a very long time without any action, so I suspect that you've already moved on.

**Comment by mderrick** [comment]
@GanLuo96214 did you solve this? I have the exact same issue and I cannot use brew due to various reasons.

**Comment by 5elfle5** [comment]
I am trying to use react-native cli, it requires watchman, and it is not satisfied with up-to-date version, it needs older version. For some reason, the version is not available in brew. Now, I am trying to compile watchman from source, and I have this problem, that ganluo960214 described in the original question. Mr. wez's answer is "use brew to install watchman" and he closed the ticket. Fucking burn in hell!

**Comment by An1mus** [comment]
I have the same issue while working with an older version of ember.
It seems I need to use watchman v4.9.0

I follow all the necessary instructions, along with installing pkg-config(which is present), but still, getting this error.
What can be done?

**Comment by KennanChan** [comment]
I have the same issue while installing watchman with homebrew on macOS Monterey 12.1.
I have pkg-config@0.29.2 installed on my machine 

> pkg-config --version
0.29.2

but still got a error saying:

> pkg-config appears to be missing (not available to autoconf tools)
please install the pkg-config package for your system.

Here's the log of autogen.sh

> 2022-01-19 09:33:24 +0800
>
> ./autogen.sh./autogen.sh
>
> glibtoolize: putting auxiliary files in '.'.
glibtoolize: linking file './ltmain.sh'
glibtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
glibtoolize: linking file 'm4/libtool.m4'
glibtoolize: linking file 'm4/ltoptions.m4'
glibtoolize: linking file 'm4/ltsugar.m4'
glibtoolize: linking file 'm4/ltversion.m4'
glibtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:22: installing './compile'
configure.ac:3: installing './config.guess'
configure.ac:3: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
pkg-config appears to be missing (not available to autoconf tools)
please install the pkg-config package for your system.
>
> HOMEBREW_VERSION: 3.0.11
ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/brew.git
HEAD: 8e11f03fa93b148e26044a331654241a2c307039
Last commit: 10 months ago
Core tap ORIGIN: https://mirrors.tuna.tsinghua.edu.cn/git/homebrew/homebrew-core.git
Core tap HEAD: cf8424d2a48ffc9dd41510d6d40c86375fb4aae3
Core tap last commit: 10 months ago
Core tap branch: master
HOMEBREW_PREFIX: /usr/local
HOMEBREW_CASK_OPTS: []
HOMEBREW_DISPLAY: /private/tmp/com.apple.launchd.vt2uBZtR9z/org.macosforge.xquartz:0
HOMEBREW_MAKE_JOBS: 8
HOMEBREW_NO_BOOTSNAP: set
Homebrew Ruby: 2.6.8 => /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/bin/ruby
CPU: octa-core 64-bit kabylake
Clang: 13.0 build 1300
Git: 2.30.0 => /usr/local/bin/git
Curl: 7.77.0 => /usr/bin/curl
macOS: 12.1-x86_64
CLT: 13.2.0.0.1.1638488800
Xcode: 13.2.1
XQuartz: 2.7.11 => /opt/X11
>
> HOMEBREW_CC: clang
HOMEBREW_CXX: clang++
MAKEFLAGS: -j8
CMAKE_PREFIX_PATH: /usr/local/opt/openssl@1.1:/usr/local/opt/readline:/usr/local/opt/sqlite:/usr/local
CMAKE_INCLUDE_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Headers
CMAKE_LIBRARY_PATH: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk/System/Library/Frameworks/OpenGL.framework/Versions/Current/Libraries
CMAKE_FRAMEWORK_PATH: /usr/local/opt/python@3.9/Frameworks
PKG_CONFIG_PATH: /usr/local/opt/openssl@1.1/lib/pkgconfig:/usr/local/opt/pcre/lib/pkgconfig:/usr/local/opt/readline/lib/pkgconfig:/usr/local/opt/sqlite/lib/pkgconfig:/usr/local/opt/xz/lib/pkgconfig:/usr/local/opt/python@3.9/lib/pkgconfig
PKG_CONFIG_LIBDIR: /usr/lib/pkgconfig
HOMEBREW_GIT: git
HOMEBREW_SDKROOT: /Library/Developer/CommandLineTools/SDKs/MacOSX.sdk
ACLOCAL_PATH: /usr/local/share/aclocal
PATH: /usr/local/Homebrew/Library/Homebrew/shims/mac/super:/usr/local/opt/autoconf/bin:/usr/local/opt/automake/bin:/usr/local/opt/libtool/bin:/usr/local/opt/pkg-config/bin:/usr/local/opt/openssl@1.1/bin:/usr/local/opt/pcre/bin:/usr/local/opt/gdbm/bin:/usr/local/opt/sqlite/bin:/usr/local/opt/xz/bin:/usr/local/opt/python@3.9/bin:/usr/bin:/bin:/usr/sbin:/sbin

**Comment by dot-mike** [comment]
Also facing this issue. Someone got a solution?

**Comment by xgenem** [comment]
`brew install watchman` on Ubuntu seems the easiest
