### ISSUE TITLE
Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/2), failed. TypeError: Right-hand side of 'instanceof' is not an object

### ISSUE THREAD

**Issue by arifmahfudin** [facebook/watchman#547]
I run react native project using windows. 
react-native-cli: 2.0.1
react-native: 0.48.2
Node -v v8.5.0
npm version 5.3.0

APK can installed, but have problem
`Bundling `index.android.js`  [development, non-minified, hmr disabled]  0.0% (0/2), failed. TypeError: Right-hand side of 'instanceof' is not an object`

Is anyone have the same problem? how fix this problem?
Thanks

**Comment by wez** [comment]
You probably want to report this to the react native project?  It doesn't sound like it could be related to watchman.
