### ISSUE TITLE
bash: ./configure: No such file or directory getting when  ./configure run in terminal

### ISSUE THREAD

**Issue by habeebrahmanpt** [facebook/watchman#551]
xxxxxxxxxxx:/home/watchman$ ./configure
bash: ./configure: No such file or directory

**Comment by wez** [comment]
Please follow the instructions here:
https://facebook.github.io/watchman/docs/install.html#installing-from-source

**Comment by itarafath** [comment]
same issue,not fixed yet

**Comment by msmaromi** [comment]
After  i ran `./autogen.sh` the second time, the `configure` file was appear

**Comment by customcommander** [comment]
I had a similar issue but then I looked closer to the output of `./autogen.sh`:

```
/var/watchman # ./autogen.sh 
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
configure.ac:22: installing './compile'
configure.ac:3: installing './config.guess'
configure.ac:3: installing './config.sub'
configure.ac:4: installing './install-sh'
configure.ac:4: installing './missing'
Makefile.am: installing './depcomp'
parallel-tests: installing './test-driver'
pkg-config appears to be missing (not available to autoconf tools)
please install the pkg-config package for your system.
```

Last line says that I was missing a package. In my case all I had to do was to install `pkgconfig` on my system (Alpine):

```
apk add pkgconfig
```

YMMV of course.

**Comment by ronn** [comment]
Possible errors:

1. While running ./autogen.sh 
Error: your system lacks libtoolize
Solution: sudo apt-get install libtool

After that, "./configure" worked! :)

Source: https://medium.com/@saurabh.friday/install-watchman-on-ubuntu-18-04-ba23c56eb23a
