### ISSUE TITLE
Use newer runtime or statically link the CRT or distribute it with watchman

### ISSUE THREAD

**Issue by indygreg** [facebook/watchman#552]
Watchman Windows builds currently require a shared library dependency against msvcr120.dll (MSVC 2013).

Would it be possible to do a dynamic link against the universal CRT (which is part of Windows 10)? (I think this requires switching to MSVC 2015.)

If sticking with MSVC 2013 is desired, could the CRT be statically linked so as to not incur the shared library dependency? Or, could the watchman binary distribution include a copy of msvcr120.dll so end-user machines don't need a previous install of the runtime to run watchman.exe?

**Comment by indygreg** [comment]
Oh, I didn't check with a recent build. I'm just reporting issues that were reported at Mozilla. Perhaps we didn't pick up a recent enough watchman build...

**Comment by wez** [comment]
I'm going to assume that we did the right thing with this and close out this issue.  You know where to find me if I'm wrong :-)
