### ISSUE TITLE
Package, distribute, and update for Linux

### ISSUE THREAD

**Issue by HideDev** [facebook/watchman#563]
It would be good to use https://snapcraft.io/

**Comment by wez** [comment]
When it comes to packaging and distribution, our stance is that we cannot do a good job at supporting different flavors of linux on our own, so we prefer to work with a maintainer from the distribution that is committed to supporting the package on that system.  That way the users get the best possible experience.  Without having someone in that role we'd prefer not to just throw a packaging script over the wall and let it rot.

In addition, the snap deployment system sounds like it isolates the package from the rest of the system; that doesn't really fit the spirit of a developer infrastructure service such as watchman.

So, snapcraft doesn't sound like it would be a great fit.

Is there a specific issue that you have that you thought that this might solve?

**Comment by listepo** [comment]
Snapcraft supports the most popular linux distributions and is a universal solution.

**Comment by wez** [comment]
I'm not convinced that this is an appropriate way to deploy and use watchman (it's a service and not an isolated app) so I'm going to close this out.  If someone puts in some legwork to try this out I'd be happy to review it and see if it is suitable, but for now this feels like it adds unwanted overheads and isn't something that we want to spend cycles on internally at this time.
