### ISSUE TITLE
Directory noted as modified when creating files, but not when deleting files

### ISSUE THREAD

**Issue by jcea** [facebook/watchman#566]
Ubuntu 16.04, watchman 4.9.0, inotify.

Testcase:

1. Create directory `/tmp/z/z`

2. Execute this code:

    #!/usr/bin/env python3

    import pathlib
    import pywatchman

    w = pywatchman.client()
    w.query('watch', '/tmp/z')
    clock = w.query('clock', '/tmp/z')['clock']
    w.query('subscribe', '/tmp/z', 'test', {'since': clock})

    f = pathlib.Path('/tmp/z/z/q')

    print('Create file')
    f.touch()
    print(w.receive())

    print('Delete file')
    f.unlink()
    print(w.receive())

What I see:

    $ ./watchman-bug.py 
    Create file
    {'unilateral': True, 'subscription': 'test', 'root': '/tmp/z', 'files': [{'name': 'z', 'exists': True, 'new': False, 'size': 4096, 'mode': 16877}, {'name': 'z/q', 'exists': True, 'new': True, 'size': 0, 'mode': 33188}], 'is_fresh_instance': False, 'version': '4.9.0', 'since': 'c:1517253834:3333:3:28', 'clock': 'c:1517253834:3333:3:29'}
    Delete file
    {'unilateral': True, 'subscription': 'test', 'root': '/tmp/z', 'files': [{'name': 'z/q', 'exists': False, 'new': False, 'size': 0, 'mode': 33188}], 'is_fresh_instance': False, 'version': '4.9.0', 'since': 'c:1517253834:3333:3:29', 'clock': 'c:1517253834:3333:3:30'}

Note that when I create the file, I get a notification with two events: file creation and directory update. GOOD.

When I delete the file, I only get an event: file deletion. I don't get the directory update.

Thanks for your time!.

**Comment by wis** [comment]
i'm having the same issue same issue. I move the file to a parent directory of the watched directory and no trigger, move the file back and there's a trigger.

**Comment by wez** [comment]
Fixed in https://github.com/facebook/watchman/commit/4388b3d5e87d9766e905438e0f3311a5a2ff826c
