### ISSUE TITLE
failed to install on 32 bit window 7

### ISSUE THREAD

**Issue by BittuBushera** [facebook/watchman#567]
i have download the watchman setup from  : - "https://facebook.github.io/watchman/docs/install.html" from : - Download latest watchman.zip file .
it download successfully but at installation time it showing error as your system is not compatible with this version.
For information - i am using window 7 32 bit 
Please suggest me for  help

**Comment by wez** [comment]
We only build binaries for 64-bit Windows systems.  32-bit Windows is not a priority for us, but if someone in the community were to submit a pull request for the windows build and appveyor configuration that also built out 32-bit binaries, we'd take it.
