### ISSUE TITLE
Failed to install on Debian 9

### ISSUE THREAD

**Issue by sergibondarenko** [facebook/watchman#568]
System
```
Linux version 4.9.0-5-amd64 (debian-kernel@lists.debian.org) (gcc version 6.3.0 20170516 (Debian 6.3.0-18) ) #1 SMP Debian 4.9.65-3+deb9u2 (2018-01-04)
```
I install from source by following [the official instructions](https://facebook.github.io/watchman/docs/install.html#installing-from-source).

On executing `./autogen.sh && ./configure && make` I get the following error:
```
rm: cannot remove 'watchman': Is a directory
Makefile:1566: recipe for target 'watchman' failed
make[1]: *** [watchman] Error 1
make[1]: Leaving directory '/home/trex/Downloads/watchman'
Makefile:1101: recipe for target 'all' failed
make: *** [all] Error 2
```
PS
Tried both v4.9.0 and v4.9.0-rc1 tags.

**Comment by wez** [comment]
Sounds like you accidentally extracted or cloned watchman inside an existing watchman clone, because that doesn't happen by default!

I'd suggest removing the watchman dir and starting again.

**Comment by aweeraman** [comment]
Watchman is now also available in Debian and Ubuntu and can be installed via 'apt-get install watchman'.
