### ISSUE TITLE
Compile Error due to InlineExecutor

### ISSUE THREAD

**Issue by xin-jin** [facebook/watchman#573]
`make` gives an error:
```
cppclient/WatchmanConnection.cpp:10:42: fatal error: folly/futures/InlineExecutor.h: No such file or directory
```

I installed the latest folly. It seems that `InlineExecutor` has been moved to `folly/executors'?

**Comment by wez** [comment]
This is probably way too late to be helpful to you, but folly moves very quickly and you will need to use the master branch from approximately the same time as the folly version you are using to be sure that things work correctly; internally, the folly change that moved those headers took care of updating the watchman code.  Those portions of the repo are synced out separately to their corresponding github repos.
