### ISSUE TITLE
The specified blob does not exist

### ISSUE THREAD

**Issue by artem-solovev** [facebook/watchman#583]
[Link](https://appveyorcidata.blob.core.windows.net/wez-25370/watchman/b1540/celdwkash6w3ahuj/watchman.zip?sv=2015-12-11&sr=c&sig=j1K44OWABckOKKI%2BB9%2B%2BM6%2FIzv8YCJbDE3WtYfTIT%2FE%3D&st=2018-03-12T13%3A26%3A52Z&se=2018-03-12T13%3A32%3A52Z&sp=r)
`<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:da146cd5-501e-003c-5a05-ba0e3f000000 Time:2018-03-12T13:27:52.7957324Z
</Message>
</Error>`

**Comment by AdrianoCahete** [comment]
This is working: https://ci.appveyor.com/api/buildjobs/41p1lupk97crwvm0/artifacts/watchman.zip

**Comment by artem-solovev** [comment]
@AdrianoCahete thank you but why it doesn't work [here ](https://facebook.github.io/watchman/docs/install.html#download-for-windows-beta)

**Comment by AdrianoCahete** [comment]
In Docs, the link is the same as the first link on this issue.

I opened a PR now fixing that, but this PR needs to be reviewed by Facebook Team.

**Comment by wez** [comment]
this is the correct link:

https://ci.appveyor.com/api/projects/wez/watchman/artifacts/watchman.zip?branch=master&job=Environment:+WATCHMAN_WIN7_COMPAT%3D&pr=false
