### ISSUE TITLE
libssl-dev dependency missing from "install from source" directions

### ISSUE THREAD

**Issue by jsedgwick** [facebook/watchman#585]
Following the directions at https://facebook.github.io/watchman/docs/install.html#installing-from-source, I ran into a compile error at the make step looking for OpenSSL headers. I installed libssl via `sudo apt-get install libssl-dev` and everything worked. This is on Ubuntu 16.04.

Just an FYI to check the instructions at some point and make sure all the Linux deps are there. There may have been others besides libssl headers that aren't listed in the instructions that I just happened to already have. This probably should have failed at `./configure` right?

(p.s. Hi @wez !)

**Comment by wez** [comment]
Thanks @jsedgwick; I just pushed an admittedly terse mention of this to the web site
