### ISSUE TITLE
Can't create temp file "wmana#####"

### ISSUE THREAD

**Issue by Pysis868** [facebook/watchman#590]
Haven't seen this error anywhere on the web yet.
```
==> /cygdrive/c/Users/Username/AppData/Local/Temp/Username-state/log <==
2018-03-25T22:32:00,380: [trigger echo C:/.../topfolder] input_json: sending json object to stm
2018-03-25T22:32:00,529: [trigger echo C:/.../topfolder] unable to create a temporary file: C:\Users\Username\AppData\Local\Temp/wmana30692 Permission denied
2018-03-25T22:32:00,529: [trigger echo C:/.../topfolder] trigger C:/.../topfolder:echo Permission denied
[{"name":"folder1/folder2/folder3/file1","size":133,"exists":true,"new":true,"mode":33206},{"name":"folder1/folder2/folder3/file2","size":9943,"exists":true,"new":true,"mode":33206},{"name":"folder1/folder2/folder3/file3","size":65584,"exists":true,"new":true,"mode":33206},{"name":"folder1/folder2/folder3","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1/folder2","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1","size":0,"exists":true,"new":true,"mode":16895}]
2018-03-25T22:32:06,367: [trigger echo C:/.../topfolder] input_json: sending json object to stm
2018-03-25T22:32:06,421: [trigger echo C:/.../topfolder] unable to create a temporary file: C:\Users\Username\AppData\Local\Temp/wmana30692 Permission denied
2018-03-25T22:32:06,421: [trigger echo C:/.../topfolder] trigger C:/.../topfolder:echo Permission denied
[{"name":"folder1/folder2/folder3/file1","size":133,"exists":true,"new":false,"mode":33206},{"name":"folder1/folder2/folder3/file2","size":9943,"exists":true,"new":false,"mode":33206},{"name":"folder1/folder2/folder3/file3","size":65584,"exists":true,"new":false,"mode":33206},{"name":"folder1/folder2/folder4/folder5","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1/folder2/folder4/folder5","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1/folder2/folder4","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1/folder2","size":0,"exists":true,"new":false,"mode":16895}]
2018-03-25T22:32:09,884: [trigger echo C:/.../topfolder] input_json: sending json object to stm
[{"name":"folder1/folder2/folder3/file2","size":9943,"exists":true,"new":false,"mode":33206},{"name":"folder1/folder2/folder3/file3","size":65584,"exists":true,"new":false,"mode":33206},{"name":"folder1/folder2/folder3/file1","size":133,"exists":true,"new":false,"mode":33206}]
```

That prefix also does not appear in the codebase.
I can understand where the "wm" comes from (WatchMan), if that is true, but haven't found the code that does it yet.
The number suffix seems to only change between server restarts, but it does not seem related to the PID.
I'm using Windows 10 Pro 64-bit, with ConEmu and watchman 4.9.1.
I have Cygwin and bash, and would like to use those in the future, but I am trying to simplify the situation by using the default expected situation, so at least Windows Command Prompt (still with ConEmu :) ).

Not sure what the problem is, so I have tried various things such as running the process from an elevated prompt both that way, and marking the compatibility attribute for all users to run it as administrator.  I verified this with Process Explorer viewing all process information by elevating itself, and seeing the process owned by the Administrator group.  Also non-privileged prompts got an E_ACCESS violation when trying to run the executable at that point.

I have done multiple runs where I had later given it the `shutdown-server` command, cleared all of the "<Username>-State" directories I could find, have been following all of their logs with `tail -F ...`, and starting it with `version`.  I can see the process start up, even when running Process Explorer in unprivileged mode.  Sometimes I the trigger has been simply created, and other times replaced.

I was using a heavy process to replicate them, but found all I needed to do was copy a folder with some files, or even a single file, inside of the watched directory.  Creating the folder directly with `mkdir`, and copying the files over individually, did not cause the error.

Maybe this is triggered within the settle period, since the item events do seem to be emitted in a batch array of JSON objects when the error occurs.  I do believe there are some entires that are missing, say, when I copied a folder of 6 files over, I was only find 3 or 4 of them in the log.

Since the error message showed mixed-slash-style paths, I tried setting the environment variables manually to use forward slashes, but that didn't help.

```
Username@HOSTNAME C:\Users\Username
$ echo %TMP%
C:\Users\Username\AppData\Local\Temp

Username@HOSTNAME C:\Users\Username
$ echo %TEMP%
C:\Users\Username\AppData\Local\Temp

Username@HOSTNAME C:\Users\Username
$ echo %TMPDIR%
%TMPDIR%

Username@TEHFISHYBEAST C:\Users\Username
$ set TMP=C:/Users/Username/AppData/Local/Temp

Username@TEHFISHYBEAST C:\Users\Username
$ set TEMP=C:/Users/Username/AppData/Local/Temp

Username@TEHFISHYBEAST C:\Users\Username
$ echo %TMP%
C:/Users/Username/AppData/Local/Temp

Username@TEHFISHYBEAST C:\Users\Username
$ echo %TEMP%
C:/Users/Username/AppData/Local/Temp
```
```
==> /cygdrive/c/Users/Username/AppData/Local/Temp/Username-state/log <==
2018-03-25T23:42:34,964: [trigger echo C:/.../topfolder] input_json: sending json object to stm
2018-03-25T23:42:35,023: [trigger echo C:/.../topfolder] unable to create a temporary file: C:/Users/Username/AppData/Local/Temp/wmana06612 Permission denied
2018-03-25T23:42:35,023: [trigger echo C:/.../topfolder] trigger C:/.../topfolder:echo Permission denied
[{"name":"folder1/folder3","size":0,"exists":true,"new":true,"mode":16895},{"name":"folder1/folder3/file1","size":133,"exists":true,"new":true,"mode":33206},{"name":"folder1/folder3/file2","size":9943,"exists":true,"new":true,"mode":33206},{"name":"folder1/folder3/file3","size":65584,"exists":true,"new":true,"mode":33206},{"name":"folder1","size":0,"exists":true,"new":false,"mode":16895}]
```

Using the command `log-level debug` does not provide any additional information, so that must be the default.

Here are the commands I used.
The path further up has a space in it, and at some lengths can be about 91 characters long.
I had also used custom commands such as `jq -C` and `cat` that worked as well, just except for this temporary file error.

```
...
alternatePath2=".../topfolder";

path="$alternatePath2";
path="$(cygpath -m "$path")";

watchman watch "$path";

watchman -j <<-EOT
["trigger", "$path", {
  "name": "echo",
  "command": ["jq", "-M", "-c", "."],
  "appendFiles": false,
  "stdin": ["name", "exists", "new", "size", "mode"]
}]
EOT

# or

watchman -j <<-EOT
["trigger", "$path", {
  "name": "echo",
  "command": ["cat"],
  "appendFiles": false,
  "stdin": ["name", "exists", "new", "size", "mode"],
  "stdout": ">D:/out.log"
}]
EOT

{
    "version": "4.9.1",
    "watch": "C:/.../topfolder",
    "watcher": "win32"
}
{
    "version": "4.9.1",
    "triggerid": "echo",
    "disposition": "created"
}
```

**Comment by Pysis868** [comment]
It happens in both circumstances.
Also, it does not have an error when copying multiple folders over at the same time, even when some are nested.
It does not happen when I delete multiple files in a folder, only when creating them.

Here are the Process Monitor Results concerning that file:

22:08:21.29 | watchman.exe | 5572 | CreateFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | NAME NOT FOUND | Desired Access: Read Attributes, Disposition: Open, Options: Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a
-- | -- | -- | -- | -- | -- | --
22:08:21.29 | watchman.exe | 5572 | ReadFile | D:\bin\watchmaan\watchman.exe | SUCCESS | Offset: 2,027,520, Length: 16,384, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
22:08:21.29 | watchman.exe | 5572 | CreateFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS | Desired Access: Generic Read/Write, Disposition: OverwriteIf, Options: Synchronous IO Non-Alert, Non-Directory File, Attributes: N, ShareMode: Read, Write, Delete, AllocationSize: 0, OpenResult: Created
22:08:21.29 | watchman.exe | 5572 | CreateFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS | Desired Access: Read Attributes, Delete, Disposition: Open, Options: Non-Directory File, Open Reparse Point, Attributes: n/a, ShareMode: Read, Write, Delete, AllocationSize: n/a, OpenResult: Opened
22:08:21.29 | watchman.exe | 5572 | QueryAttributeTagFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS | Attributes: A, ReparseTag: 0x0
22:08:21.29 | watchman.exe | 5572 | SetDispositionInformationFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS | Delete: True
22:08:21.29 | watchman.exe | 5572 | CloseFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS |  
22:08:21.29 | watchman.exe | 5572 | QueryStandardInformationFile | C:\Users\Username\AppData\Local\Temp\Username-state\log | SUCCESS | AllocationSize: 81,920, EndOfFile: 77,935, NumberOfLinks: 1, DeletePending: False, Directory: False
22:08:21.29 | watchman.exe | 5572 | WriteFile | C:\Users\Username\AppData\Local\Temp\Username-state\log | SUCCESS | Offset: 77,935, Length: 140
22:08:21.29 | watchman.exe | 5572 | ReadFile | D:\bin\watchman\watchman.exe | SUCCESS | Offset: 2,019,328, Length: 8,192, I/O Flags: Non-cached, Paging I/O, Synchronous Paging I/O, Priority: Normal
22:08:21.29 | watchman.exe | 5572 | WriteFile | C:\Users\Username\AppData\Local\Temp\wmana05452 | SUCCESS | Offset: 0, Length: 475, Priority: Normal

**Comment by wez** [comment]
Should be resolved by https://github.com/facebook/watchman/commit/74797da25b0aba18d4558d270244450ab3747be4
