### ISSUE TITLE
make file query relative to "path" option

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#591]
I'm querying a subdirectory of a watched root, and I want the returned file names to be relative to the `path` option instead of the watched root. Is this possible? If not, would you consider a new option?

**Comment by wez** [comment]
Yes, we have a way to do this.  It is admittedly difficult to discover.  I'd be happy to field your questions on it here and feed that back into the docs:

https://facebook.github.io/watchman/docs/file-query.html#relative-roots

**Comment by aleclarson** [comment]
Oh, I didn't make the connection that `relative_root` is used for that. Not sure how I messed up when reading that section. The docs are *probably* clear enough, I just didn't read carefully enough.

Thanks!
