### ISSUE TITLE
Watchman taking up more than 1 GB of RAM

### ISSUE THREAD

**Issue by Hum4n01d** [facebook/watchman#593]
I’m running only Safari, Spotify, and Final Cut Pro on my computer yet it’s extremely slow and laggy.

My laptop is a 2012 MacBook Pro with upgraded 8GB RAM. 

Can somebody explain why watchman is taking up more than a GB of memory when I’m not even using it?

![screen shot 2018-03-28 at 7 06 43 pm](https://user-images.githubusercontent.com/17228477/38066088-53e14ee0-32bb-11e8-8c1b-216cd2e40bbb.png)

**Comment by Hum4n01d** [comment]
Just restarted my computer and watchman is back again with nothing running besides Safari and Spotify 
![screen shot 2018-03-28 at 7 15 38 pm](https://user-images.githubusercontent.com/17228477/38066350-7625ada6-32bc-11e8-91e2-b803dc70d5f2.png)

**Comment by wez** [comment]
Watchman remembers the directories that you asked it to watch.  `watchman watch-list` will show you what it is watching.  `watchman watch-del-all` will cancel all of those watches until you next use a tool that starts a watch up again.

**Comment by Hum4n01d** [comment]
Ok, but I haven’t used watchman directly ever.

**Comment by wez** [comment]
You most likely installed it to do something with React Native.  React Native uses watchman to respond to changes in your project and hot reload them.

**Comment by Hum4n01d** [comment]
Yes, that’s why I installed it. I haven’t used React Native in months though.

**Comment by wez** [comment]
You seem somewhat confrontational about this, and I'm not sure what you want to hear.  If you run the commands that I suggested above, you will reveal what it was watching and be able to stop it.  There are configuration options available to limit the scope of what it is watching that we can explore if you wish to keep using it, and you are certainly free to uninstall the software.

**Comment by Hum4n01d** [comment]
Sorry about my tone, I was pretty frustrated when I discovered this. I will run that command as soon as I can.

**Comment by wez** [comment]
I'll close this out for now; when you have time to work through this, please re-open this issue and we can continue.

**Comment by Hum4n01d** [comment]
Sorry about the big delay. I ran the `watch-list` command to find this:

```
~ watchman watch-list
{
    "version": "4.7.0",
    "roots": [
        "/Users/**redacted**"
    ]
}
```

That explains a lot of memory use. I ran the `watch-del-all` command and the RAM usage went away. 

Thanks @wez!
