### ISSUE TITLE
Maintain separate watch-list for each connection

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#594]
At time of connection, a client should have the option to keep its own `watch-list` separate from other clients. In this scenario, a client would be calling `watch-project` for the user, completely isolating Watchman from the user. Without the ability to keep a separate `watch-list`, the user (or some other client) can trigger strange behavior when sending `watch-del` commands.

Watchman would still consolidate watched roots like normal, but this would be invisible to clients if the ancestor root is not in their unique `watch-list`.

The unique `watch-list` would not persist across reconnections, so the client should save a record of which roots it's watching in case of disconnection or client reboot.

**Comment by wez** [comment]
In general, no tool or automation should be generating `watch-del` calls; those are intended to be for the user to manage because there isn't a reasonable way to any tooling to automatically know when the user wants the watch to go away.  The watchman server can be configured to reap a watch if it has been idle for a while: https://facebook.github.io/watchman/docs/config.html#idle_reap_age_seconds.

Can you tell me more about how you want to apply watchman?  That will help me provide some guidance and understand more about where we might fall short today.

**Comment by aleclarson** [comment]
> there isn't a reasonable way for any tooling to automatically know when the user wants the watch to go away

I disagree. For the user to unwatch a root, they would need to use whichever Watchman client sent the `watch-project` command.

The idea is that the Watchman client acts as the layer between the user and Watchman, completely isolating the two. So the client would send both `watch-project` and `watch-del` commands to maintain its unique `watch-list`. Thus, the client would need to provide a means for the user to watch/unwatch a root.

The unique `watch-list` lets Watchman clients avoid stepping on each other.

**Comment by aleclarson** [comment]
In response to https://github.com/facebook/watchman/issues/595#issuecomment-377798046:

> Non persistent clients rely on the watch being alive and persisted between runs, otherwise there is no performance benefit to be gained. This is a critical function of watchman; without this, source control status calls in very large repos can sometimes take minutes to run! This is one of the reasons that we generally frown upon automated or unilateral use of the watch-del command; a given tool doesn't know which other tools rely on watchman to make things fast by persisting a watch.

The idea of a "detached" `watch-list` avoids this issue of using `watch-project` and `watch-del` as a client. Basically, a root will remain watched as long as it exists in the global `watch-list` (the default) or some detached `watch-list` (designated with some globally unique ID, possibly generated by watchman).

I'm curious if you see issues in this solution. If the owner of the detached `watch-list` is uninstalled, its watched roots will remain watched until reaping occurs. Apart from that minor issue, I haven't thought of anything else.

**Comment by aleclarson** [comment]
Expensive watches are an edge case for most developers, I think. That use case can be improved upon with specialized tooling that splits the expensive watch into semantically meaningful subsets. At the very least, a `timeout` option would prevent unexplained stalling in those cases.

Tooling on top of Watchman is a great way to reduce friction for the majority, abstracting away manual intervention unless absolutely necessary. For example, my library reduces friction by programmatically sending `watch-project` commands when a user wants to watch a root *temporarily* (eg: until some bundler process exits).

Preventing clients from stepping on each other's toes is crucial in abstracting Watchman away from the user, and subscriptions don't fit the bill currently.

Allowing tools to isolate their `watch-list` from other tools (while preserving the benefits of root consolidation between tools) seems to be a step in the right direction, but I'm always open to other ideas!

**Comment by wez** [comment]
What you're proposing introduces massive complexity and is at odds with how watchman works.  I don't think it is necessary though; you can omit the `watch-del` portion of the flow you've been talking about and get the functionality that you want.  You just need to stop worrying about canceling the watch.
