### ISSUE TITLE
Emit an "unwatch" event

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#595]
When a `watch-del` command is sent by a client, other clients should receive an `unwatch` event. The current solution is to periodically send `watch-list` commands and look for removed roots. An `unwatch` event makes it easier to interoperate with other clients, assuming #594 may take a while to implement (or may never be implemented).

**Comment by aleclarson** [comment]
I strongly prefer #594 over this, because this doesn't protect against my client unwatching a root that some other client was using.

**Comment by aleclarson** [comment]
An alternative solution to periodic `watch-list` commands is to create a "base subscription" whenever watching a root. When the subscription is cancelled, you'll know that another client unwatched that root.

**Comment by wez** [comment]
Watchman already generates a `canceled` event if a watch is stopped for any reason.  I described this to you here: https://github.com/facebook/watchman/issues/589#issuecomment-376258832

**Comment by aleclarson** [comment]
@wez From that comment, I understood that a `canceled` event is generated for each subscription, but I'm talking about an event that would be generated even if no subscriptions exist for the deleted root. Am I misunderstanding something?

**Comment by aleclarson** [comment]
Using `subscribe` to detect a `watch-del` works well, but I've found a minor annoyance. If a project directory is deleted from the filesystem, the 'subscription' event has no property to signal that.

Two possible solutions:
- include `deleted: true` in the cancel event
- send a separate 'subscription' event like `{name: '/', ...}` before the cancel event
- make the user create a second subscription that watches the project directory explicitly if they want to know about its deletion

The first solution has the potential to be confusing, since someone may think `deleted` means the subscription was canceled by a `watch-del` command.

The third solution seems a little heavy-handed / inconvenient.

The second solution seems best, but I admit `name: '/'` is strange since other 'subscription' events don't include a leading backslash.
