### ISSUE TITLE
know when a subscription root is deleted

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#608]
Using `subscribe` to detect a `watch-del` works well, but I've found a minor annoyance. If the project directory (aka: the subscription root) is deleted from the filesystem, the 'subscription' event has no property to signal that.

I see 3 possible solutions:
- include `deleted: true` in the cancel event
- send a separate 'subscription' event like `{name: '/', ...}` before the cancel event
- make the user create a second subscription that watches the project directory explicitly if they want to know about its deletion

The first solution has the potential to be confusing, since someone may think `deleted` means the subscription was canceled by a `watch-del` command.

The third solution seems a little heavy-handed / inconvenient.

The second solution seems best, but I admit `name: '/'` is strange since other 'subscription' events don't include a leading backslash.

**Comment by wez** [comment]
Can I ask how you intend to use this information?

There are a few different things that can asynchronously trigger cancellation and we don't currently have a simple way to thread the context through in a consumable fashion.

For the time being I would suggest that you check to see if the root exists for yourself in response to this event.

I would caution against automatically watching in response to a cancellation event, as this is likely going to frustrate the system operator if they are trying to troubleshoot and delete watches.

**Comment by aleclarson** [comment]
> Can I ask how you intend to use this information?

To invalidate a cache.

> For the time being I would suggest that you check to see if the root exists for yourself in response to this event.

Yeah, this is the proper solution. 🙂

**Comment by aleclarson** [comment]
> I would caution against automatically watching in response to a cancellation event, as this is likely going to frustrate the system operator if they are trying to troubleshoot and delete watches.

It's a trade off I'm willing to make, because ensuring resilience of temporary "change streams" lets the user fire-and-forget without the burden of repeating the same rewatch logic for every temporary stream in their codebase. This is all assuming the user always prefers temporary streams to stay alive until manually closed, even if that means breaking the `watch-del` command. How often do users really need to use `watch-del` anyways? I haven't once used it manually.

**Comment by wez** [comment]
Not portably, and it's not even guaranteed that we'll get told about some classes of logical rename or removal; for example, btfs and possibly apfs volume snapshots can appear and disappear in ways that the kernel do not inform about.  I'm inclined to keep this as dumb and simple as possible to minimize the surprise factor of these sorts of things.
