### ISSUE TITLE
jest-haste-map: Watchman crawl failed. Retrying once with node crawler.

### ISSUE THREAD

**Issue by Manoj002** [facebook/watchman#611]
Hello,

Im using expo sdk 27, react 16.3, react native: 0.55.2, npm 
The packager was working fine till yesterday, but this morning it is running into errors, i dont know why...

any help will be appreciated...

**Comment by wez** [comment]
The error message you shared doesn't come from watchman so we in the watchman project don't know what it means.   I'd recommend asking the react native project folks for help in understanding this issue.

The watchman troubleshooting guide can help you with low level watchman issues:
https://facebook.github.io/watchman/docs/troubleshooting.html

Without seeing your log files we don't have any information to go on to troubleshoot this from the watchman side.
