### ISSUE TITLE
make query commands work with unwatched roots

### ISSUE THREAD

**Issue by aleclarson** [facebook/watchman#612]
This would need to be opt-in I'm guessing.

The motivating factor here is the ability to use Watchman's "query language" without needing to establish temporary watch roots.

Watchman would invisibly take advantage of a watch root if the queried directory is one or a descendant of one. Otherwise, the query will take longer, but I'm okay with that.

The results would include a `watch` property that equals the watch root or null.

**Comment by wez** [comment]
We used to do this and removed it; here are some randomly ordered bullet points with context:

*  It is too expensive to spin up the watch on-demand on large repos
* This makes it difficult to manage expectations; should the query timeout after a couple of seconds, or minutes?
* There's no way in the protocol to advise the client that we're now doing something unexpected, so no good way to show progress UI

Forcing the client to explicitly watch-project first ends up being nicer for the end-user at the expense of being a little bit more awkward for the integrator:

* The watch-project call can have an appropriate (longer!) timeout configured around it, and a progress UI can explicit indicate that it is waiting for the project to be made available to watchman
* The query call can have a more reasonable and short timeout configured
* It's clearer to everyone what is going on
