### ISSUE TITLE
Process hang up and high CPU usage using `watch-project` on Mac

### ISSUE THREAD

**Issue by chemzqm** [facebook/watchman#617]
I just tried out watchman by install it from homebrew with `--head` options, is seems that `watch-project` not working, it cost high CPU usage and not responsing.

I tried with command like:
```
watchman watch-project  $PWD
```
and node code
``` js
var watchman = require('fb-watchman')
var client = new watchman.Client();

client.capabilityCheck({optional:[], required:['relative_root']}, function (error, resp) {
  if (error) {
    console.error(error)
    return
  }
  console.log(resp)
  client.command(['watch-project', process.cwd()], function (error, resp) {
    if (error) {
      console.error(error)
      return
    }
    console.log(1)
  })
})
```
`capabilityCheck` works as expected, but the callback never triggered of `watch-project`

**Comment by lodestone** [comment]
I'm not sure if my problem is related or not, but I'm seeing high CPU usage as well. It sits around 10%.

I tried 4.9 from brew and --HEAD from brew also. Same results.

**Details:**

* macOS 10.13.4 (17E202)
* MacBook Pro (Retina, 13-inch, Early 2015)

Doing this from an electron project directory. Medium amount of files, I'd say.

```bash
 watchman -j <<< '["trigger", "./", { "stdin": ["name", "size", "mtime", "atime", "ctime"], "name": "allwatcher", "command": ["/Users/z/in.rb"] }]'
```

**Comment by wez** [comment]
@chemzqm how many files are in the directory you are watching?  Is it being actively modified?  watch-project will block until the directory has been crawled, so if you're trying to watch something large it can take a while to complete.

Please also work through the troubleshooting guide; we'll need to see your log files to be able to start to understand what is happening on your system.  There is additional information in the guide that might help you dig in and resolve this for yourself:

https://facebook.github.io/watchman/docs/troubleshooting.html

**Comment by chemzqm** [comment]
When I run command `watch-list` I got:

```
❯ watchman watch-list

{
    "version": "4.9.0",
    "roots": [
        "/Users/chemzqm"
    ]
}
```
but I didn't tell watchman to watch my home directory, I run watchman command `watchman watch-project $PWD` in a different dictionary.

**Comment by chemzqm** [comment]
Also find that after I use 
```
watchman watch $PWD
```
and then I could use 
```
watchman watch-project $PWD
```
without any trouble, it will not try to watch my home directory anymore.

But if I kill the process and try `watch-project`, it doesn't work again.

**Comment by chemzqm** [comment]
Looks like the issue cause by the `.watchmanconfig` file in my home directory.
`watch-project` use it regard less the existing `.git` folder in the directory command argument.

**Comment by chemzqm** [comment]
Could `fb-watchman` module expose the child process or provide a method so I could kill the watchman process if it's not responsing for some time?
