### ISSUE TITLE
Getting Compiler issue "bytesobject.h: No such file or directory"

### ISSUE THREAD

**Issue by Gobi94** [facebook/watchman#620]
During make we are getting below error while compiling bser.c
pywatchman/bser.c:1124: error: too many arguments to function ‘_pdu_info_helper’
error: command 'gcc' failed with exit status 1
make[1]: *** [py-build] Error 1
make[1]: Leaving directory `/opt/watchman-master'
make: *** [all] Error 2
Please help

**Comment by wez** [comment]
There's not a lot of information to work with here.  Please tell us which version of watchman you are building and provide information about the operating system and compiler versions that you're using.

**Comment by wez** [comment]
Also: the title of the issue doesn't match the error output in the description; please be sure to share as much information as possible.
