### ISSUE TITLE
error while loading shared libraries: api-ms-win-crt-filesystem-l1-1-0.dll

### ISSUE THREAD

**Issue by lcardosozago** [facebook/watchman#627]
Hi, I'm having a problem when executing `watchman` command, this give me an error

> error while loading shared libraries: api-ms-win-crt-filesystem-l1-1-0.dll: cannot open shared object file: No such file or directory

Anyone that had a similar problem?

**Comment by Luc45** [comment]
Same error here. Windows 10 Pro 64 bits with the latest updates. I've tried to manually install Microsoft Visual C++ Redistributable Visual Studio 2017, but no luck. Also tried to install Universal C Runtime, but couldn't find a Windows 10 version for it.

Then I did something unthinkable as a last resource... I've downloaded all standalone DLLs and placed on watchman.exe folder. Well, it worked... These are the DLLs watchman requires to run:

- api-ms-win-crt-filesystem-l1-1-0.dll
- api-ms-crt-locale-l1-1-0.dll
- api-ms-crt-math-l1-1-0.dll
- api-ms-crt-convert-l1-1-0.dll
- api-ms-crt-stdio-l1-1-0.dll
- api-ms-crt-time-l1-1-0.dll
- api-ms-crt-string-l1-1-0.dll
- api-ms-crt-environment-l1-1-0.dll
- api-ms-crt-heap-l1-1-0.dll
- api-ms-crt-runtime-l1-1-0.dll

After you've placed all these DLLs, it will still ask for double-conversion.dll, which is a recent issue with the latest build of watchman.exe, and there's a workaround here: https://github.com/facebook/watchman/issues/675

I've packed all DLLs here: https://mega.nz/#!7pFHBI7K

So, download the workaround watchman from the issue 675, download the dll pack and put in the same folder. That's it, hope it works.

**Comment by dancherb** [comment]
@Luc45 I'm having the same problem - went to download your DLLs but it requires a decryption key? 😁

**Comment by Luc45** [comment]
@dancherb, I've updated the link, it should work now.

**Comment by wez** [comment]
I'd suggest trying the binaries from here: https://github.com/facebook/watchman/releases/latest
Please open a new issue if you have problems with that build.
