### ISSUE TITLE
Install watchman in OS X 10.9.5 (Mavericks)

### ISSUE THREAD

**Issue by lorenzocesconetto** [facebook/watchman#628]
I am trying to install watch man via MacPorts.
When I run the command `sudo port install watchman`
I'm getting the following error:

`--->  Computing dependencies for watchman
--->  Building watchman
Error: Failed to build watchman: command execution failed
Error: See /opt/local/var/macports/logs/_opt_local_var_macports_sources_rsync.macports.org_macports_release_tarballs_ports_sysutils_watchman/watchman/main.log for details.
Error: Follow https://guide.macports.org/#project.tickets to report a bug.
Error: Processing of port watchman failed`

Any help on this?

**Comment by sunshowers** [comment]
Could you include the log?

**Comment by wez** [comment]
We don't support macports directly.  I believe it has a very old version of watchman in its port definition.  If you must use the macports version, you will need to coordinate with the macports folks to get it to build.

I would recommend using homebrew on macos.
