### ISSUE TITLE
Compile errors on freebsd

### ISSUE THREAD

**Issue by ndowens** [facebook/watchman#629]
[patch1.txt](https://github.com/facebook/watchman/files/2251961/patch1.txt)
[patch2.txt](https://github.com/facebook/watchman/files/2251962/patch2.txt)

Fixed the compile errors

**Comment by wez** [comment]
Would you mind submitting this as a pull request?  That way you go through the CLA flow that we require to accept your code submissions, and your changes will trigger the CI to run.
Thanks!

**Comment by ndowens** [comment]
https://github.com/facebook/watchman/pull/634
