### ISSUE TITLE
age-out watches

### ISSUE THREAD

**Issue by amasad** [facebook/watchman#63]
More of a question than an issue. I'm writing a node library on top of the fb-watchman node binding and I have question about cleanup:

* Do I need to `watch-del` the directory I watched? Or is it enough to just unsubscribe?
* What if the user has other programs using that watched directory, will I be messing that up?
* If I don't `watch-del`, is that a leak?

Thanks

**Comment by wez** [comment]
I think the new watch-project stuff obviates the need for this.  I'm going to close this issue; we can revisit if needed in the future.

**Comment by stefanpenner** [comment]
@wez I would like to still plead my case for a watcher decay.

I still need to update ember-cli to take better advantage of watchman, but even with that (and watch-project) I believe a watcher decay would make watchman a much better citizen.

In my developer workflow it is not uncommon to for me to check out various projects a day, each one then indefinitely *leaks* watchers.

Why would I checkout another project?

* preview an add-on demo
* fix a bug in an add-on
* code-review
* creating a new add-on
* creating a new app
* creating a new reproduction of an error scenario

Theoretically solutions:

* conventionalize a shared root for all these activities, and watch the root

  unfortunately, this will likely be difficult to conventionalize across the larger OSS community

**Comment by wez** [comment]
OK, let's re-open under a different name

**Comment by wez** [comment]
We have https://reviews.facebook.net/D37701 in review as a possible implementation of this feature

**Comment by wez** [comment]
This has landed in master and will be part of Watchman 3.7 that we're cutting this week

**Comment by stefanpenner** [comment]
nice!
