### ISSUE TITLE
Crash on OSX

### ISSUE THREAD

**Issue by keithprestonsc** [facebook/watchman#630]
Seeing this while using watchman with Buck. 

Terminating due to signal 11 Segmentation fault generated by pid=0 uid=0.  (0x0)
0   watchman                            0x0000000102124fc1 crash_handler + 345
1   libsystem_platform.dylib            0x00007fff61599f5a _sigtramp + 26
2   ???                                 0x0000000000000028 0x0 + 40
3   watchman                            0x0000000102137a45 w_root_perform_age_out + 147
4   watchman                            0x00000001021379ab consider_age_out + 67
5   watchman                            0x0000000102139505 run_io_thread + 729
6   libsystem_pthread.dylib             0x00007fff615a3661 _pthread_body + 340
7   libsystem_pthread.dylib             0x00007fff615a350d _pthread_body + 0
8   libsystem_pthread.dylib             0x00007fff615a2bf9 thread_start + 13
2018-08-07T09:57:09,225: [listener] Watchman 4.7.0 <no build info set> starting up on

**Comment by wez** [comment]
This should already be fixed in watchman 4.9.0, please upgrade.
