### ISSUE TITLE
Lots of timeouts from Watchman

### ISSUE THREAD

**Issue by keithprestonsc** [facebook/watchman#633]
How do I further test and debug this build machine?    Currently using BUCK to do lots of builds and it frequently fails to query watchman. 

The watchman log is littered with:

synchronization failed: Operation timed out
timedwait failed: 60: istimeout=1 Operation timed out

**Comment by wez** [comment]
Can you share literal sections from the log?  Please also let us know some other characteristics; they are all important:

* OS version + distro
* `watchman version` output
* size of the tree you are watching (number of files, number of dirs)
* Check that you've configured your OS to match your workload: https://facebook.github.io/watchman/docs/install.html#system-specific-preparation
* Is this a spinning disk based system, or SSD/Flash storage?
* `watchman watch-list` output; does it list the tree of interest?
