### ISSUE TITLE
v4.9.0 compile failure on Debian unstable

### ISSUE THREAD

**Issue by cricalix** [facebook/watchman#638]
On buster/sid, updated today, watchman v4.9.0 will not compile.

  CXX      scm/watchman-Mercurial.o
scm/Mercurial.cpp: In constructor ‘watchman::Mercurial::infoCache::infoCache(std::__cxx11::string)’:
scm/Mercurial.cpp:16:40: error: ‘void* memset(void*, int, size_t)’ clearing an object of non-trivial type ‘struct watchman::FileInformation’; use assignment or value-initialization instead [-Werror=class-memaccess]
```
   memset(&dirstate, 0, sizeof(dirstate));
                                        ^
In file included from scm/Mercurial.h:10,
                 from scm/Mercurial.cpp:3:
./FileInformation.h:18:8: note: ‘struct watchman::FileInformation’ declared here
 struct FileInformation {
        ^~~~~~~~~~~~~~~
cc1plus: all warnings being treated as errors
make[1]: *** [Makefile:4446: scm/watchman-Mercurial.o] Error 1
make[1]: Leaving directory '/home/user/src/watchman'
make: *** [Makefile:1264: all] Error 2
```

$ gcc -v
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/lib/gcc/x86_64-linux-gnu/8/lto-wrapper
OFFLOAD_TARGET_NAMES=nvptx-none
OFFLOAD_TARGET_DEFAULT=1
Target: x86_64-linux-gnu
Configured with: ../src/configure -v --with-pkgversion='Debian 8.2.0-4' --with-bugurl=file:///usr/share/doc/gcc-8/README.Bugs --enable-languages=c,ada,c++,go,brig,d,fortran,objc,obj-c++ --prefix=/usr --with-gcc-major-version-only --program-suffix=-8 --program-prefix=x86_64-linux-gnu- --enable-shared --enable-linker-build-id --libexecdir=/usr/lib --without-included-gettext --enable-threads=posix --libdir=/usr/lib --enable-nls --with-sysroot=/ --enable-clocale=gnu --enable-libstdcxx-debug --enable-libstdcxx-time=yes --with-default-libstdcxx-abi=new --enable-gnu-unique-object --disable-vtable-verify --enable-libmpx --enable-plugin --enable-default-pie --with-system-zlib --with-target-system-zlib --enable-objc-gc=auto --enable-multiarch --disable-werror --with-arch-32=i686 --with-abi=m64 --with-multilib-list=m32,m64,mx32 --enable-multilib --with-tune=generic --enable-offload-targets=nvptx-none --without-cuda-driver --enable-checking=release --build=x86_64-linux-gnu --host=x86_64-linux-gnu --target=x86_64-linux-gnu
Thread model: posix
gcc version 8.2.0 (Debian 8.2.0-4) 

```
Your build configuration:

  CC = gcc
  CPPFLAGS =  -D_REENTRANT -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE
  CFLAGS = -g -O2 -Wall -Wextra -Wdeclaration-after-statement -g -gdwarf-2 -fno-omit-frame-pointer
  CXX = g++
  CXXFLAGS = -g -O2 -Wall -Wextra -g -gdwarf-2 -fno-omit-frame-pointer
  LDFLAGS = 
  prefix: /usr/local
  version: 4.9.0
  state directory: /usr/local/var/run/watchman
```

**Comment by cricalix** [comment]
Issue goes away when I switch to master, and different problems show up in thirdparty/jansson.

thirdparty/jansson/load.cpp:109:26: error: ‘ near '’ directive output may be truncated writing 7 bytes into a region of size between 1 and 160 [-Werror=format-truncation=]
                          "%s near '%s'", msg_text, saved_text);
                          ^~~~~~~~~~~~~~
thirdparty/jansson/load.cpp:108:25: note: ‘snprintf’ output 9 or more bytes (assuming 168) into a destination of size 160

**Comment by wez** [comment]
You can pass `--enable-lenient` to configure to disable promoting warnings to errors; hopefully that will unblock you.

**Comment by cricalix** [comment]
Yep, that unblocked. Thank you wez. (Hasn't got the diff view working, but it's squashed Nuclide's "I can't find watchman" on startup.)

**Comment by chadfurman** [comment]
I have similar issues related to jansson -- this appears to be a new GCC thing https://github.com/akheron/jansson/pull/423

**Comment by meowsus** [comment]
On Ubuntu 19.04 the only thing that worked for me was checking out the `v4.9.0` tag and compiling with:

```shell
./configure --without-python  --without-pcre --enable-lenient
```

Hope this helps someone in the future.

**Comment by rohanshukla9** [comment]
./configure --enable-lenient did the job. I had to install python-dev though.

**Comment by marianzburlea** [comment]
> You can pass `--enable-lenient` to configure to disable promoting warnings to errors; hopefully that will unblock you.

Thanks a lot! This helped me pass the `make` step on **Ubuntu 19.04**

**Comment by caco13** [comment]
> On Ubuntu 19.04 the only thing that worked for me was checking out the `v4.9.0` tag and compiling with:
> 
> ```shell
> ./configure --without-python  --without-pcre --enable-lenient
> ```
> 
> Hope this helps someone in the future.

No errors but a lot of warnings with that options. Apparently the watchman was installed.

**Comment by angeloDiepe** [comment]
Thanks alot helped pass the make step **ubuntu 20.04** ![bitmoji](https://sdk.bitmoji.com/render/panel/38e3bc7c-223a-4cd4-9c00-b7a942bcc2d0-9da2a378-3507-4629-b7a7-557bd64af3d5-v1.png?transparent=1&palette=1&width=246)

**Comment by angeloDiepe** [comment]
> On Ubuntu 19.04 the only thing that worked for me was checking out the `v4.9.0` tag and compiling with:
> 
> ```shell
> ./configure --without-python  --without-pcre --enable-lenient
> ```
> 
> Hope this helps someone in the future.

Thanks alot helped pass the make step **ubuntu 20.04** ![bitmoji](https://sdk.bitmoji.com/render/panel/ed5c9c0f-c444-4b15-b96b-a66885184e6a-9da2a378-3507-4629-b7a7-557bd64af3d5-v1.png?transparent=1&palette=1&width=110)

**Comment by harbingerofdoom** [comment]
build/ARM/dev/ide_ctrl.cc: In constructor 'IdeController::Channel::Channel(std::__cxx11::string, Addr, Addr)':
build/ARM/dev/ide_ctrl.cc:85:40: warning: 'void* memset(void*, int, size_t)' clearing an object of type 'struct IdeController::Channel::BMIRegs' with no trivial copy-assignment; use assignment or value-initialization instead [-Wclass-memaccess]
     memset(&bmiRegs, 0, sizeof(bmiRegs));
                                        ^
In file included from build/ARM/dev/ide_ctrl.cc:49:
build/ARM/dev/ide_ctrl.hh:83:16: note: 'struct IdeController::Channel::BMIRegs' declared here
         struct BMIRegs
                ^~~~~~~
At global scope:
cc1plus: error: unrecognized command line option '-Wno-constant-conversion' [-Werror]
cc1plus: error: unrecognized command line option '-Wno-for-loop-analysis' [-Werror]
cc1plus: error: unrecognized command line option '-Wno-potentially-evaluated-expression' [-Werror]
cc1plus: error: unrecognized command line option '-Wno-mismatched-new-delete' [-Werror]
cc1plus: error: unrecognized command line option '-Wno-undefined-var-template' [-Werror]
cc1plus: error: unrecognized command line option '-Wno-inconsistent-missing-override' [-Werror]
cc1plus: all warnings being treated as errors
scons: *** [build/ARM/dev/ide_ctrl.o] Error 1
scons: building terminated because of errors.


I tried the above experiments but none of them seems to work in sconscript.
How can i resolve it? I am using gcc 8.3 and on CentOs 8
