### ISSUE TITLE
watchman -j hanging 

### ISSUE THREAD

**Issue by ghost** [facebook/watchman#64]
Hi,
I'm very new to watchman. I find that the simple syntax is great and easy to work with. But I need extended syntax for a couple of reasons, try to run the example script with my path replaced : 

``` sh
watchman -j <<-EOT
["trigger", "/path/to/root", {
  "name": "assets",
  "expression": ["pcre", "\.(js|css|c|cpp)$"],
  "command": ["make"]
}]
EOT
```

It doesn't seem to do anything. It just hangs there and the trigger is not in the path's trigger list. Did I do anything wrong ?

Thanks for creating such great tool :)

**Comment by pardha-billa** [comment]
I am new to wathman. I am using zsh. I think I didn't install watchman correctly in my Ubuntu. Can anybody help me. 
I am getting following error while using watchman

 **zsh: command not found: watchman**

**Comment by wez** [comment]
@pardha-billa please open a new issue; be sure to include what you tried and the errors you're seeing
