### ISSUE TITLE
Could not  run application in react-native getting issue

### ISSUE THREAD

**Issue by AnitaVPN** [facebook/watchman#640]
![screen shot 2018-08-24 at 5 45 05 pm](https://user-images.githubusercontent.com/38452188/44584240-f07e3900-a7c5-11e8-816b-1d878545473b.png)
Hi i am newbie in react-native development

Following things i have perform before build react-native application

1. Install WebStorm
2. Intsall NPM
3. Install watchman
4. Intsall react-native
5. Update brew

When i am run the command i am getting following issue

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2018-08-24T17:37:44,142: [0x7fffab20d380] while computing sockname: failed to create /usr/local/var/run/watchman/macbookpro-state: No such file or directory

I am also attaching the screenshot here , please take a look and guide me for proceed further

Help will be really appriciated

Thanks

**Comment by wez** [comment]
Sounds like `/usr/local/var/run/watchman/` doesn't exist.  Setting that up is typically handled by the installation process.  How did you install watchman?  We recommend using `brew` for that.  My suggestion is to uninstall watchman, update brew and then install watchman again, because from what you posted it sounds like you updated brew after installing, so you may have installed an older version of something.

**Comment by tomaszwojcik** [comment]
Same issue here, sadly the installation using `brew` fails:

```
brew install watchman
==> Downloading https://homebrew.bintray.com/bottles/watchman-4.9.0.high_sierra.bottle.tar.gz
Already downloaded: /Users/twojcik/Library/Caches/Homebrew/watchman--4.9.0.high_sierra.bottle.tar.gz
==> Pouring watchman--4.9.0.high_sierra.bottle.tar.gz
Warning: The post-install step did not complete successfully
You can try again using `brew postinstall watchman
```

Tried `brew uninstall watchman && brew install watchman` - didn't help at all.

When running `watchman version`:
```
2018-08-29T15:02:08,530: [0x7fff9a86a380] while computing sockname: failed to create /usr/local/var/run/watchman/twojcik-state: No such file or directory
```

**Comment by tomaszwojcik** [comment]
Still no progress for installing using `brew` (even reinstalled `Homebrew`).

However this seems to work (it's based on `watchman` formula):
```
cd /usr/local/var/run
sudo mkdir watchman
sudo chmod 042777 watchman
```

The `watchman version` correctly returns the version now:

```
{
    "version": "4.9.0"
}
```

And it seems to hot reload code in `React Native`.

**Comment by wez** [comment]
From what you pasted, it sounds like there was something up with your system:

```
Warning: The post-install step did not complete successfully
```

My guess is a permissions problem blocking something.  Now that you've manually created those dirs I wonder if you've unblocked it?

Since this wasn't a watchman problem and you're unblocked, I'm going to close this issue.

**Comment by tomaszwojcik** [comment]
Well, the issue with dir access occured on 2nd day of using `watchman` and `React Native` (1st day was totally fine) so I'm not quite sure what could happen with my system after 1 day of work with mentioned tools.

So I guess this is a safe workaround to manually create `watchman` dir.

**Comment by PomegranateApps** [comment]
I am also having this issue. I'm using brew to install and it's not creating this directory for me in Mac OS X Catalina.

**Comment by timkindberg** [comment]
I just had this exact issue. I tried everything from [this comment](https://github.com/facebook/watchman/issues/640#issuecomment-416945346) and had the exact same experience. Watchman error followed by postinstall failure.

**Comment by wichopy** [comment]
This fixed for me. https://stackoverflow.com/questions/32105860/the-command-brew-install-watchman-runs-chmod-but-fails-to-install-eventually/41320226#comment110182255_41320226

**Comment by free-soellingeraj** [comment]
I started the server with `sudo`, in my case it was `sudo yarn start`

**Comment by software-mariodiana** [comment]
My Watchman was installed via Homebrew. I don't know what went wrong, but my error stemmed from that fact that there was no `/usr/local/var/run/watchman` directory. Homebrew had installed one here: `/usr/local/homebrew/var/run/watchman`.

I fixed this with a bit of a hack. I created a soft link at the path Watchman was looking for (`/usr/local/var/run/watchman`) that pointed to `/usr/local/homebrew/var/run/watchman`.

**Comment by lemonkang** [comment]
i start react -native project with this wrong issue

i fix it
```javascript
 cd /usr/local/var/run  
sudo mkdir watchman
sudo yarn start
```

<img width="1096" alt="image" src="https://github.com/facebook/watchman/assets/53658981/9781f286-e9ea-419a-b735-4b75d22d7fc4">

**Comment by arrmani88** [comment]
In my case, i had this symlink `/usr/local/var/homebrew/linked/watchman` which points to `/usr/local/Cellar/watchman/2023.12.04.00`.
When I investigated, I found that `/usr/local/Cellar/watchman/2023.12.04.00` was somehow deleted, which means the symlink pointed to an existing folder.  

The solution was to easily do:
```
rm -rf /usr/local/var/homebrew/linked/watchman
brew update
brew install watchman
``` 

if you can't install watchman, try `brew uninstall watchman`, then `brew install watchman`
