### ISSUE TITLE
ImportError: cannot import name hg

### ISSUE THREAD

**Issue by Saliva520319** [facebook/watchman#642]
env： osx 10.12.6
python version 2.7.14
When i run watchman -v, return this error:

Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/bin/watchman", line 7, in <module>
    from watchman.main import main
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/watchman/main.py", line 4, in <module>
    from sh         import cd, hg, git, watchman
ImportError: cannot import name hg

from the Traceback , I just install the commandline toolpack sh  using pip,but still throw this error.

how to fix this all maybe I did wrong somewhere?

**Comment by wez** [comment]
Our `watchman` isn't installable via pip, I think you installed this other unrelated project https://github.com/alephmelo/watchman, which is a newer project and unfortunately picked the same name as our pre-existing project.

**Comment by Saliva520319** [comment]
@wez Thanks for reply, I use homebrew to install watchman, seems I made a stupid mistake. the path order make the default watchman is the python one. many thanks
