### ISSUE TITLE
Installing Watchman on macOS Mojave

### ISSUE THREAD

**Issue by RustiRabbit** [facebook/watchman#649]
I was trying to install Watchman on macOS Mojave and got this error:
`Errno::EPERM: Operation not permitted @ dir_s_mkdir - /usr/local/Cellar`

Is it a Homebrew problem or is it a Watchman issue?

**Comment by wez** [comment]
Not watchman.  Not sure that it is really a homebrew problem either; sounds like the Mojave upgrade messed with the permissions on your homebrew install.  I'd suggest asking the homebrew folks how to proceed.

**Comment by RustiRabbit** [comment]
Thanks, I'll go talk to the Homebrew people
