### ISSUE TITLE
Provide a Debian package as part of releases?

### ISSUE THREAD

**Issue by njlr** [facebook/watchman#659]
This would make installation much easier on services such as Travis CI. This is already done by Buck (for example https://github.com/facebook/buck/releases/tag/v2018.10.29.01)

**Comment by aweeraman** [comment]
Watchman is now also available in Debian and Ubuntu and can be installed via 'apt-get install watchman'. New releases will be tracked and made available in Debian unstable/testing.

**Comment by njlr** [comment]
```
sudo apt-get install watchman
```
