### ISSUE TITLE
Shutdown Server Issue

### ISSUE THREAD

**Issue by zhanghongce** [facebook/watchman#661]
Is it true that if a user accidentally watched his/her home directory, he/she will not be able to (a) shutdown the server (b) unwatch it?

**Comment by zhanghongce** [comment]
At least this seems to be what happened to me...

    hongcez@server:~$ echo $HOME
    /home/hongcez
    hongcez@server:~$ watchman watch-list
    {
        "version": "4.9.0",
        "roots": [
            "/home/hongcez/test",
            "/home/hongcez"
        ]
    }
    hongcez@server:~$ watchman watch-del-all
    {
        "version": "4.9.0",
        "roots": [
            "/home/hongcez/test",
            "/home/hongcez"
        ]
    }
    hongcez@server:~$ watchman watch-list
    {
        "version": "4.9.0",
        "roots": [
            "/home/hongcez",
            "/home/hongcez/test"
        ]
    }

**Comment by wez** [comment]
You can use the `watch-del` command to delete a watch; this page has more information:

https://facebook.github.io/watchman/docs/cmd/watch-del.html

**Comment by wez** [comment]
(sorry, I only just noticed this issue!)

**Comment by zhanghongce** [comment]
Thanks!
