### ISSUE TITLE
unable to talk to your watchman ...

### ISSUE THREAD

**Issue by karlkras** [facebook/watchman#671]
OS: IOS Mojave
watchman: v4.9.0

in the last day or so, starting my react-native environment, long hang followed by watchman error:
```
[cli] unable to talk to your watchman on /opt/local/var/run/watchman/axian-state/sock! (No such file or directory)
```
which is absolutely true, there is no `sock!` at that location. Have no idea why it's suddenly looking for it?

**Comment by karlkras** [comment]
so, it looks like it's an access issue with watchman. Using sudo works with execution of watchman, fails without. I've tried resetting access to the obvious executables, but can't get it working.

**Comment by gregblake** [comment]
@karlkras I encountered this issue as well. You're correct that it is an access issue. 

Running this resolved the issue for me:

```bash
chmod 0700 /usr/local/var/run/watchman/greg-state
```

Make sure to change "greg" to your user ("axian" in your case).

**Comment by karlkras** [comment]
Yeah, I believe I already did this, but I'll double check this evening... I sorta gave up and moved exclusively to android only emulator from a windows box.

**Comment by unfrgivn** [comment]
I am having this same issue on Mojave with 4.9.0. The steps which worked for everyone else reinstalling watchman with brew and changing permissions have no impact.

Same error and outputs to original questions as @karlkras

**Comment by unfrgivn** [comment]
Hmm I eventually resolved this by repeating the uninstall and reinstall watchman + permissions a few times and ultimately restarting I think fixed it. Sorry, I'm all good now

**Comment by RIP21** [comment]
For anyone who has a similar issue.
If even `watchman --foreground --logfile=/dev/stdout` fails, everything will more likely fail too.
In my case just going to `/usr/local/var/run/watchman/<username>-state/` and removing `pid` and other files that were there, fixed the issue.

**Comment by honeyp0t** [comment]
I also had issues with watchman hanging.

In addition to what's been mentioned above I also had the issue that I installed and ran watchman over an SSH session which may not work very well, at least not in my case.

**Comment by SevenZark** [comment]
I'm having this issue on Windows, so a lot of these fix suggestion (dealing with pids, chmod, /dev/stdout) don't apply. Anybody solve this for Windows?

**Comment by ryancat** [comment]
I have similar issue to this. After an hour of reinstall watchman, a simple restart my MacBook solved it...

**Comment by naumanzchaudhry** [comment]
Restarting solved this for me

**Comment by wez** [comment]
I am no longer with Meta and haven't worked on watchman in a couple of years. You might be better served by opening a new issue of your own, rather than piggy-backing on top of a 4 year old closed issue.

**Comment by anandvarkeyphilips** [comment]
How can we re-open this issue? This is still affecting us.
