### ISSUE TITLE
glog.dll not found.execution can't proceed

### ISSUE THREAD

**Issue by rahulk8** [facebook/watchman#675]
glog.dll not found.execution can't proceed.reinstalling can solve the issue...my window say this

**Comment by wez** [comment]
We're in the middle of changing deps, so the latest master builds don't yet capture all of them.
You can try this build from before the deps changed:

https://ci.appveyor.com/project/wez/watchman/builds/21736853/job/lp4n8kyiq3fv1s0l/artifacts

**Comment by Dmo16** [comment]
Tried this file as @wez suggested but same results.

**Comment by kumarharsh** [comment]
@Dmo16 you also need to copy all the DLLs and place them with the watchman binary. See #683 for details.

**Comment by kumarharsh** [comment]
@wez can we temporarily either link to #683 in the "Download for windows" part? Or link to the latest "passing" build?

**Comment by wez** [comment]
I'm going to close this issue in favor of @kumarharsh's https://github.com/facebook/watchman/issues/683 which has some nicely prepared instructions
