### ISSUE TITLE
$PATH is very hard to set on MacOS Yosemite

### ISSUE THREAD

**Issue by dmcg** [facebook/watchman#68]
Commands that I invoke through Watchman on Yosemite have a PATH set to /usr/bin:/bin:/usr/sbin:/sbin

Needless to say, very little of my toolchain is in that path.

I think that it has to do with launchd defaulting to a very restricted path http://apple.stackexchange.com/questions/106355/

The only solution I've come up with is to source ~/.bash_profile in scripts invoked from Watchman, but this means that if I invoke them normally they have an enormous path set.

**Comment by jimtla** [comment]
Any updates on this? As a hack I've added a script to freeze my current env into the plist: 

```bash
#Freeze the current env to the watchman config. This is a hack to get around
# https://github.com/facebook/watchman/issues/68
ENVIRONMENT=$(env | sed 's/=/<\/key><string>/' | sed -e 's/^/<key>/' | sed -e 's/$/<\/string>/')
echo $ENVIRONMENT

PLIST=~/Library/LaunchAgents/com.github.facebook.watchman.plist

# Remove the last two lines.
sed -i '' -e '$ d' $PLIST
sed -i '' -e '$ d' $PLIST

# replace the second to last line (previously "</dict>") with our environment +
# "</dict>"
echo "<key>EnvironmentVariables</key><dict>"$ENVIRONMENT"</dict></dict>" >> $PLIST

# Replace the last line
echo "</plist>" >> $PLIST

# Reload the watchman config
launchctl unload -w ~/Library/LaunchAgents/com.github.facebook.watchman.plist
launchctl load -w ~/Library/LaunchAgents/com.github.facebook.watchman.plist
```

but it's annoying to manually run that after any update to my env.

**Comment by wez** [comment]
We have a diff that we'll land real soon now: https://reviews.facebook.net/D36045

**Comment by wez** [comment]
This has landed; we're going to cut 3.1 with this fix in it soon and submit a PR to homebrew.
Meanwhile, you can do `brew install --HEAD watchman` to pick up this fix.

**Comment by sunny-mittal** [comment]
I am still having an issue related to this (I think) using 3.3.0. I ran the following in my project root:
```
$ watchman watch `pwd`
$ watchman -- trigger `pwd` js '*.js' -- "browserify -o bundle.js"
```
But when I check the logs, I see a "No such file or directory" error. If I change the command to `cat` or something, I see the output in the log as expected. The plist confirms that my path is getting picked up, but it doesn't seem to be able to find browserify.

**Comment by wez** [comment]
I think you want this:

`watchman -- trigger `pwd` js '*.js' -- browserify -o bundle.js`

otherwise watchman will try to find the file named "browserify -o bundle.js" in your path and execute it

**Comment by sunny-mittal** [comment]
I tried that as well...no luck. I also tried it with various node-related commands and they all fail with the same error. Any other ideas? In the log file, I can see that the path is correct but it just doesn't seem to want to execute any command related to node.

**Comment by wez** [comment]
I can't see your log file so I don't have any more context than you have shared on this closed issue.
I'd recommend just making a wrapper script that sets the appropriate things in the environment:

```
#!/bin/sh
PATH="$PATH:/some/where"
NODE_PATH="whatever is appropriate"
export PATH NODE_PATH
exec browserify -o bundle.js "$@"
```

**Comment by sunny-mittal** [comment]
I'll give that a shot. Thanks for your help!

**Comment by jimtla** [comment]
For anybody looking - my hack to freeze the environment into the plist doesn't work so well anymore, but I wrote a new script to bake the current environment into a shell script: 
```
#!/bin/bash -e -x

# Takes a bash script as the only argument, and prints the location of a new
# shell script that executes the given script with the current environment.

SCRIPT=`mktemp $TMPDIR"bake_env".XXXXXXXX`
ENVIRONMENT=$(env | sed "s/=\(.*\)\$/='\1'/g" | sed 's/^/;export /')
echo "#!/bin/bash -e" >> $SCRIPT
echo "true"$ENVIRONMENT >> $SCRIPT
ABS_PATH=`python -c "import os; print os.path.realpath('$1')"`
echo "exec $ABS_PATH \$@" >> $SCRIPT
chmod a+x $SCRIPT
echo $SCRIPT
```
When I want to run something with watchman I pass the target to run to that script, and then pass the output to watchman.
