### ISSUE TITLE
Error while loading shared libraries: double-conversion.dll:

### ISSUE THREAD

**Issue by andrzejpalemba** [facebook/watchman#681]
I am getting errors while running watchman on Windows 7:

`watchman --version`
`C:/Program Files/watchman/watchman.exe: error while loading shared libraries: double-conversion.dll: cannot open shared object file: No such file or directory`

**Comment by wez** [comment]
Duplicate of https://github.com/facebook/watchman/issues/675

**Comment by wez** [comment]
Actually, https://github.com/facebook/watchman/issues/683 has a better resolution
