### ISSUE TITLE
Downloading latest windows builds gives non-functional watchman

### ISSUE THREAD

**Issue by kumarharsh** [facebook/watchman#683]
The link to download the latest watchman build leads users to download builds which are failing on Appveyor. This leads them to raise issues like #681 and #675. Expecting them to download dlls provided by other well meaning peers is not secure, as seen here: https://github.com/facebook/watchman/issues/627#issuecomment-464461216.

### The workaround
The trick is to download a build from Appveyor which is **passing**. So, head to the source of the Windows builds: https://ci.appveyor.com/project/wez/watchman/history, and keep scrolling down and click *Show More* until you see a build which is passing (green border):

![image](https://user-images.githubusercontent.com/760112/53321470-95f1a100-38fe-11e9-9547-4a3ac6df0e2d.png)

Click on the commit message to go to that build, then click the "Artifacts" link to view the artifacts page:
![image](https://user-images.githubusercontent.com/760112/53321516-be799b00-38fe-11e9-8488-22bded58b7d3.png)

where you can download the `watchman.zip` file:
![image](https://user-images.githubusercontent.com/760112/53321528-c76a6c80-38fe-11e9-9b49-ce24993555c2.png)

Extract **all** the useful contents (*.exe, *.dll) and put them somewhere in your path. I put them in a folder called `C:\bin\misc`. Then open a new cmd or powershell, and run `watchman version`. It should work.

**Comment by kumarharsh** [comment]
For the record, this is the latest **passing** build for Windows: https://ci.appveyor.com/project/wez/watchman/builds/22125585/artifacts

Follow the instructions above to get a working watchman.

**Comment by wez** [comment]
Thanks for digging into this; I'm glad you found a build with those deps included.

**Comment by wez** [comment]
I've adjusted the download link to reference that particular build for the time being

**Comment by chaojiangcn** [comment]
第一次用，就不会安装

**Comment by damiangreen** [comment]
I've kept scrolling but all builds seem to be failing

**Comment by zeldafreak** [comment]
@damiangreen This was the latest build I found that was passing: https://ci.appveyor.com/project/wez/watchman/builds/24658997/artifacts
