### ISSUE TITLE
watchman.exe on Windows 10

### ISSUE THREAD

**Issue by ktodyruik** [facebook/watchman#685]
Hi. 

I just tried downloading and installing Watchman for Windows. Hmmm... Puzzling. Running watchmane.exe on the command line does nothing... Just goes to the next line.  No errors, no messages.

Bummer. This looked so promising.

**Comment by wez** [comment]
Sounds like it started up. Is there something specific you wanted to do with it?

**Comment by ktodyruik** [comment]
Oh... It actually worked? I can't tell. Maybe a message saying it started or something would be helpful. It looks to me like it just died. Watchman seems to be a bit different from most command line tools. It doesn't follow the idioms we are accustomed to.

I want to monitor a directory of files with a specific extension and compile it when the file changes. Like make, but without having to run make all the time. :) Is there a simple example somewhere that demonstrates this? 

Thanks

**Comment by ktodyruik** [comment]
Basically I want to do what transpilers like coffeescript do with their built in --watch command line option, for a transpiler that doesn't have --watch. Thanks

**Comment by wez** [comment]
Take a look at https://facebook.github.io/watchman/docs/watchman-make.html

We don't have that packaged up on windows, so you'll need to clone the repo from github to get at the script and the pywatchman library.

The `python` subdirectory of the repo has a `bin` dir containing `watchman-make` and a `pywatchman` library that it requires to run.

Windows support is still early days for us so you'll have to figure out how to get your python environment in a state that is ready to run this; sorry :)

**Comment by Timon0305** [comment]
how can I get download watchman.ext

**Comment by karthik2342323** [comment]
Release version doesn't have any watchman.exe file so how windows gonna run without .exe file .
