### ISSUE TITLE
Alpine Edge Testing package, does not create the statesdir.

### ISSUE THREAD

**Issue by inf3cti0n95** [facebook/watchman#689]
I tried using the watchman package from the Alpine Repository https://pkgs.alpinelinux.org/package/edge/testing/x86/watchman 

And I get error when I am running watchman. Similar to this #640 .

Which I fixed by creating the missing directory manually. Is it supposed to be like that? Or the Alpine Installation should be generating that Package? Since the build log of the alpine package did log the state directory https://build.alpinelinux.org/buildlogs/build-edge-x86/testing/watchman/watchman-4.9.0-r2.log . Shouldn't it be creating directory post installing the package.

**Comment by wez** [comment]
Please reach out to the Alpine package maintainer; we don't directly maintain packaging for any linux distributions.

**Comment by inf3cti0n95** [comment]
Okay thanks! Did it!
