### ISSUE TITLE
can watchman-make rerun scripts that do not exit?

### ISSUE THREAD

**Issue by wis** [facebook/watchman#691]
watchman-make is not restarting my server/infinate loop script.

```watchman-make -p 'swapWindowFocusListener' --run 'server_script'```
then I tried:
```watchman-make -p 'swapWindowFocusListener' --run 'pkill -f "^python3 path/to/server_script$"; server_script'```

server_script
``` python
#!/usr/bin/env python3
# blocking/non-exiting server code

```

while trying to take a look at `watchman-make`s python code installed on my system, I discovered `watchman-wait` and made a little bash script that reruns scripts that don't exit. 

``` bash
#!/bin/bash
# watch and on save rerun scripts that dont exit.
# first argument ($1) is a commandline only of this form:
# runner script_path [args], e.g python|node path/to/script.py|.js --h
cmdln="$1" #echo ${cmdln}
arr=($cmdln)
length=${#arr[@]} #echo "length $length"
if (( $length >= 2 )); then
    path="${arr[1]}" #echo "path $path"
    while true; do
        $cmdln &
        forkedPid=$!
        watchman-wait "$path"
        if [[ "$?" -ne "0" ]]; then
            echo "watchman exit status: $?.. not 0, exiting.."
            kill $forkedPid
            exit 1
        fi
        kill $forkedPid
    done
fi
```

**Comment by wez** [comment]
this comment has relevant information on this topic:
https://github.com/facebook/watchman/issues/447#issuecomment-296737851
