### ISSUE TITLE
Unable to talk to your watchman / Failed to lock pidfile

### ISSUE THREAD

**Issue by NotHawthorne** [facebook/watchman#697]
Hey guys! I'm having this issue where npm start in a blank React Native project causes the error: 

`Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2019-04-04T09:30:50,148: [cli] unable to talk to your watchman on /nfs/2018/a/alkozma/.brew/var/run/watchman/alkozma-state/sock! (No such file or directory)`

The log file shows this:

`2019-04-04T09:41:51,328: [0x7fff92e27340] Failed to lock pidfile /nfs/2018/a/alkozma/.brew/var/run/watchman/alkozma-state/pid: process  owns it: Operation not supported`

It's becoming really frustrating for me and my team. Any insights into how to fix this? Steps taken already:

`brew rm watchman
brew update && brew upgrade
brew install watchman`

Note: Installing with the --HEAD flag throws errors relating to python 2.7 multithreading in autopen.sh???

`chmod 0700 /nfs/2018/a/alkozma/.brew/var/run/watchman/alkozma-state`

I reproduced the error by writing a simple C main, opening the file with the same flags (O_RDWR | O_CREAT, 0644) and fcntl with F_SETLK, and it returns -1 in my program. Permissions are fine. Someone please help!

**Comment by wez** [comment]
It looks like you're using NFS.  I think there are two problems that you're facing here:

1. The `/var/run` directory is always supposed to be machine-local.  Mounting it over NFS violates that expectation and will cause similar problems with other software.  In particular, file locking is notoriously broken over NFS and watchman needs to have working locking to safely start just a single instance of the daemon.
2. It is not possible to watch directories mounted via NFS.  I'm not sure if you're hoping to try that, but it won't work: it may appear to partially work (eg: local changes *may* be reported), but changes made via other machines will not be visible and will lead to incorrect results.

I would recommend that you configure your homebrew installation to place `/var/run` on the local system to resolve the first part.
