### ISSUE TITLE
In Linux configure script doesn't check for OpenSSL headers presense

### ISSUE THREAD

**Issue by mike1808** [facebook/watchman#699]
I've tried to install watchman on Ubuntu 17.10 and didn't have OpenSSL libs installed and got the following build error:

```
ContentHash.cpp:13:10: fatal error: openssl/sha.h: No such file or directory
 #include <openssl/sha.h>
          ^~~~~~~~~~~~~~~
```

The problem was easily fixed by installing appropriate libraries (`libssl-dev` in Ubuntu).

It'd nice to have the warning during `./configure`

**Comment by mike1808** [comment]
I saw that CMake file contains a check for that. I guess it's platform and cmake issue, not watchman. Can be closed.

**Comment by mike1808** [comment]
Duplicate of #606

**Comment by anidaniel** [comment]
You need to install `sudo apt install -y libssl-dev`
