### ISSUE TITLE
Watchman with Ember CLI issue

### ISSUE THREAD

**Issue by JDillon522** [facebook/watchman#70]
I recently opened up an issue on the [Ember-CLI repo](https://github.com/stefanpenner/ember-cli/issues/2622) and per the advice there I'm going to open an issue here.

In short, while using Watchman via Ember-CLI, I had this error:

> version: 0.1.3
> valid watchman found, version: [3.0.0]
> Livereload server on port 35729
> Serving on http://0.0.0.0:4200/
> 
> events.js:72
>         throw er; // Unhandled 'error' event
>               ^
> Error: FSEventStreamStart failed
>     at null.<anonymous> (/Users/jdillon/Desktop/openSrc/shoppingList/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/index.js:84:23)
>     at emit (events.js:95:17)
>     at null.<anonymous> (_stream_readable.js:764:14)
>     at emit (events.js:92:17)
>     at emitReadable_ (_stream_readable.js:426:10)
>     at emitReadable (_stream_readable.js:422:5)
>     at readableAddChunk (_stream_readable.js:165:9)
>     at Readable.push (_stream_readable.js:127:10)
>     at Transform.push (_stream_transform.js:140:32)
>     at JSONStream._transform (/Users/jdillon/Desktop/openSrc/shoppingList/node_modules/ember-cli/node_modules/broccoli-sane-watcher/node_modules/sane/node_modules/fb-watchman/node_modules/json-stream/lib/json-stream.js:30:14)

I ran `brew uninstall watchman` and the cli's `ember serve` command worked but without the live reload capability. I reinstalled watchman with `brew install watchman` and had the same issue. I also tried `watchman shutdown-server` and had this output: 

> {
>   "version": "3.0.0",
>   "shutdown-server": true
> }

This didnt change the error. 

I ran:
`which -a watchman`
`watchman version` 

And got:

> brew install watchman
> ==> Downloading https://downloads.sf.net/project/machomebrew/Bottles/watchman-3.0.0.mavericks.bottle.tar.gz
> Already downloaded: /Library/Caches/Homebrew/watchman-3.0.0.mavericks.bottle.tar.gz
> ==> Pouring watchman-3.0.0.mavericks.bottle.tar.gz
> 🍺  /usr/local/Cellar/watchman/3.0.0: 4 files, 184K
> 
> which -a watchman
> /usr/local/bin/watchman
> 
> watchman version
> {
>     "version": "3.0.0"
> }

It was suggested that I upgrade to Yosemite. After upgrading everything worked fine. 

Any ideas?

**Comment by mariozig** [comment]
@amasad I ran into the same situation -- `fseventsd` some how ended up in a bad state (still not sure how/why).  I fixed it by killing the `fseventsd` process, which automatically respawns, and then rerunning my ember cli commands.  Things work fine after that.

**Comment by Mukhilan** [comment]
Leave a comment

**Comment by eibrahim** [comment]
a restart did it for me
