### ISSUE TITLE
Different behavior watching directory under symlink socket vs CLI

### ISSUE THREAD

**Issue by louissobel** [facebook/watchman#700]
Hello —

With a project directory like:
```
/code/lives/at/projectDir
```

and a symlink from

```
/path/to/symlinkToCodeDir --> /code/lives/at
```

watching then calling `clock` on `/path/to/symlinkToCodeDir/projectDir` behaves inconsistently between the CLI or sending commands to the watchman socket.

- I'm running Mac OS 10.14.4.

- For both, a `watch-project /path/to/symlinkToCodeDir/projectDir` succeeds
- From the command line, `clock /path/to/symlinkToCodeDir/projectDir` works, but sending the same thing to the watchman socket fails with an error like:
```
unable to resolve root /path/to/symlinkToCodeDir/projectDir: unable to lstat "/path/to/symlinkToCodeDir/projectDir" open: /path/to/symlinkToCodeDir: Too many levels of symbolic links
```

From some initial investigation, this is failing at https://github.com/facebook/watchman/blob/master/FileDescriptor.cpp#L663, because the parent of the root is a symlink, but in the open options used `followSymlinks` is zero, so we set `O_NOFOLLOW` at https://github.com/facebook/watchman/blob/master/FileDescriptor.cpp#L217 . I experimented with setting `followSymlinks` to true in the `queryFileInfo` options, but then, while the `open` succeeded, we later failed in a comparison of the passed path to the canonicalized one (they are indeed different).

It feels like the symlink handling logic in here is pretty complicated, so rather than continuing trying to debug I figured I would open an issue and see if this was something you all could help with.

This particular directory / symlink setup did work on watchman 4.7

**Comment by louissobel** [comment]
I have a failing test case at https://github.com/facebook/watchman/compare/master...louissobel:parent-directory-symlink — it works for the CLI usage but not for any of the Local ones

**Comment by wez** [comment]
Sorry, I haven't looked at this deeply yet, but my gut reaction is that you're running into:
https://github.com/facebook/watchman/issues/533

**Comment by louissobel** [comment]
Ah — brilliant — yes that's it — I will fix our client. Thank you!
