### ISSUE TITLE
Always RootResolveError on macOS when creating trigger

### ISSUE THREAD

**Issue by tybook** [facebook/watchman#702]
Trigger defined like this
```
watchman -n -j <<-EOT
["trigger", "$(pwd -P)", {
  "name": "watchman_bug",
  "command": ["$(pwd -P)/triggered_script.sh"],
  "append_files": false,
  "stdin": [
      "name",
      "exists",
      "type"
  ]
}]
EOT
```

No matter what path I I tried for the trigger (even plain hard-coded paths), I get the following error:
```
{
    "version": "4.9.4",
    "error": "RootResolveError: unable to resolve root /Users/ty/code/watchman_bug: directory /Users/ty/code/watchman_bug is not watched"
}
```

This is with latest `master`, commit `7bce6e959bc0038b30e2787eb2abae2763516914` on macOS 10.14.4. I built it by manually installing Folly with `brew install folly`, then `autogen.sh` followed by `make`.

**Comment by wez** [comment]
You can only register a trigger for a watched project.   In other words, you must first run `watchman watch-project .`
Note that watchman will aggregate watches under the same directory tree, so a robust integration will parse the output from `watch-project` and react accordingly.

With all that said, most trigger use cases are more easily met with the `watchman-make` command; it's easier to see what is happening and to kill it off with ctrl-c when you want it to stop.
More info on that here: https://facebook.github.io/watchman/docs/watchman-make.html

**Comment by tybook** [comment]
Yep that was it, thanks!
