### ISSUE TITLE
Additional WIP `serde_bser` impls

### ISSUE THREAD

**Issue by mystor** [facebook/watchman#708]
I was recently poking around with `watchman` again, and noticed that this repo has a [WIP `serde_bser` implementation](https://github.com/facebook/watchman/tree/5cfe655e76df7610a3265776092c11b43ef9ba54/rust/serde_bser). 

A few months ago, I also threw together a WIP `serde_bser` implementation, not realizing that this implementation existed. I never got around to testing it ~~at all~~ heavily, so I'm doubtful that there's much in it which will be useful, but I figured I'd let y'all know it exists. If there's anything handy, feel free to take the code (I can even add a license file :-P).

https://github.com/mystor/serde-bser/

cc @sunshowers

**Comment by wez** [comment]
Thanks :)

Sorry: some legal preamble.  We'll need you to sign our CLA before we can take your contribution, and the easiest path for us is if you submit a PR (a bot will take you through the CLA flow if needed, but you can take a peek at that at https://code.facebook.com/cla).

With that out of the way: if you have a bit of time to massage your work into a PR, that will help highlight any differences and see if you've managed to close some of our gaps.

Thanks!

**Comment by wez** [comment]
We published https://docs.rs/serde_bser/0.2.0/serde_bser/ as part of releasing https://docs.rs/watchman_client so I'm going to mark this as closed.
