### ISSUE TITLE
Assigned value is garbage

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/watchman#709]
in line 1014:
https://github.com/facebook/watchman/blob/50298c336855aaa5eee1ba8d6ed8573194e542ac/python/pywatchman/bser.c#L1014

'expected_len' is garbage. 

when in line 1008, called 'bunser_int'  and the function  of bunser_int is defined in line 559

https://github.com/facebook/watchman/blob/50298c336855aaa5eee1ba8d6ed8573194e542ac/python/pywatchman/bser.c#L583

assuming no cases matches to buf[0], return without writing to '*val'.

**Comment by wez** [comment]
Thanks for looking at this!
It is only left uninitialized in the error case, and all callers ignore that value in the error case, so I don't believe that this is a problem in practice
