### ISSUE TITLE
node client should expose API to detect if watchman is present + version compatible

### ISSUE THREAD

**Issue by stefanpenner** [facebook/watchman#71]
If no-one beats me to it, I'll try throwing something together later this week.

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wez** [comment]
I'm closing this in favor of: https://github.com/facebook/watchman/issues/116
