### ISSUE TITLE
Null dereference

### ISSUE THREAD

**Issue by QiAnXinCodeSafe** [facebook/watchman#710]
Null pointer value stored to 'o'
https://github.com/facebook/watchman/blob/c8a74cdce0ad54763a6104ec84aa06bfcf7473f2/opt.cpp#L188

Assuming the condition is false
https://github.com/facebook/watchman/blob/c8a74cdce0ad54763a6104ec84aa06bfcf7473f2/opt.cpp#L190

Access to field 'is_daemon' results in a dereference of a null pointer (loaded from variable 'o')
https://github.com/facebook/watchman/blob/c8a74cdce0ad54763a6104ec84aa06bfcf7473f2/opt.cpp#L197

**Comment by wez** [comment]
This condition cannot be met; `getopt_long` would have returned `?` and we would have already returned earlier.
