### ISSUE TITLE
Please remove -g in the release build

### ISSUE THREAD

**Issue by yurivict** [facebook/watchman#716]

**Comment by wez** [comment]
Please elaborate a bit more?   I'm assuming you are referring to the release build including debug information rather than some other `-g`?
Is there a specific issue you're running into that led to filing this?  Can you explain more about it?

**Comment by yurivict** [comment]
-g is for a debug build, why do you need to add debug information to a binary that is installed by the package for end users to run?

**Comment by wez** [comment]
The debug information improves the quality of stack traces that get logged to the logs in the event of a problem, and makes it easier to support users, so we prefer to always include it.

If you are maintaining a package and do not want this, you can arrange to `strip(1)` the debug information as part of your packaging process.

**Comment by yurivict** [comment]
Ok, thanks!
