### ISSUE TITLE
Suppress info output

### ISSUE THREAD

**Issue by buggymcbugfix** [facebook/watchman#728]
Is it possible to suppress the info output, e.g. `# waiting for changes`?

**Comment by wez** [comment]
Watchman itself doesn't print that so I'm assuming that you're running some other tool; please be as specific as possible about what you're running and in which context as that helps us understand the issue and be better informed in our responses.  Thanks!

**Comment by buggymcbugfix** [comment]
Oh dear, I'm sorry, I meant [`watchman-make`](https://github.com/facebook/watchman/blob/master/python/bin/watchman-make). From looking at its source, there doesn't seem any way of disabling it. I might send a PR for a `-q --quiet` flag if this is likely to get accepted.

**Comment by wez** [comment]
We'll gladly accept a PR for that!
Take a look at https://facebook.github.io/watchman/contributing.html for an important note about our CLA and some other information about contributing

**Comment by wez** [comment]
I'm going to close this feature request; we're still willing to accept a PR but are not going to work on this ourselves.
