### ISSUE TITLE
If path has a space, then the command won't work.

### ISSUE THREAD

**Issue by garyking** [facebook/watchman#736]
If the path in these lines has a space, then copying the command won't work. The path should be quoted, or the spaces should be escaped.

https://github.com/facebook/watchman/blob/4c2ad931b5ca40d8c76277fb9a836ab50385759d/listener-user.cpp#L34-L39

**Comment by LuckyPigeon** [comment]
@garyking Doesn't it has to work like this? Or do you have another good idea for handling the space?

**Comment by garyking** [comment]
The path could be wrapped in quotes, or escape the spaces in the root path by prepending them with backslashes.

**Comment by wez** [comment]
Do you either of you feel like submitting a PR to put single quotes in the appropriate places in that output?
