### ISSUE TITLE
pywatchman: pypi package

### ISSUE THREAD

**Issue by tony** [facebook/watchman#74]
Is it possible to have pywatchman released as python package?  This would be nice to have.

**Comment by wez** [comment]
Sorry for leaving this hanging for so long.   It would be nice to have.  If someone were to contribute the appropriate build/configuration to make it easy to push this at the appropriate time, we'd welcome it.

**Comment by kwlzn** [comment]
@wez I can volunteer to tackle this. would the preferred approach here be to add a top level Makefile target for publishing - or something more local to the ./python subfolder (e.g. a separate Makefile, shell script, python script)?

**Comment by wez** [comment]
@kwlzn Thanks! Probably a `python/publish-pypy.sh` script?  I'm not 100% on what the steps are for this :)

**Comment by tony** [comment]
It'd be a supreme success to get this packaged finally.

@kwlzn : I think the best option would be a ``Makefile`` to package it and a ``.gitignore`` for any work output created by the packaging.  Shell scripts are ok too.

**Comment by kwlzn** [comment]
@wez SGTM. PR out at https://github.com/facebook/watchman/pull/126.

Also, I went ahead and registered the 'pywatchman' project on pypi and published 0.1.1 as an E2E test, so this is live at https://pypi.python.org/pypi/pywatchman. happy to transfer ownership of that over to someone actually associated with the project if you could just supply me one or more pypi user IDs.

**Comment by wez** [comment]
@kwlzn I think it's time I got myself a pypi account ;-)
  
Also: looks like the build failed on the that PR; can you run `make integration`?  We rely on pywatchman in our test harness; there are rules to build the current python module in both Makefile.am and winbuild/Makefile

**Comment by wez** [comment]
I'm now `wez` on pypi

**Comment by kwlzn** [comment]
@wez sweet, added you as owner for the project on pypi - feel free to boot me at will.

Saw and am investigating the CI failure. When I run 'make integration', I get a 'No rule to make target `integration`' - likely due to the fact that Makefile doesn't exist yet. I followed the setup instructions on https://facebook.github.io/watchman/contributing.html up until that point, but couldn't seem to figure out why that wasn't working. any ideas? tried autoconf && configure, but that complains about undefined macros not being able to find an install.sh.

also, I'm hanging out in the #watchman channel on freenode if it's an easier to discuss there.

**Comment by wez** [comment]
Thanks to @kwlzn this is now landed and pywatchman 1.0.0 should be available from pypi.  I'd love it if someone can independently verify that this is working ok before we close out this issue.

A quick simple test program:

```
import pywatchman
client = pywatchman.client()
print(client.query('version'))
```

You will need to have `watchman` installed and available in your path for this to work :-)

**Comment by kwlzn** [comment]
lgtm!

```
[illuminati ~]$ pex pywatchman==1.0.0 -v
  pywatchman 1.0.0:: Resolving distributions :: Packaging pywatchman
pex: Building pex: 1027.2ms                                         
pex:   Resolving distributions: 1018.8ms
pex:       Packaging pywatchman: 301.6ms
Running PEX file at /var/folders/3t/xkwqrkld4xxgklk2s4n41jb80000gn/T/tmpurJo8c with args []
pex: PEX.run invoking /Users/kwilson/Python/CPython-2.7.8/bin/python2.7 /var/folders/3t/xkwqrkld4xxgklk2s4n41jb80000gn/T/tmpurJo8c
Python 2.7.8 (default, Jul 17 2014, 17:43:08) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(InteractiveConsole)
>>> import pywatchman
>>> client = pywatchman.client()
>>> print(client.query('version'))
{'version': '3.1.0'}
>>> 
```

**Comment by wez** [comment]
Alrighty then, thanks!
