### ISSUE TITLE
watchman doesn't work inside rootless container

### ISSUE THREAD

**Issue by oblitum** [facebook/watchman#740]
This is the behavior inside an podman container running ArchLinux:

```
[I] ➜ watchman --foreground --logfile=/dev/stdout
2019-08-21T02:29:34,021: [listener] Watchman 4.9.0 <no build info set> starting up on 381e05761903
2019-08-21T02:29:34,024: [listener] failed to parse json from /tmp/root-state/state: unable to open /tmp/root-state/state: No such file or directory
2019-08-21T02:29:34,024: [listener] chmod(/tmp/root-state/sock, 0600): No such device or address2019-08-21T02:29:34,024: [listener] Exiting from service with res=0
terminate called without an active exception
zsh: abort (core dumped)  watchman --foreground --logfile=/dev/stdout

[I] ➜ ls -lh /tmp
total 12K
drwx--S--- 2 francisco francisco 4.0K Aug 21 02:29 root-state
drwx------ 2 francisco francisco 4.0K Aug 21 02:28 tmux-1000

[I] ➜ sudo rm /tmp/root-state
[sudo] password for francisco:
rm: cannot remove '/tmp/root-state': Is a directory
```

1. No idea why watchman is creating `/tmp/root-state` instead of `/tmp/francisco-state`.
2. This `/tmp/root-state` directory got created with some special permission that doesn't allow me to remove it.

**Comment by oblitum** [comment]
#711 seems related, due to error message.

**Comment by wez** [comment]
I'm not sure exactly what a rootless or podman container is, but from what you've described I think one issue is that your `$USER` env var is incorrectly set to `root` rather than the current user.

Watchman looks at the `$USER` or `$LOGNAME` env vars to determine your username when constructing the path for the state dir (this behavior is compatible with that described by POSIX for how the posix shell determines your username).

Another unusual aspect of your report is this: `chmod(/tmp/root-state/sock, 0600): No such device or address`.  That's very weird.  Is there something special about `/tmp` in that container?  Watchman requires the ability to create a unix domain socket in the statedir.

I also want to note that `/tmp` for statedir is not the default behavior for watchman; the compile time default for the statedir is `/var/run/watchman`.  It sounds like your installation was explicitly built with either `--enable-statedir=no` or `--disable-statedir`.  Whichever location is used must be able to support 

Regarding special permissions: the sticky bit is set on the directory to ensure correct ownership inside the directory.  The reason you can't `rm` that directory is that `rm` cannot remove directories unless you also pass the `-r` flag.

**Comment by oblitum** [comment]
> The reason you can't `rm` that directory is that `rm` cannot remove directories unless you also pass the `-r` flag.

My bad on that, I mistyped. Actually I can't remove it even with `sudo rm -rf`. The relevant error is another one:

```
[I] ➜ sudo rm -rf /tmp/root-state
rm: cannot remove '/tmp/root-state': Directory not empty
```

**Comment by oblitum** [comment]
> I also want to note that `/tmp` for statedir is not the default behavior for watchman; the compile time default for the statedir is `/var/run/watchman`. It sounds like your installation was explicitly built with either `--enable-statedir=no` or `--disable-statedir`. Whichever location is used must be able to support creating unix domain sockets.

OK, I'll  check this one. Even on real machine ArchLinux, it's being put on `/tmp` for me, not `/var/run/watchman`, but it works at least.

**Comment by oblitum** [comment]
> I'm not sure exactly what a rootless or podman container is, but from what you've described I think one issue is that your `$USER` env var is incorrectly set to `root` rather than the current user.
> 
> Watchman looks at the `$USER` or `$LOGNAME` env vars to determine your username when constructing the path for the state dir (this behavior is compatible with that described by POSIX for how the posix shell determines your username).

I'll have to check why this is happening inside the container, you're right  about it. `$USER` is empty and `$LOGNAME` has root, which is weird. Thanks for the info.

**Comment by wez** [comment]
> My bad on that, I mistyped. Actually I can't remove it even with `sudo rm -rf`. The relevant error is another one:
> 
> ```
> [I] ➜ sudo rm -rf /tmp/root-state
> rm: cannot remove '/tmp/root-state': Directory not empty
> ```

That sounds very broken.  Can you share the output from `mount` in that container?  I'm curious about what `/tmp` actually is in that environment.

I wonder if `/tmp` is mounted with `nodev` and if that is the root cause of this.  It wouldn't surprise me if `nodev` is required for a rootless container because of the security concerns.

You can google for `podman nodev` and find other weird stories, like: https://github.com/containers/libpod/issues/1303

**Comment by wez** [comment]
This issue may also be relevant: https://github.com/containers/libpod/issues/3816

**Comment by oblitum** [comment]
> Can you share the output from mount in that container?

```
[I] ➜ mount
fuse-overlayfs on / type fuse.fuse-overlayfs (rw,nodev,noatime,user_id=0,group_id=0,default_permissions,allow_other)
proc on /proc type proc (rw,nosuid,nodev,noexec,relatime)
tmpfs on /dev type tmpfs (rw,nosuid,size=65536k,mode=755,uid=1000,gid=1000)
sysfs on /sys type sysfs (ro,nosuid,nodev,noexec,relatime)
devpts on /dev/pts type devpts (rw,nosuid,noexec,relatime,gid=100004,mode=620,ptmxmode=666)
mqueue on /dev/mqueue type mqueue (rw,nosuid,nodev,noexec,relatime)
shm on /dev/shm type tmpfs (rw,nosuid,nodev,noexec,relatime,size=64000k,uid=1000,gid=1000)
tmpfs on /etc/hostname type tmpfs (rw,nosuid,nodev,relatime,size=1635524k,mode=700,uid=1000,gid=1000)
tmpfs on /run/.containerenv type tmpfs (rw,nosuid,nodev,relatime,size=1635524k,mode=700,uid=1000,gid=1000)
tmpfs on /etc/resolv.conf type tmpfs (rw,nosuid,nodev,relatime,size=1635524k,mode=700,uid=1000,gid=1000)
tmpfs on /etc/hosts type tmpfs (rw,nosuid,nodev,relatime,size=1635524k,mode=700,uid=1000,gid=1000)
tmpfs on /sys/fs/cgroup type tmpfs (ro,nosuid,nodev,noexec,relatime,mode=755,uid=1000,gid=1000)
cgroup on /sys/fs/cgroup/systemd type cgroup (ro,nosuid,nodev,noexec,relatime,xattr,name=systemd)
cgroup on /sys/fs/cgroup/blkio type cgroup (ro,nosuid,nodev,noexec,relatime,blkio)
cgroup on /sys/fs/cgroup/freezer type cgroup (ro,nosuid,nodev,noexec,relatime,freezer)
cgroup on /sys/fs/cgroup/hugetlb type cgroup (ro,nosuid,nodev,noexec,relatime,hugetlb)
cgroup on /sys/fs/cgroup/memory type cgroup (ro,nosuid,nodev,noexec,relatime,memory)
cgroup on /sys/fs/cgroup/rdma type cgroup (ro,nosuid,nodev,noexec,relatime,rdma)
cgroup on /sys/fs/cgroup/devices type cgroup (ro,nosuid,nodev,noexec,relatime,devices)
cgroup on /sys/fs/cgroup/net_cls,net_prio type cgroup (ro,nosuid,nodev,noexec,relatime,net_cls,net_prio)
cgroup on /sys/fs/cgroup/perf_event type cgroup (ro,nosuid,nodev,noexec,relatime,perf_event)
cgroup on /sys/fs/cgroup/cpu,cpuacct type cgroup (ro,nosuid,nodev,noexec,relatime,cpu,cpuacct)
cgroup on /sys/fs/cgroup/pids type cgroup (ro,nosuid,nodev,noexec,relatime,pids)
cgroup on /sys/fs/cgroup/cpuset type cgroup (ro,nosuid,nodev,noexec,relatime,cpuset,clone_children)
dev on /dev/null type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /dev/random type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /dev/full type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /dev/tty type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /dev/zero type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /dev/urandom type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
devpts on /dev/console type devpts (rw,nosuid,noexec,relatime,gid=100004,mode=620,ptmxmode=666)
proc on /proc/asound type proc (ro,relatime)
proc on /proc/bus type proc (ro,relatime)
proc on /proc/fs type proc (ro,relatime)
proc on /proc/irq type proc (ro,relatime)
proc on /proc/sys type proc (ro,relatime)
proc on /proc/sysrq-trigger type proc (ro,relatime)
tmpfs on /proc/acpi type tmpfs (ro,relatime,uid=1000,gid=1000)
dev on /proc/kcore type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /proc/keys type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /proc/latency_stats type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /proc/timer_list type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
dev on /proc/sched_debug type devtmpfs (rw,nosuid,relatime,size=8167224k,nr_inodes=2041806,mode=755)
tmpfs on /proc/scsi type tmpfs (ro,relatime,uid=1000,gid=1000)
tmpfs on /sys/firmware type tmpfs (ro,relatime,uid=1000,gid=1000)
```

**Comment by wez** [comment]
I think https://github.com/containers/libpod/issues/3816 might be the real issue; sounds like you need to upgrade (or maybe downgrade?) fuse-overlayfs

**Comment by oblitum** [comment]
Thanks for pointing that. I'm running fuse-overlayfs 0.5, I've upgrade to 0.5.2, this changed behavior and it's not core dumping anymore. I've export `$USER` and `$LOGNAME` manually and tried it again and got:

```
[I] ➜ watchman --foreground --logfile=/dev/stdout
2019-08-21T04:38:57,278: [listener] Watchman 4.9.0 <no build info set> starting up on c1bc00327c36
2019-08-21T04:38:57,278: [listener] failed to parse json from /tmp/francisco-state/state: unable to open /tmp/francisco-state/state: No such file or directory
```

I'm not sure whether it's actually functional now. I don't use watchman directly at the moment,  it's a dependency of another tool, and it seems this tool isn't complaining anymore. I whatever case, I think this is more an issue with the other stuff than watchman itself. Thanks for the help.
