### ISSUE TITLE
Broken Windows Zip Download

### ISSUE THREAD

**Issue by jason-hunt** [facebook/watchman#741]
The Windows .zip file download is broken:
https://ci.appveyor.com/api/buildjobs/vkp4mmk1cri9jsel/artifacts/watchman.zip

results in:

<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:...... Time:2019-09-06.....
</Error>

**Comment by Toni111111** [comment]
yes , i also have it problem.

**Comment by landauchos** [comment]
This XML file does not appear to have any style information associated with it. The document tree is shown below.

**Comment by paulmains** [comment]
Yeah this is still broken, does anyone know any other means to download this?

**Comment by rmswns0413** [comment]
plz.. answer me other ways to download

**Comment by minhdongsss** [comment]
Not good for us :(

**Comment by jason-hunt** [comment]
FYI, there's another issue logged that identifies how to find a working build of this:
https://github.com/facebook/watchman/issues/683

**Comment by paulmains** [comment]
> FYI, there's another issue logged that identifies how to find a working build of this:
> #683

Thanks for the direction, I'll try that out.

**Comment by alexjosesilva** [comment]
download link broken...please!

**Comment by luizcarloscavalcanti** [comment]
download link broken...

**Comment by KOR-xoxo** [comment]
제발

**Comment by nathantaal** [comment]
14 days for a broken download link...

**Comment by bonetti** [comment]
Same here.. some one to help ?

**Comment by nathantaal** [comment]
> Same here.. some one to help ?

Follow @jason-hunt instructions if you need watchman on Windows now

**Comment by shiwani** [comment]
Zeldafreak in this thread has pointed this :https://ci.appveyor.com/project/wez/watchman/builds/24658997/artifacts
