### ISSUE TITLE
FileDescriptor.o compilation issue on OSX 10.7

### ISSUE THREAD

**Issue by bitsandnumbers** [facebook/watchman#745]
Hi,

I'm trying to compile Watchman on an old macbook that run on 10.7 and I get the following error whether I try compiling directly from sources or from MacPorts :

`  CXX      watchman-FileDescriptor.o
FileDescriptor.cpp: In function 'watchman::FileInformation watchman::getFileInformation(const char*, watchman::CaseSensitivity)':
FileDescriptor.cpp:663:56: error: 'AT_SYMLINK_NOFOLLOW' was not declared in this scope
         handle.fd(), pathPiece.baseName().data(), &st, AT_SYMLINK_NOFOLLOW)) {
                                                        ^
FileDescriptor.cpp:663:75: error: 'fstatat' was not declared in this scope
         handle.fd(), pathPiece.baseName().data(), &st, AT_SYMLINK_NOFOLLOW)) {
                                                                           ^
make[1]: *** [Makefile:3339: watchman-FileDescriptor.o] Error 1`

Is 10.7 really not supported anymore or is there a way to make it work ? Thanks

**Comment by wez** [comment]
We don't support 10.7 any more.  You can try checking out one of the older releases and building that; `git tags` should list the available releases; maybe `v4.7.0` will work for you?

**Comment by bitsandnumbers** [comment]
@wez ok thank you, that's what I thought... I'll try as you suggest then.
