### ISSUE TITLE
watchman package not found

### ISSUE THREAD

**Issue by tarungupta5966** [facebook/watchman#746]
unable to found the watchman package for windows on the link from its docs section.
 the following error is occured:

This XML file does not appear to have any style information associated with it. The document tree is shown below.
<Error>
<Code>BlobNotFound</Code>
<Message>
The specified blob does not exist. RequestId:8e6344f1-a01e-0044-77dc-766688000000 Time:2019-09-29T15:39:48.0864479Z
</Message>
</Error>

please do resolve the issue as soon as possible.

**Comment by drevoluti** [comment]
solution ?
