### ISSUE TITLE
Watchman crawl failed. After MacOS Catalina Update 

### ISSUE THREAD

**Issue by t-castanho** [facebook/watchman#751]
After the MacOS update and zsh terminal change i can't run my app with npm start even with a watchman blank file. I'm getting this error:
```
jest-haste-map:` Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file 
in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: resolve_projpath: path `(mypath)`: open: (mypath): Operation 
not permitted. Make sure watchman is running for this project. 
See https://facebook.github.io/watchman/docs/troubleshooting.html.
```
Should i downgrade? Or there is any fix for this?

**Comment by rocketaero** [comment]
I had the same problem.  I moved the entire project directory outside of the Documents directory and it solved the problem.  Appears to be something related to the new permissions catalina requires for access to the Documents directory.

**Comment by t-castanho** [comment]
Where do you paste your project? I’ve my project in the desktop directory. Can we remove the permissions?

**Comment by rocketaero** [comment]
I think the Desktop has similar problems as Documents, I moved mine to my root user directory 
(  /Users/{myuser}  ) and it worked.

**Comment by wez** [comment]
See also: https://stackoverflow.com/questions/58318341/why-watchman-crawl-failed-error-in-react-native-immediately-after-updating-to

**Comment by nickwelp** [comment]
Is there anyway to change the permissions for the Document folder for Catalina? I didn't recognize it when, upon updating, I was immeaditely prompted to allow access. I planned to Google it later... but then I've not had that prompt since.

**Comment by jaeseonglee1008** [comment]
Guys. I spent hours to figure this out. I found a solution. 
I you still face this problem after you re-install node, watchman and expo cli etc, You gotta try this simple step. Trust me. Its all bcuz of catalina grant access to folders permission.

First, Kill all the server running and close your terminal.
Go to 'System preference' -> 'Security & Privacy' -> scroll down and click 'Full Disk Access' -> Make sure you checked on 'Terminal' and 'Watchman'. Save and restart ur laptop.

You are welcome.

**Comment by SaravanakumarSubramanian** [comment]
@jaeseonglee1008 Worked for me!! kudos man!!

**Comment by IgorUsoltsev** [comment]
> I think the Desktop has similar problems as Documents, I moved mine to my root user directory
> ( /Users/{myuser} ) and it worked.

this one solved it for me. 

Tried all the stuff from "Full disk access" to reinstall, chmod etc. But moving project under {user} folder solved all the issues. Damn Catalina's new security rules. Spent few days on that.

**Comment by webhaoying** [comment]
> To change the permissions for Watchman regarding the Documents folder, it's under Security & Privacy -> files & folders in the system preferences

thanks ,fixed

**Comment by grangerjs** [comment]
> Guys. I spent hours to figure this out. I found a solution.
> If you still face this problem after you re-install node, watchman and expo cli etc, You gotta try this simple step. Trust me. Its all bcuz of catalina grant access to folders permission.
> 
> First, Kill all the server running and close your terminal.
> Go to 'System preference' -> 'Security & Privacy' -> scroll down and click 'Full Disk Access' -> Make sure you checked on 'Terminal' and 'Watchman'. Save and restart ur laptop.
> 
> You are welcome.

This was it. THANK YOU.

**Comment by lalidiaz** [comment]
> To change the permissions for Watchman regarding the Documents folder, it's under Security & Privacy -> files & folders in the system preferences

Thank you so much :)

**Comment by rplotkin** [comment]
> Guys. I spent hours to figure this out. I found a solution.
> If you still face this problem after you re-install node, watchman and expo cli etc, You gotta try this simple step. Trust me. Its all bcuz of catalina grant access to folders permission.
> 
> First, Kill all the server running and close your terminal.
> Go to 'System preference' -> 'Security & Privacy' -> scroll down and click 'Full Disk Access' -> Make sure you checked on 'Terminal' and 'Watchman'. Save and restart ur laptop.
> 
> You are welcome.

This was it.  Thank you!

**Comment by ismailkhan4** [comment]
How to change fix the issue in Ubuntu? :(

**Comment by nikhilthakur001** [comment]
> > I think the Desktop has similar problems as Documents, I moved mine to my root user directory
> > ( /Users/{myuser} ) and it worked.
> 
> this one solved it for me.
> 
> Tried all the stuff from "Full disk access" to reinstall, chmod etc. But moving project under {user} folder solved all the issues. Damn Catalina's new security rules. Spent few days on that.

Same, this only solved my problem, but there should be a better solution. I cannot move all my react-native project to /User/{myuser}.

**Comment by DavidPhilip** [comment]
@nikhilthakur001 What actually solved this for me was that I needed to run `watchman shutdown-server` after doing all of the above. When I fired it up again I got the OS's disk-access permission dialog which I confirmed and everything started to work as expected.

**Comment by himanshuzeptonow** [comment]
> I think the Desktop has similar problems as Documents, I moved mine to my root user directory ( /Users/{myuser} ) and it worked.

Worked for me as well

**Comment by shubhamRai12** [comment]
> > > I think the Desktop has similar problems as Documents, I moved mine to my root user directory
> > > ( /Users/{myuser} ) and it worked.
> > 
> > 
> > this one solved it for me.
> > Tried all the stuff from "Full disk access" to reinstall, chmod etc. But moving project under {user} folder solved all the issues. Damn Catalina's new security rules. Spent few days on that.
> 
> Same, this only solved my problem, but there must be a better solution. I manage all my projects in Documents/projects. It would not be possible to move all my react-native projects to /User/{myuser}.

Worked for me also. Thanks.

**Comment by ui-code** [comment]
I'm using Mac with Apple M1 chip.
As of today, 25th Nov 2022, none of the above worked for me, until I came across this post:

https://www.spinellis.gr/blog/20211127/

According to which, we need to add path of homebrew within project's build phases, so that watchman is picked up while xcode archives the project:
export PATH="$PATH:/opt/homebrew/bin"

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/66790061/203906201-f9035eac-cbfe-4de9-813a-1ff6bb288b2d.png">

**Comment by NutNick31** [comment]
One solution that I found was really helpful,
1. Go to the root directory of you application
2. Run the command ```watchman watch .```
3. Start the app ```npx expo start``` or ```npx expo start --tunnel```

It should work fine
