### ISSUE TITLE
Travis build failures

### ISSUE THREAD

**Issue by abitrolly** [facebook/watchman#752]
Travis builds for `master` are red for a long time https://travis-ci.org/facebook/watchman/builds Does that mean that `watchman` builds are broken on Linux?

**EDIT**: The build was broken in [Feb 2019](https://github.com/facebook/watchman/commits/master?after=658e9ec680fe7691e1fe1d136180b282511a301a+925) - most likely by https://github.com/facebook/watchman/commit/631bdda241a136d975883de7d78aacce59dc0721.

**Comment by wez** [comment]
Fixed by effectively deleting the travis build config :-p
