### ISSUE TITLE
link to watchman.zip for windows broken.

### ISSUE THREAD

**Issue by robertsmit** [facebook/watchman#755]

**Comment by piyushspss** [comment]
The link to download the Watchman.zip =>  https://ci.appveyor.com/api/buildjobs/vkp4mmk1cri9jsel/artifacts/watchman.zip  is not available.

**Comment by woss** [comment]
i have the same prob, solved it by installing nightly build with [scoop](https://scoop.sh/)

`scoop install watchman-nightly`

I hope that helps

**Comment by mcottingham** [comment]
I tried that, but it didn't work for me.

![image](https://user-images.githubusercontent.com/3824600/67624624-38488800-f7f0-11e9-95d7-c9c26b5fa0c9.png)

**Comment by Sureiya** [comment]
> I tried that, but it didn't work for me.

You need to add the 'extras' bucket

```ps
scoop bucket add extras
scoop install watchman-nightly
```

For those who don't have scoop and just want to get watchman installed quickly.

```ps
scoop bucket add extras
scoop install watchman-nightly
iwr -useb get.scoop.sh | iex
```

**Comment by riazXrazor** [comment]
![image](https://user-images.githubusercontent.com/13194363/68046621-4f144080-fd02-11e9-91fc-4a3503fb27b6.png)
tried it unable to install

**Comment by Sureiya** [comment]
> ![image](https://user-images.githubusercontent.com/13194363/68046621-4f144080-fd02-11e9-91fc-4a3503fb27b6.png)
> tried it unable to install

Are you on win7?

**Comment by riazXrazor** [comment]
nope win10

**Comment by riazXrazor** [comment]
> > ![image](https://user-images.githubusercontent.com/13194363/68046621-4f144080-fd02-11e9-91fc-4a3503fb27b6.png)
> > tried it unable to install
> 
> Are you on win7?
nope win10

found a link here 
https://github.com/facebook/watchman/issues/741
https://ci.appveyor.com/project/wez/watchman/builds/24658997/artifacts
