### ISSUE TITLE
Installation - Github Actions is only accessable if logged in on github.com 

### ISSUE THREAD

**Issue by daniel-svensson-aa** [facebook/watchman#765]
When on the installation page https://facebook.github.io/watchman/docs/install.html and following the install instructions below

![image](https://user-images.githubusercontent.com/58296429/69805068-276ca700-11e0-11ea-8b96-608127327975.png)
I come to a 404 page on github

![image](https://user-images.githubusercontent.com/58296429/69805112-45d2a280-11e0-11ea-8a79-4d5e1945d083.png)

Clearly, this is an error on githubs side, they should not give me a 404 if I'm not logged in, they should ask me to log in.
But until they have sorted that out, it would be nice if watchman supplied a workaround.

**Suggestion** Clarify on the install page https://facebook.github.io/watchman/docs/install.html that you need to be logged in to github to be able to access the actions section.

**Comment by kumarharsh** [comment]
Agreed. Maybe it should be made so that the CI artifacts are automatically uploaded to Github releases.

**Comment by wez** [comment]
Starting today, we have weekly tags with binaries uploaded to them: https://github.com/facebook/watchman/releases/latest
