### ISSUE TITLE
size of file and permission to open

### ISSUE THREAD

**Issue by misbell** [facebook/watchman#768]
in artifacts dropdown, size of 5.54 mb is shown.
actual download says 63mb in safari download list.
shows zero bytes in finder.
double clicking on it shows either no files in subdir, or you get a permissions error and zip won't open.
using macos catalina, latest production build.

**Comment by misbell** [comment]
![2019-12-07 at 4 21 PM](https://user-images.githubusercontent.com/356572/70380720-939c8880-190d-11ea-9637-6e08d6daf413.jpg)
![2019-12-07 at 4 20 PM](https://user-images.githubusercontent.com/356572/70380713-8b444d80-190d-11ea-8476-7c88b6cf2a56.jpg)

![2019-12-07 at 4 21 PM](https://user-images.githubusercontent.com/356572/70380734-b0d15700-190d-11ea-971b-aa44c068b69c.jpg)

**Comment by misbell** [comment]
![2019-12-07 at 4 23 PM](https://user-images.githubusercontent.com/356572/70380747-e2e2b900-190d-11ea-8a31-31cf67d8b1fa.jpg)

**Comment by misbell** [comment]
I changed permissions on the folder and got access to it

**Comment by wez** [comment]
This sounds like a local download issue so I'm closing this out.
