### ISSUE TITLE
watchman CI  artifacts download failed.

### ISSUE THREAD

**Issue by liudonghua123** [facebook/watchman#771]
I tried to download the latest windows binaries on https://github.com/facebook/watchman/runs/351164043.

![image](https://user-images.githubusercontent.com/2276718/71453242-36d21680-27c5-11ea-9ab4-2cc18dcf4f48.png)

But When I click the link and try to download, the downloaded file changes everytime. I have tried many times, all failed.

![image](https://user-images.githubusercontent.com/2276718/71453297-8284c000-27c5-11ea-8dcd-6cabab85aaaf.png)

Could we publish the files in the github release. It is more easy for downloading.

**Comment by jamolkhon** [comment]
Watchman is required for Flipper.  I can't believe this is still unresolved. It's been more than 2 months.

**Comment by Lexicality** [comment]
I'm able to download https://github.com/facebook/watchman/suites/423326153/artifacts/1382043 and extract it with 7zip without trouble?

**Comment by milesrichardson** [comment]
It seems like the artifacts link only works when you are authenticated to GitHub. So for example, simply downloading via curl will not be sufficient.

**Comment by liudonghua123** [comment]
@milesrichardson Hi, I have logined to Github, but the problem still exists.

Can we push the binary to the release page? It's more easier for downloading.

**Comment by milesrichardson** [comment]
@woopla I got watchman to work in docker a few weeks ago. I was just testing it, and am not running this in production (no guarantees), but it builds. You still need to figure out how to configure watchman. But, feel free to use it as a starting point

## `build_watchman.sh`

```bash
#!/usr/bin/env bash

THIS_DIR="$(cd -P -- "$(dirname -- "$0")" && pwd -P)"

WATCHMAN_TAG="${WATCHMAN_TAG-"v4.9.0"}"

export DOCKER_BUILDKIT=1
docker build "$THIS_DIR" -f watchman.dockerfile \
    --build-arg WATCHMAN_TAG"=${WATCHMAN_TAG}" \
    -t acmeco/watchman:${WATCHMAN_TAG} \
&& docker tag acmeco/watchman:${WATCHMAN_TAG} acmeco/watchman:latest \
&& exit 0

exit 1
```

### `watchman.dockerfile`

```dockerfile
# syntax = docker/dockerfile:experimental

FROM ubuntu:latest AS build_phase

RUN --mount=type=cache,target=/var/cache/apt --mount=type=cache,target=/var/lib/apt apt-get update -qq \
    && apt-get install -yy \
    wget \
    autoconf \
    automake \
    build-essential \
    git \
    libssl-dev \
    libtool \
    pkg-config \
    python-dev \
    python-setuptools

ARG WATCHMAN_TAG=v4.9.0

RUN git clone https://github.com/facebook/watchman.git -b "${WATCHMAN_TAG}" --depth 1

RUN cd watchman \
    && ./autogen.sh \
    && ./configure \
    && make \
    && make install

FROM ubuntu:latest

COPY --from=build_phase \
    /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 \
    /usr/lib/x86_64-linux-gnu/libstdc++.so.6 \
    /usr/lib/x86_64-linux-gnu/

COPY --from=build_phase /lib64/ld-linux-x86-64.so.2 /lib64/ld-linux-x86-64.so.2

COPY --from=build_phase /lib/x86_64-linux-gnu/libpthread.so.0 \
    /lib/x86_64-linux-gnu/libgcc_s.so.1 \
    /lib/x86_64-linux-gnu/libc.so.6 \
    /lib/x86_64-linux-gnu/libdl.so.2 \
    /lib/x86_64-linux-gnu/libm.so.6 \
    /lib/x86_64-linux-gnu/

COPY --from=build_phase /watchman/watchman /usr/local/bin

ENTRYPOINT ["watchman"]
```

**Comment by woopla** [comment]
Thanks, @milesrichardson. I started playing with the Docker instance, but the container kept erroring out because it could not create files in `/usr/local/var/run`. That looked weird to me (`var` belongs to `/`, never saw it in `/usr/local`), plus I wanted this to be available from CentOS 6.x anyway (Docker ain't properly supported there).

In the end, I got it working natively by using the DTS6 compiler collection from RedHat, along with `./configure --enable-lenient` and a patch to get a test to pass. I gleaned the last two items from other issues on Github.

**Comment by wez** [comment]
Starting today, we have weekly tags with binaries uploaded to them: https://github.com/facebook/watchman/releases/latest

**Comment by woopla** [comment]
@wez you need to build the `watchman` binary differently:
```bash
> ldd bin/watchman
	linux-vdso.so.1 (0x00007fff2cf68000)
	/usr/local/lib/libgflags.so.2.2 => not found
	/usr/local/lib/libglog.so.0 => not found
	libcrypto.so.1.1 => /lib64/libcrypto.so.1.1 (0x00007f75dd71f000)
	libdl.so.2 => /lib64/libdl.so.2 (0x00007f75dd51b000)
	libpthread.so.0 => /lib64/libpthread.so.0 (0x00007f75dd2fb000)
	libstdc++.so.6 => /lib64/libstdc++.so.6 (0x00007f75dcf66000)
	libm.so.6 => /lib64/libm.so.6 (0x00007f75dcbe4000)
	libgcc_s.so.1 => /lib64/libgcc_s.so.1 (0x00007f75dc9cc000)
	libc.so.6 => /lib64/libc.so.6 (0x00007f75dc609000)
	libz.so.1 => /lib64/libz.so.1 (0x00007f75dc3f2000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f75e8572000)
```

The libraries search path should not be `/usr/local/lib`, because that forces me to put them there, not on (say) an NFS mount so it's available to our thousands of hosts that our users might choose.

**Comment by wez** [comment]
These binaries are built for deployment to `/usr/local/`.
I have a doc update pending review that will explain this a bit better.
For relocatable watchman, my rough plan is to ship an AppImage so that it is self contained and can run from anywhere.

**Comment by woopla** [comment]
AppImage ain't gonna work :( We still (sigh) have a lot of CentOS 6.x boxes... Guess I'll have to keep building it manually :)

**Comment by sluongng** [comment]
Support for centos would be nice. We also have a lot of centos 7 and soon 8 boxes

**Comment by anderspitman** [comment]
> I have a doc update pending review that will explain this a bit better. For relocatable watchman, my rough plan is to ship an AppImage so that it is self contained and can run from anywhere.

@wez did this ever get explained anywhere by chance? I'm trying to figure out why watchman hard codes /usr/local, which prevents things like LD_LIBRARY_PATH.

Here's some context: https://github.com/orgs/Homebrew/discussions/5371

Any insight or docs you can point me to would be greatly appreciated.

**Comment by wez** [comment]
FWIW, I haven't worked on this project in several years, and no longer work at FB. As a result, I'm sorry to say that I have no personal incentive to spend the time required to dig into the current state of the code to figure out what it is doing in order to be able to respond to this question.

**Comment by anderspitman** [comment]
Definitely don't think you should waste time looking through the current code. This specific issue seems like a fundamental design decision from the early days of watchman. Even answering to the best of your memory might be very helpful for me tracking down my issue.

**Comment by wez** [comment]
At compile time, you control what the installation path is defined to be. If homebrew is compiling watchman, it in theory can control that definition.
