### ISSUE TITLE
CMake Error at CMakeLists.txt:306 (find_package), while running ./autogen.sh

### ISSUE THREAD

**Issue by fayaz07** [facebook/watchman#781]
CMake Error at CMakeLists.txt:306 (find_package):
  Could not find a package configuration file provided by "fmt" with any of
  the following names:

    fmtConfig.cmake
    fmt-config.cmake

  Add the installation prefix of "fmt" to CMAKE_PREFIX_PATH or set "fmt_DIR"
  to a directory containing one of the above files.  If "fmt" provides a
  separate development package or SDK, be sure it has been installed.

-- Configuring incomplete, errors occurred!
See also "/home/fayaz/watchman/CMakeFiles/CMakeOutput.log".

**Comment by JanuaryThomas** [comment]
Before running ./autogen.sh 
run `git checkout v4.9.0`

**Comment by wez** [comment]
This is fixed in master.  The newer cmake build process does still need docs; there are a few things we're tidying up before writing those up.
