### ISSUE TITLE
single argument use gives "error": "wrong number of arguments"

### ISSUE THREAD

**Issue by pjgoodall** [facebook/watchman#783]
```
% sudo watchman clock
{
    "cli_validated": true,
    "version": "4.9.0",
    "error": "wrong number of arguments"
}
```
same for `get-config`
```
 % lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 18.04.4 LTS
Release:	18.04
Codename:	bionic
```

**Comment by wez** [comment]
Both [`clock`](https://facebook.github.io/watchman/docs/cmd/clock.html) and [`get-config`](https://facebook.github.io/watchman/docs/cmd/get-config.html) require a project path as an argument, so it is expected to see that error when not enough parameters are provided.

The docs show examples of correct usage:
https://facebook.github.io/watchman/docs/cmd/clock.html
https://facebook.github.io/watchman/docs/cmd/get-config.html

**Comment by pjgoodall** [comment]
Thanks Wez
