### ISSUE TITLE
Adding all directories to watch OS X

### ISSUE THREAD

**Issue by Zainpro** [facebook/watchman#786]
Hi,
Apologies this is more a question than a problem...
I am trying to watch all directories for any changes in OS X Mac book and creating a state configuration:
Is there a default configuration for all files/folders or Do we have to create one specific? Do I use:

watchman watch /

Then to check changes do I use 

watchman watch-list 

For instance using the following:

 watchman watch /Library\
> 
{
    "version": "4.9.0",
    "error": "unable to resolve root /Library: \"/Library\" resolved to \"/Library\" but we were unable to examine \"/Library\" using strict case sensitive rules.  Please check each component of the path and make sure that that path exactly matches the correct case of the files on your filesystem."
}

Please help
Thanks in advance

**Comment by wez** [comment]
We do not allow watching `/`; it is too expensive and macOS won't schedule watchman with a high enough priority to keep up with every single file change on the entire system.

Regarding `/Library`, are you on macOS Catalina?  It has some magic with system protected paths that can affect canonicalization.   Watching system paths isn't part of our main use case so we haven't looked into exactly what is going on there.

The intended purpose is that you watch specific projects (such as source code repos) and usually through some higher level tooling, such as the `hg` or `git` `fsmonitor` extensions, or with utilities like [`watchman-make`](https://facebook.github.io/watchman/docs/watchman-make).

Most users will not manually interact with the `watchman` CLI directly.
