### ISSUE TITLE
watchman-make binary is missing

### ISSUE THREAD

**Issue by NV** [facebook/watchman#792]
`watchman-make` is documented on https://facebook.github.io/watchman/docs/watchman-make, which doesn't say how to install it.

I just installed watchman from Macports. It didn't install `watchman-make` binary. I couldn't find `watchman-make` in the latest CI build either.

**Comment by wez** [comment]
We don't maintain macports; I suspect they have a really old version of watchman.  I'd recommend installing from homebrew if you can.

That said, `watchman-make` is just a python program that uses `pywatchman`; you could try grabbing it from the repo: https://github.com/facebook/watchman/blob/master/python/bin/watchman-make and if macports installs pywatchman maybe it will just run, but if not, you might be able to `pip install pywatchman` if your system is set up for that.

**Comment by NV** [comment]
Perhaps https://facebook.github.io/watchman/docs/watchman-make should mention that `watchman-make` isn't included in CI builds, at least.

**Comment by wez** [comment]
I actually have some diffs queued up on master internally that build the `watchman-XXX` utilities in our cmake build, so these may start showing up in the CI artifact bundles as a side effect.
