### ISSUE TITLE
Watch on mounted volume

### ISSUE THREAD

**Issue by MichZipp** [facebook/watchman#795]
Hi,

is it possible to use watchman to watch on a mounted folder? It works if I change a file in the mounted folder on the same machine where watchman is running. However, If I change a file in the same mounted folder on another machine, it doesn't work.

Best,
Michael

**Comment by wez** [comment]
This is mentioned in the installation requirements section of the docs:

https://facebook.github.io/watchman/docs/install
> Watchman relies on the operating system facilities for file notification, which means that you will likely have very poor results using it on any kind of remote or distributed filesystem.

In practice what we've observed is that your kernel will generally report changes that originate from the local machine (but this is not guaranteed!) and nothing for network mounts.  Most network filesystems protocols lack support for pushing change notifications over the wire so this is physically impossible to make work in a scalable manner.

**Comment by MichZipp** [comment]
Alright, thanks for the information!
