### ISSUE TITLE
Support for piping BSER into CLI (akin to -j)

### ISSUE THREAD

**Issue by cstrahan** [facebook/watchman#80]
It would be nice to be able to pipe BSER serialized commands into the CLI for commands like `get-sockname`. Right now, there's `-j` for piping in JSON, but there doesn't seem to a be a BSER analogue.

(The idea is that it would remove a dependency on a JSON parsing lib in my applications.)

**Comment by facebook-github-bot-6** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wez** [comment]
This is something that might get a bit easier once the Windows branch is merged in, which I'm planning to do after we tag and release 3.7 this week

**Comment by wez** [comment]
This will ship in version 3.8

**Comment by HARLEY1988** [comment]
Help me
