### ISSUE TITLE
Unable to make on SLES 12

### ISSUE THREAD

**Issue by purvimisal** [facebook/watchman#803]
I am getting the Error.  Help needed. 

make
make  all-am
make[1]: Entering directory '/data1/GDPRDATA/watchman'
cd python && /usr/bin/python ./setup.py clean build_py -c -d . build_ext -i
running clean
removing 'build/temp.linux-x86_64-2.7' (and everything under it)
removing 'build'
running build_py
running build_ext
building 'pywatchman.bser' extension
creating build
creating build/temp.linux-x86_64-2.7
creating build/temp.linux-x86_64-2.7/pywatchman
gcc -pthread -fno-strict-aliasing -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DNDEBUG -fmessage-length=0 -grecord-gcc-switches -fstack-protector -O2 -Wall -D_FORTIFY_SOURCE=2 -funwind-tables -fasynchronous-unwind-tables -fstack-clash-protection -g -DOPENSSL_LOAD_CONF -fwrapv -fPIC -I/usr/include/python2.7 -c pywatchman/bser.c -o build/temp.linux-x86_64-2.7/pywatchman/bser.o
pywatchman/bser.c:31:20: fatal error: Python.h: No such file or directory
#include <Python.h>
                   ^
compilation terminated.
error: command 'gcc' failed with exit status 1
Makefile:5040: recipe for target 'py-build' failed
make[1]: *** [py-build] Error 1
make[1]: Leaving directory '/data1/GDPRDATA/watchman'
Makefile:1089: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by wez** [comment]
it sounds like you need to install the python-devel or equivalent package for your system so that the python headers can be found

**Comment by purvimisal** [comment]
you're right. it was that. Got it to work now! thanks
