### ISSUE TITLE
Ridiculously large Linux binary

### ISSUE THREAD

**Issue by dandv** [facebook/watchman#804]
Really, 182MB to watch for file changes?! What goes in there, a whole distro, including a filesystem?

![image](https://user-images.githubusercontent.com/33569/79941919-a4632a80-84b9-11ea-883c-ea7ca35189b4.png)

This is from [the latest artifact](https://facebook.github.io/watchman/docs/install/#buildinstall). Please tell me something has gone wrong and that's an outlier version or something.

**Comment by wez** [comment]
It's debug information produced by the `RelWithDebInfo` cmake build mode that we're using.  You can `strip` the binary to bring it down to a more reasonable size.  We'll get the CI to do that automatically.

**Comment by wez** [comment]
We're down to about 2.5MB now:
https://github.com/facebook/watchman/actions/runs/91748642
