### ISSUE TITLE
Artifacts are not available to download (Expired).

### ISSUE THREAD

**Issue by RandunuK** [facebook/watchman#810]
I've followed the instructions on [#download-for-windows-beta](https://facebook.github.io/watchman/docs/install#download-for-windows-beta) and I couldn't download the artifact. Artifact page says "The following artifacts have expired and are no longer able to be downloaded."

Artifact page link : [https://github.com/facebook/watchman/actions/runs/32012692](https://github.com/facebook/watchman/actions/runs/32012692)

**Comment by wez** [comment]
We just split the CI job into separate platform jobs, but haven't updated the docs yet.
You can find the current latest windows build here:
https://github.com/facebook/watchman/actions/runs/92555802

**Comment by wez** [comment]
Starting today, we have weekly tags with binaries uploaded to them: https://github.com/facebook/watchman/releases/latest
