### ISSUE TITLE
Watchman has screwed me

### ISSUE THREAD

**Issue by CrownRock** [facebook/watchman#819]
I lost all my commits and even worse now I can't run Expo to get my React Native project running. Here's the error: 
![image](https://user-images.githubusercontent.com/43010311/83705357-efe91800-a5d1-11ea-9cb0-e11f6caefed7.png)
How do I eliminate watchman???

**Comment by wez** [comment]
Firstly, please be try to be constructive; it's clear that you are frustrated but it doesn't help us to help you when you make a post with the tone and content above.

Secondly: watchman doesn't modify your filesystem so it seems extremely unlikely that watchman has proactively done anything to your system.

We in the watchman project don't really know much at all about developing with React or even what Expo is, so your question about "eliminating" watchman is not something we can help you with here.

Watchman can be used in conjunction with source control systems, although that is rare outside of FB.  You haven't shared information about how you might have configured things  in relation to your statement about commits.

The error message in your screenshot appears similar to the one in this question that someone previously asked on stackoverflow; there's an answer there that explains in more detail what the error message means and what might cause it, and how you might be able to resolve it:

https://stackoverflow.com/q/59346532/149111
