### ISSUE TITLE
[python] Building as wheel broken on master

### ISSUE THREAD

**Issue by samschlegel** [facebook/watchman#829]
In https://github.com/facebook/watchman/commit/2865ab1bed38393167fc956ec3213a0eb3577a41 setuptools was reverted back to distutils, but this means that you can no longer `python setup.py bdist_wheel`. We do this as part of our build process, but this means that `publish-pypi.sh` won't work anymore.

It should be safe to try to import setuptools, and on an ImportError import distutils instead. PR is easy so I can throw that up if needed, but figured I'd file this first.

**Comment by genevievehelsel** [comment]
@samschlegel sorry for the delay - we've reverted that change and it will be updated soon (today/tomorrow).

**Comment by fanzeyi** [comment]
Closed in fdf5fa70ac76b7cbc698fe0eb9ef8983877c3386.
