### ISSUE TITLE
[readme]: adding usage and installation info

### ISSUE THREAD

**Issue by subedigaurav** [facebook/watchman#836]
Hello there!

I appreciate the project. It is well documented. However, the readme could be made better by adding some basic installation and usage info. What do you think?

Looking forward to a positive response and (hopefully) a PR!

Thanks.

**Comment by wez** [comment]
We have a lot of information on the website; I'd rather push people there than replicate it in the readme, as duplicated information is guaranteed to become stale!

**Comment by subedigaurav** [comment]
alright. sounds good.
