### ISSUE TITLE
macOS build is broken

### ISSUE THREAD

**Issue by develar** [facebook/watchman#838]
No latest release for macOS because last successful build was [3 months ago](https://github.com/facebook/watchman/actions?query=workflow%3Amac+is%3Asuccess).

Is it possible to fix build and provide releases not only for Linux and Windows, but also for macOS?

**Comment by fanzeyi** [comment]
Sorry I have a fix for it pending. Gonna push it later today.

**Comment by fanzeyi** [comment]
4969d39 fixes this. Tomorrow's release should contain a release for macOS.

**Comment by develar** [comment]
Thanks for a quick fix. It works.
