### ISSUE TITLE
inotify on SmartOS (Illumos) issue

### ISSUE THREAD

**Issue by alcir** [facebook/watchman#84]
Newer platforms of SmartOS (that is based on Illumos) are built with inotify.
Btw it seems that something goes wrong.

```
1425998445: tid=3 notify_thread[/opt/repos] assessing triggers
1425998445: tid=3 inotify read: returned 48.
1425998445: tid=3 notify: wd=1 mask=100 prova
1425998445: tid=3 add_pending for inotify mask=100 /opt/repos/prova
1425998445: tid=3 add_pending: /opt/repos/prova
1425998445: tid=3 notify: wd=0 mask=8 prova
1425998445: tid=3 wanted dir 0 for mask 8 but not found prova
1425998445: tid=3 /opt/repos: dir missing from internal state: scheduling a tree recrawl
1425998445: tid=3 inotify read: returned 48.
1425998445: tid=3 notify: wd=0 mask=4 prova
1425998445: tid=3 wanted dir 0 for mask 4 but not found prova
1425998445: tid=3 notify: wd=0 mask=8 prova
1425998445: tid=3 wanted dir 0 for mask 8 but not found prova
1425998445: tid=3 add_pending: /opt/repos
1425998445: tid=3 processing 1 events in /opt/repos
1425998445: tid=3 opendir(/opt/repos) recursive=false
1425998445: tid=3 watch_dir(/opt/repos)
```

Even if a single file is modified, watchman is performing a full recrawl of the directory. So the argv array is filled by all the files existing in the directory and not by only the one added or changed.

Sorry, I'm not a developer.
But if I try to edit the `configure.ac` file
```
182 AC_CHECK_HEADERS(sys/types.h inttypes.h locale.h port.h sys/inotify.h sys/event.h)
183 AC_CHECK_FUNCS(mkostemp kqueue port_create inotify_init strtoll localeconv statfs)
```
removing `sys/inotify.h` and `inotify_init`, then compiling Watchman, it performs well.

**Comment by wez** [comment]
Is `inotify` now in the base system or do you have some kind of emulated inotify package installed?
Could you put the `config.log` file (without your configure.ac changes!) in a gist or email it to me?

I think I might go with a fix along these lines:

```
$ git diff
diff --git a/root.c b/root.c
index da6511c..55fa2ea 100644
--- a/root.c
+++ b/root.c
@@ -1720,10 +1720,10 @@ void watchman_watcher_init(void) {

 #if HAVE_FSEVENTS
   watcher_ops = &fsevents_watcher;
-#elif defined(HAVE_INOTIFY_INIT)
-  watcher_ops = &inotify_watcher;
 #elif defined(HAVE_PORT_CREATE)
   watcher_ops = &portfs_watcher;
+#elif defined(HAVE_INOTIFY_INIT)
+  watcher_ops = &inotify_watcher;
 #elif defined(HAVE_KQUEUE)
   watcher_ops = &kqueue_watcher;
 #else
```

which will prefer the portfs watcher over inotify.  It seems unlikely that linux will add a portfs emulation, so we can dodge the opposite problem on linux :-)

Could you try my suggested code change and let me know if it operates correctly for you?

**Comment by alcir** [comment]
As far as I know, `inotify` is now in the SmartOS base system. But I don't know much more.

With your fix it works (in that way it doesn't use inotify, right?).

Here you can find the `config.log` file: https://gist.github.com/alcir/3bb015e9c24c82937c6d

**Comment by alcir** [comment]
Someone on the SmartOS IRC channel says:

*https://github.com/joyent/illumos-joyent/blob/master/usr/src/uts/common/io/inotify.c
inotify has been added to illumos-joyent.
on platforms from after it went in, software will now find the headers and build against it.
I don't know how well it performs against the native illumos way to do the same thing.*

**Comment by wez** [comment]
Great; thanks for the report and the feedback + talking to the illumos folks; very helpful!
I've just pushed the fix + some comments.
