### ISSUE TITLE
License clarification for bser package

### ISSUE THREAD

**Issue by jfoz** [facebook/watchman#844]
Could you please confirm the license of the bser package? There is no LICENSE file in the node directory (unlike python), and npm says Apache 2.0, which seems it would make it a different license than the one in the watchman/python directory.

Relevant links:
https://github.com/facebook/watchman/tree/master/node
https://github.com/facebook/watchman/blob/master/python/LICENSE
https://www.npmjs.com/package/bser

**Comment by wez** [comment]
Everything in the repo is covered by the top level license file:
https://github.com/facebook/watchman/blob/master/LICENSE (Apache 2.0)
except for the python directory which has a more BSDish license:
https://github.com/facebook/watchman/blob/master/python/LICENSE

**Comment by fanzeyi** [comment]
I think @wez 's comment should answer the question. Closing this issue. If you have any follow up questions, feel free to re-open.
