### ISSUE TITLE
do not trigger on file deletion

### ISSUE THREAD

**Issue by alcir** [facebook/watchman#85]
There is a way to do not trigger an action when a file is deleted?
If I'm not wrong, I see that I can manually add ["exists"] to expression in the root.state, like
```
...
                    "expression": [
                        "allof",
                        [
                            "match",
                            "*",
                            "wholename"
                        ],
                        ["exists"]
                    ]
...
```
Is it OK? And if it is OK, how to achieve this using the command line, using the watchman command (like `watchman -- trigger /opt/repos 'repos-sync' -X '*.css' -I '*' -- /usr/local/sbin/scanner.sh`)

**Comment by wez** [comment]
Sounds like you want the extended trigger syntax:
https://facebook.github.io/watchman/docs/cmd/trigger.html#extended-syntax

something like this will register a trigger to run your scanner.sh on all files that are changed if they don't match the pattern `*.css` and currently exist on the filesystem:

(you may want to double check the expression syntax, as I'm typing this directly into this comment window)

```
$ watchman -j <<-EOT
["trigger", "/opt/repos", {
  "name": "repos-sync",
  "expression": ["allof", ["not", ["match", "*.css"]], ["exists"]],
  "command": ["/usr/local/sbin/scanner.sh"]
}]
EOT
```

**Comment by alcir** [comment]
This is what I was looking for. Thank you
