### ISSUE TITLE
How to invoke script once , despite multiple file changes 

### ISSUE THREAD

**Issue by p4yl0ad** [facebook/watchman#855]
I have a watch setup to monitor file changes within a directory "input/" which calls a script which performs formatting on said files and moves them to an "output/" directory. 

When the watchman triggers and multiple files have changed, the script gets called x times where x is the number of files moved to the /input directory.

Is there a way to configure watchman to only trigger once despite multiple changes being detected within a time period. 
I have had a play with configuring a .watchman config file within the target watch directory input/ however this just halts my processing and breaks my logging function.

I.E.
files list1.csv list2.csv list3.csv get moved into the 'input/' directory 
Watchman will get triggered 3 times and as a result my script gets called 3 times, thus damaging the logging functions i have written in my script.

```
def logger(timestamp_start,list_of_moved, list_of_stamps):
    logfile = directory_root + logs + 'VFT_log_' + timestamp_start + ".json"
    log_data = {}
    log_data['Move History'] = []

    for idx,val in enumerate(list_of_moved):
        print(idx)
        print(val)
        log_data['Move History'].append({
            'filename':val,
            'isotime':list_of_stamps[idx]
            })

    with open(logfile, 'w') as outfile:
        json.dump(log_data, outfile)
```

due to the script getting called three times, three iterations of the same .json logfile are generated overwriting the successor logfile. Is this an logic error and there is a better way of handling this ?

I can supply source if needed :) 
Thanks 

EDIT
there is an obvious fix which is to generate one json log per call to the script however this will bloat the log/ directory with hundreds of files daily , i would like it to be processed in a batch nature.

**Comment by fanzeyi** [comment]
I don't have good suggestions, but here is a way to make it work. What about instead of having Watchman telling you about these events but your script actively queries it. To put it in a simply bash code (I didn't run):

```bash
dir=/path/to/watched-dir/
clock=$(watchman clock "$dir")
while true; do
  changes=$(watchman since "$dir" # add some filter here)
  python script.py <<< "$changes"
  sleep 5
done
```

**Comment by p4yl0ad** [comment]
Ive actually managed to get it to work, my mistake was thinking i could invoke a batch job upon a first file changing and a wait period in order to let the files 'settle' and ensure no changes during processing.

Watchman will trigger a job for EACH file that changes (given in the trigger spec), its good to know :)

**Comment by rimzici** [comment]
@p4yl0ad  Could you please shed some light on how you managed to solve it?
Facing similar issue, where typescript compiled output results in JS to reload infinitely and eventually crash metro.

Thanks!
