### ISSUE TITLE
Error on build watchman: fatal: reference is not a tree

### ISSUE THREAD

**Issue by Daemon-Macklin** [facebook/watchman#859]
Hi There,

I am currently trying to build Watchman from source on Ubuntu 20.04 using WSL. I am using the latest [source code zip](https://github.com/facebook/watchman/releases/tag/v2020.09.21.00).  

To build I run the command 
```bash
python3 build/fbcode_builder/getdeps.py build watchman
```
Then after 20/30 minutes of it installing and building stuff it clones the https://github.com/facebook/fbthrift repo then tries to check out a branch. and that is where it throws the error.

```
Using pinned rev 53216cb40521530217db158af6c068c635af61e8 for https://github.com/facebook/fbthrift.git
Assessing fbthrift...
Using pinned rev 53216cb40521530217db158af6c068c635af61e8 for https://github.com/facebook/fbthrift.git
Cloning https://github.com/facebook/fbthrift.git...
---
+ cd /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/repos && \
+ git \
+      clone \
+      --depth=100 \
+      -- \
+      https://github.com/facebook/fbthrift.git \
+      github.com-facebook-fbthrift.git
Cloning into 'github.com-facebook-fbthrift.git'...
remote: Enumerating objects: 6977, done.
remote: Counting objects: 100% (6977/6977), done.
remote: Compressing objects: 100% (4317/4317), done.
remote: Total 6977 (delta 3634), reused 3524 (delta 2139), pack-reused 0
Receiving objects: 100% (6977/6977), 5.81 MiB | 1.37 MiB/s, done.
Resolving deltas: 100% (3634/3634), done.
Updating files: 100% (4724/4724), done.
Updating /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git -> 53216cb40521530217db158af6c068c635af61e8
---
+ cd /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git && \
+ git \
+      fetch \
+      origin
---
+ cd /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git && \
+ git \
+      checkout \
+      53216cb40521530217db158af6c068c635af61e8
fatal: reference is not a tree: 53216cb40521530217db158af6c068c635af61e8
Command '['git', 'checkout', '53216cb40521530217db158af6c068c635af61e8']' returned non-zero exit status 128.
!! Failed
```
Not entirely sure what I would be doing wrong here since it seems like an issue with the repo it's trying to clone, but if someone could point out where I am going wrong it would be much appreciated.

**Comment by Daemon-Macklin** [comment]
Okay so I tried two things.
1. Was to just pull down from Master and run the build there.
2. Updating the build/deps/github_hashes/facebook/fbthrift-rev.txt to have the most recent commit in the latest release source, which was the exact same as what was on the Master branch.

Both of those resulted in it being able to pull down the repo and checkout the branch but now I'm getting a different error later down the line.

```bash
[95/205] Building CXX object thrift/lib/cpp/CMakeFiles/protocol.dir/protocol/TJSONProtocol.cpp.o
ninja: build stopped: subcommand failed.
Command '['/tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/installed/cmake-uGvgBiBuh-u79QywFBcdwO7jbJf3n0x6THCKGu3tRUM/bin/cmake', '--build', '/tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchman-2020.09.21.00ZbuildZfbcode_builder/build/fbthrift', '--target', 'install', '--config', 'Release', '-j', '8']' returned non-zero exit status 1.
!! Failed
```
It looks like it's still and issue with the [fbthrift](https://github.com/facebook/fbthrift) branch. Any idea on what's going wrong?

**Comment by fanzeyi** [comment]
I don't think the error message is complete. Can you maybe make the entire CMake output into a gist? Look for lines contain `error:`. Also, I wouldn't recommend manually change `fbthrift-rev.txt`. Internally everything is in a giant monorepo and we can only guarantee everything works together if they are on the same version as internal is. That's why these revision files exist. 

Also, our GitHub Actions might be helpful: [`getdeps_linux.yml`](https://github.com/facebook/watchman/blob/master/.github/workflows/getdeps_linux.yml)

**Comment by Daemon-Macklin** [comment]
I'm not sure if this is what you're looking for. But it's the output I get when running the getdeps script.

[gist](https://gist.github.com/Daemon-Macklin/159a663a01681e7edf2cf5be747bd779) - Apologies it's so long.

But I think I see the error that's causing it to fail, it's at the very end of the gist file. 

```bash
In file included from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/transport/THeader.h:30,
                 from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/server/TConnectionContext.h:25,
                 from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/TProcessorEventHandler.h:22,
                 from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/ContextStack.h:21,
                 from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/EventHandlerBase.h:26,
                 from /tmp/fbcode_builder_getdeps-ZhomeZdmacklinZwatchmanZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-fbthrift.git/thrift/lib/cpp/EventHandlerBase.cpp:17:
./thrift/lib/thrift/gen-cpp2/RpcMetadata_types.h:7:3: error: expected unqualified-id before ‘<%’ token
    7 |   <%!
      |   ^~
```

**Comment by fanzeyi** [comment]
The error seems to be related to new line characters. My guess what happened here is that getdeps doesn't know how to build in WSL, and as a result it tries to use MSVC compilers in WSL, which won't work.

Do you have any particular reason to build Watchman in WSL? If not, I would recommend building it with the same procedure but with PowerShell / cmd.exe.

**Comment by Daemon-Macklin** [comment]
Yeah I'm not too sure what the issue was. Entirely possible it's an issue with WSL. I took another look and tried installing it through [brew](https://facebook.github.io/watchman/docs/install.html#buildinstall) and that seems to have installed it okay on WSL. 

Thanks for the help, I'll close the issue.
