### ISSUE TITLE
Watchman triggers on *reads* of files shared over AFP, netatalk

### ISSUE THREAD

**Issue by jamesarosen** [facebook/watchman#86]
I'm sharing a directory from an Ubuntu VM via netatalk 3. On the OSX host machine, I mount that directory using AFP (Finder's *Connect to Server*).

Whenever I *read* files in the mounted directory (or even get stats on them via `ls`), Watchman triggers.

Is there any way to ignore these events?

(I would totally believe that this is a bug in netatalk or Apple's AFP implementation. This just seems like the easiest place to get a fix in if it's possible to filter out these kinds of file-system events.)

**Comment by jamesarosen** [comment]
One hypothesis is that one of the file systems is writing `atime` flags on the files. I will investigate setting `noatime`.

**Comment by jamesarosen** [comment]
I've tried remounting the Ubuntu VM's filesystem with `noatime`. That did not fix the problem. I wouldn't write off a `noatime`-based solution, though.

The next thing I wanted to find out was *what properties* were changing on the file.
```bash
# on Ubuntu VM:
ubuntu$ stat /opt/my-app/templates/index.hbs
  File: `/opt/my-app/templates/index.hbs'
  Size: 75        	Blocks: 16         IO Block: 4096   regular file
Device: fc00h/64512d	Inode: 2531250     Links: 1
Access: (0664/-rw-rw-r--)  Uid: ( 1001/me)   Gid: ( 1001/me)
Access: 2015-03-22 03:35:05.783692046 +0000
Modify: 2015-03-22 03:35:05.683695248 +0000
Change: 2015-03-22 03:35:05.691694991 +0000

# on OSX host:
osx$ cat ~/code/my-app/templates/index.hbs
```
That triggered Watchman. Yet when I checked the stats from Ubuntu again, they were the same!

**Comment by jamesarosen** [comment]
Turning `--log-level` up to `2` yields the following just after I `cat` a file:
```
2015-03-22_22:44:36.82622 1427064276: tid=2724595456 inotify read: returned 48.
2015-03-22_22:44:36.82624 1427064276: tid=2724595456 notify: wd=36 mask=8 index.hbs
2015-03-22_22:44:36.82624 1427064276: tid=2724595456 add_pending for inotify mask=8 /opt/my-app/templates/index.hbs
2015-03-22_22:44:36.82625 1427064276: tid=2724595456 add_pending: /opt/my-app/templates/index.hbs
2015-03-22_22:44:36.82625 1427064276: tid=2724595456 processing 1 events in /home/vagrant/fastly/Sierra
2015-03-22_22:44:36.82625 1427064276: tid=2724595456 lstat(/opt/my-app/templates/index.hbs) file=0x1a01bb0 dir=(nil)
2015-03-22_22:44:36.82626 1427064276: tid=2724595456 file changed exists=1 via_notify=1 stat-changed=0 isdir=0 /home/vagrant/fastly/Sierra/app/lib/sierra.history.coffee
2015-03-22_22:44:36.82626 1427064276: tid=2724595456 lstat(/opt/my-app/templates) file=0x19e8400 dir=0x19e8530
2015-03-22_22:44:36.82626 1427064276: tid=2724595456 file changed exists=1 via_notify=1 stat-changed=0 isdir=1 /opt/my-app/templates
```

**Comment by sid0** [comment]
I'm afraid network filesystems aren't really supported. As you've discovered they can have really funky semantics.

**Comment by wez** [comment]
Not sure about how best to deal with this, if at all.

This line of code is probably the one to look at:
https://github.com/facebook/watchman/blob/master/root.c#L932
You'll see that we trust the `via_inotify` flag more than we trust comparing the stat structs.
You might be able to eliminate what you consider to be a false trigger in this instance if you take out the `via_inotify` part of that expression.  I'd strongly recommend that you run the regression tests if you do that (see https://facebook.github.io/watchman/contributing.html) to ensure that the service continues to operate correctly.

**Comment by jamesarosen** [comment]
That's *exactly* what I had in mind. I really appreciate your suggestion because it makes me feel like I'm on the right track 😀

I should note that the files primarily live on the FS where `watcher` is running. I'm sharing them from there to OSX where I'm doing reads (and writes, which seem to work fine).

**Comment by wez** [comment]
I took a quick peek at disabling the `via_inotify` thing today and it broke our trigger and subscription integration tests.  I'm leaning towards resolving this as won't-fix.

Can you share more about your use case?  We may be able to come up with an alternative solution if we understand the problem better.  How are you using watchman and how does this issue manifest as problematic for you?

**Comment by jamesarosen** [comment]
> I took a quick peek at disabling the via_inotify thing today
Thanks for trying that :)

> Can you share more about your use case?
Our engineering team has a large number of projects split across a number of technologies. In order to (a) make development look more like production and (b) ease the pain of setup for all devs, we run each project in an LXC that are mounted within an Ubuntu VM. In this case, we're using `watchman` inside one of those LXCs to trigger builds to a static app.

So far in what I've described `watchman` works fine.

The problem is that not every developer wants to use `vi` or Ubuntu tools to do their editing. To support people working from their host OS, we share the files *from* Ubuntu via AFP *to* OSX. It's when I read files on OSX that I trigger rebuilds.

That's no *so* bad for reading an individual file. We use `make` or [broccoli](https://github.com/broccolijs/broccoli) to avoid doing too much re-work. It's a real problem when the editor scans all the files or when you do a project-wide search, though.

**Comment by wez** [comment]
How do you trigger the build?  Are you using triggers or subscriptions?

**Comment by wez** [comment]
And worth asking also, have you tried using CIFS or SSHFS or some other sharing protocol?

**Comment by jamesarosen** [comment]
> How do you trigger the build?

In one project, we use
```bash
/opt/fst-watchman/watchman \
    --foreground \
    --logfile=/dev/stdout \
    --statefile=/etc/watchman/sierra.state
```
where `sierra.state` looks like
```json
{
    "version": "3.0.0",
    "watched": [
        {
            "path": "/home/vagrant/fastly/Sierra",
            "triggers": [
                {
                    "name": "make-dev",
                    "command": [
                        "/home/vagrant/fastly/Sierra/bin/make_dev_no_args",
                        "/home/vagrant/fastly/Sierra"
                    ],
                    "append_files": true,
                    "stdin": [
                        "name",
                        "exists",
                        "new",
                        "size",
                        "mode"
                    ],
                    "expression": [
                        "anyof",
                        [
                            "match",
                            "*.coffee",
                            "wholename"
                        ],
                        [
                            "match",
                            "*.js",
                            "wholename"
                        ],
                        [
                            "match",
                            "*.scss",
                            "wholename"
                        ],
                        [
                            "match",
                            "*.html",
                            "wholename"
                        ]
                    ]
                }
            ]
        }
    ]
}
```
In another project, we use [ember-cli](http://www.ember-cli.com/). As far as I can tell, that uses the [sane](https://www.npmjs.com/package/sane) NPM package, which in turn uses [fb-watchman](https://www.npmjs.com/package/fb-watchman).

> And worth asking also, have you tried using CIFS or SSHFS or some other sharing protocol?

I know we've tried a few protocols, but I don't know which. The engineer that did the evaluation of options didn't know about this problems at the time. He selected AFP because all of the others he looked at had other problems. I can try to get him to chime in on this thread.

**Comment by wez** [comment]
How would you characterize the main problem?  Is the main issue that `make_dev_no_args` is taking a long time and delaying a legitimate build?

**Comment by jamesarosen** [comment]
Really the problem is just that the constant reads cause the CPU to be at 100% all the time.

**Comment by wez** [comment]
I dug in a bit deeper; I can get our tests to pass in this diff:
https://reviews.facebook.net/D36531
I have mixed feelings about it; I think it will solve this case and reduce CPU utilization, but relying on the stat struct to detect changes can increase latency and cause us to miss some classes of change.
I'm wondering if it is worth adding a `.watchmanconfig` option to enable this behavior

**Comment by jamesarosen** [comment]
@wez is that the right URL?

**Comment by wez** [comment]
Yep, you might need to auth with your github account to see it

**Comment by jamesarosen** [comment]
Here are some notes from the engineer who did the networked FS evaluation:

 * SSHFS: consistency and performance problems.
 * Samba: permissions problems. It's designed for Windows. You end up with every file being marked executable or other similar problems.
 * NFS with OSX as client: UID problems. OSX uses NFS v3, which doesn't have UID rewriting. The files end up uneditable or unreadable.
 * NFS with OSX as server: security problems. NFS on OSX requires poking holes through the firewall, but doesn't have its own rich security model. This makes it non-PCI-compliant.

I'm going to ask some of our C folks to help me try your patch.

**Comment by jamesarosen** [comment]
Your patch indeed fixes the problem :)

Triggers on writes don't seem to take noticeably longer. (It may be a few ms or even a few hundred ms, but I can't tell.)

**Comment by jamesarosen** [comment]
@wez is there anything else you need from me? Any chance I'll see this -- possibly with a config flag -- in a released version?

**Comment by wez** [comment]
@jamesarosen nope, @sid0 and myself are going to talk about this in more depth to figure out how/if we want to include this

**Comment by jamesarosen** [comment]
It looks like there are some (probably legitimate) concerns with simply applying this patch wholesale. Could we wrap it in a configuration variable like `trust_inotify` that defaults to `true`?

Thus
```c
via_notify = via_notify && trust_inotify; // looked up from JSON, cached, default to true
if (!file->exists || via_notify || did_file_change(&file->st, &st)) {
```

**Comment by jamesarosen** [comment]
I think I was wrong about the fix. Even with that patch applied against v3.1, when I touch `file/a.js`, I see *hundreds* of
```
1432764660: tid=2429073152 processing 1 events in /opt/my-app
1432764660: tid=2429073152 lstat(/opt/my-app/x/y/z.png) file=0x7f3e8c1520e0 dir=(nil)
1432764660: tid=2429073152 lstat(/opt/my-app/x/y) file=0x7f3e8c14d380 dir=0x7f3e8c14d480
1432764660: tid=2429073152 inotify read: returned 32.
1432764660: tid=2429073152 notify: wd=635 mask=8 z.png
1432764660: tid=2429073152 add_pending for inotify mask=8 /opt/my-app/x/y/z.png
1432764660: tid=2429073152 add_pending: /opt/my-app/x/y/z.png
```
for various `x/y/z` files. It's as if `cat`ing one file causes all the files that match the `.state` file to trigger.

I think we'll have to fall back to polling. Thanks for your help.
