### ISSUE TITLE
Modify depth parameter to allow checkout of the correct folly revision

### ISSUE THREAD

**Issue by leonardehrenfried** [facebook/watchman#866]
I'm trying to build an RPM package (Fedora/Red Hat) but the checkout of the folly revision `c37507e46522a57409ea4519a76dfa5e1c3013e6` fails. This seems to be due to the `git clone` command being limited to a clone depth of 100.

The folly revision exists but is older than 100 commits so therefore it cannot be found during the build.

The log of the build process is here: https://download.copr.fedorainfracloud.org/results/lehrenfried/watchman/fedora-33-x86_64/01727754-watchman/builder-live.log.gz (Scroll down to the very bottom to see the relevant commits).

How can I increase the clone depth to make the build succeed?

**Comment by genevievehelsel** [comment]
@leonardehrenfried how are you trying to build the package? What commit are you on? The file that does the clone with --depth=100 was removed on Oct 2 w/ https://github.com/facebook/watchman/commit/79e6327a30a156bb71bdd8f9200a5565ae89305b

**Comment by genevievehelsel** [comment]
Actually, the 100 depth is now located here : https://github.com/facebook/watchman/blob/2e72ec4a3fe73ebd71a9e94a24aabf755d09708c/build/fbcode_builder/getdeps/fetcher.py#L206 my bad :) 

This can be changed in this file (for folly as an example) https://github.com/facebook/watchman/blob/8c6c3b6460411b31629e4497df0c81a4405de982/build/fbcode_builder/manifests/folly#L8 by adding

`depth = 500` or whichever number you need. 

(this is parsed and used here: https://github.com/facebook/watchman/blob/8c6c3b6460411b31629e4497df0c81a4405de982/build/fbcode_builder/getdeps/manifest.py#L58 )

**Comment by wez** [comment]
FWIW, newer versions of git (2.5.0) now support `git fetch origin HASH`, so we can make this "just work" regardless of the fetch depth.  I have an internal diff in review for that.

**Comment by wez** [comment]
```diff
diff --git a/build/fbcode_builder/getdeps/fetcher.py b/build/fbcode_builder/getdeps/fetcher.py
index f6e0f7c..c1e6efd 100644
--- a/build/fbcode_builder/getdeps/fetcher.py
+++ b/build/fbcode_builder/getdeps/fetcher.py
@@ -203,7 +203,7 @@ class PreinstalledNopFetcher(SystemPackageFetcher):


 class GitFetcher(Fetcher):
-    DEFAULT_DEPTH = 100
+    DEFAULT_DEPTH = 1

     def __init__(self, build_options, manifest, repo_url, rev, depth):
         # Extract the host/path portions of the URL and generate a flattened
@@ -262,7 +262,7 @@ class GitFetcher(Fetcher):
             return ChangeStatus()

         print("Updating %s -> %s" % (self.repo_dir, self.rev))
-        run_cmd(["git", "fetch", "origin"], cwd=self.repo_dir)
+        run_cmd(["git", "fetch", "origin", self.rev], cwd=self.repo_dir)
         run_cmd(["git", "checkout", self.rev], cwd=self.repo_dir)
         run_cmd(["git", "submodule", "update", "--init"], cwd=self.repo_dir)
```

**Comment by leonardehrenfried** [comment]
> @leonardehrenfried how are you trying to build the package? What commit are you on? The file that does the clone with --depth=100 was removed on Oct 2 w/ [79e6327](https://github.com/facebook/watchman/commit/79e6327a30a156bb71bdd8f9200a5565ae89305b)

I think @wez' commit addresses the issue but for completeness sake: this happened when I built version `v2020.09.21.00`.

I'm just going to wait for the next release where presumably the change is already included. Am I correct?

**Comment by leonardehrenfried** [comment]
> FWIW, newer versions of git (2.5.0) now support `git fetch origin HASH`, so we can make this "just work" regardless of the fetch depth. I have an internal diff in review for that.

Relying on git 2.5.0 is reasonable. After all, it was released in 2015.

**Comment by wez** [comment]
> I'm just going to wait for the next release where presumably the change is already included. Am I correct?

That'll work, but you can also use one of the automated "updating submodules" commits that happens after my commit lands; internally we don't have releases from the monorepo that is the source of truth for all the git projects mentioned above by my commit; we do continuous delivery.

The submodule update commits are one of the ways that repos are synced, and the weekly release tags are another.  Honestly, I'm not sure that the weekly tags are as strong as the submodule commits at syncing things together.  Also worth keeping in mind that there's no guarantee that a particular sync point isn't broken; we try to keep it all working but there are a lot of ways that breaks can make their way out here!
