### ISSUE TITLE
Working with Encrypted Hard Drives

### ISSUE THREAD

**Issue by jimbeaudoin** [facebook/watchman#87]
Hi,

I'm trying to work with Ember-CLI & Watchman. I'm under Ubuntu 14.04 & I use an Encrypted Hard Drive. Watchman do not work in this situation. I received weird errros like "No Space Left" when I have ~140GB space left. Sometimes I receive nothing and nothing happens. Workman just do not work. If I use the NodeWatcher software, everything is working good. A Owner from the Ember-CLI Repos told me the problem was probably on your side. I don't know. I do not really have the time right now to repoduce the error and give you the errors message. I'm sorry but if you ask nicely maybe I will take the time tomorrow. For me, I can work without watchman. It's up to you.

Have a Nice Day!

https://github.com/ember-cli/ember-cli/issues/3638

**Comment by wez** [comment]
Can you include the actual error message you see rather than paraphrasing?  This is important because the kernel can report ENOSPC to indicate a system limit issue, and this gets rendered as "no space left on device".  Without the context and the full output, it makes it difficult to advise you, with confidence, on the next steps.

You most likely need to bump up the inotify limits on your system to make this work; this link tells you a little more about this:
https://facebook.github.io/watchman/docs/install.html#linux-inotify-limits

**Comment by stefanpenner** [comment]
I believe the error is no change events, but the built in nodewatcher seems to still work.

**Comment by jimbeaudoin** [comment]
Hi, I'm sorry. I should have done it right the first time. My apologies. I'm working right now to reproduce the error and give you the messages.

**Comment by jimbeaudoin** [comment]
Now I received no error & nothing happen. Watchman do not seem to do is job right on my computer. I stopped the server remove, reinstall retry, nothing. I'm not a tool builder & I never got any problems like this before with a files watcher. Why do I have to tweak my system with weird settings for looking into a simple app folder? I just want to recompile my assets when something change inside that folder. Anyway like I said before, I'm not a tool builder & I will use another tool who worked for me before to do this job.

Thank You.

**Comment by wez** [comment]
I'm sorry that you're having trouble.  I can't do much to help without some more information from you.  Let's close this issue for now.  If you decide that you want to try watchman again, and experience problems, please re-open it and we can work through the problem with you.

**Comment by jimbeaudoin** [comment]
@wez  I bumped up the inotify limits on my system to 16384 and now I can work with watchman. The default Ubuntu limit is 8192 and this is not enough for a dev-box in my opinion. Thanks for your time because this is explained in the docs. :+1:

**Comment by wez** [comment]
Glad you got it working!
