### ISSUE TITLE
macOS 11.0 big Sur can't use watchman

### ISSUE THREAD

**Issue by conkyliu** [facebook/watchman#870]
Command failed: brew install watchman
   Warning: You are using macOS 11.0.
   We do not provide support for this pre-release version.
   You will encounter build failures with some formulae.
   Please create pull requests instead of asking for help on Homebrew's GitHub,
   Discourse, Twitter or IRC. You are responsible for resolving any issues you
   experience while you are running this pre-release version.

**Comment by fanzeyi** [comment]
This looks like a Homebrew issue. As the error message said, they don't seem to provide support for Big Sur yet since it is not released. You can either download directly from our [release page](https://github.com/facebook/watchman/releases) or wait until Big Sur is officially release.
