### ISSUE TITLE
Publish the website's updates please

### ISSUE THREAD

**Issue by orta** [facebook/watchman#874]
👋🏻 - I'd like to see https://github.com/facebook/watchman/commit/573b18b86b88759f31e83fa2e1837539d138de22 get shipped to the website, so I ran the publish script myself against my repo, which you can trigger as a PR from here: https://github.com/facebook/watchman/compare/gh-pages...orta:gh-pages?expand=1

It does seem to have updated a Jekyll SEO script and have some minor changes to the HTML markup though. Likely just a transitive dep updating.

2 alternatives to that PR:

- Go the settings on this repo and set the website folder as the default Jekyll (and remove the publishing script) and close this PR because it should be done automatically for you:

![Screen Shot 2020-12-03 at 3 47 03 PM](https://user-images.githubusercontent.com/49038/101052687-d889e800-357e-11eb-8743-12155f8116b6.png)

-  or you could close this issue and run the script yourself 👍🏻

**Comment by chadaustin** [comment]
Done.
