### ISSUE TITLE
curl: (6) Could not resolve host: gnumirror.nkn.in

### ISSUE THREAD

**Issue by Daemon-Devarshi** [facebook/watchman#88]
I am trying to install watchman using below command:

`brew install --HEAD watchman`

but it is failing after displaying below messages in terminal:

==> Installing dependencies for watchman: autoconf, automake, pkg-config,
==> Installing watchman dependency: autoconf
==> Downloading http://ftpmirror.gnu.org/autoconf/autoconf-2.69.tar.gz
######################################################################## 100.0%
curl: (6) Could not resolve host: gnumirror.nkn.in
Trying a mirror...
==> Downloading http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz

curl: (7) Couldn't connect to server
Error: Failed to download resource "autoconf"
Download failed: http://ftp.gnu.org/gnu/autoconf/autoconf-2.69.tar.gz

*Note: I am trying it on Mac OS Yosemite*

**Comment by Daemon-Devarshi** [comment]
I also tried below commands:

$ git clone https://github.com/facebook/watchman.git
$ cd watchman
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install

but I got these errors:

./autogen.sh: line 9: aclocal: command not found
./autogen.sh: line 10: autoheader: command not found
./autogen.sh: line 11: automake: command not found
./autogen.sh: line 12: autoconf: command not found

**Comment by wez** [comment]
I'm sorry that you're having problems getting the dependencies installed.  I'd strongly recommend that you focus on getting `brew` working for you as it will make it easier for you in the long run.

The error messages indicate that the GNU software mirror in your location is broken.  This is not something that contributors to the watchman project can resolve.  I'd recommend filing an issue with the `brew` project.  You may be able to edit the brew recipe to use a specific download host instead, but the details of that are outside the scope of what I can help you with here.

Good luck!

**Comment by ozanmuyes** [comment]
Hi @Daemon-Devarshi 

Please check this answer http://askubuntu.com/a/107115/329206

Regards,
Ozan MÜYESSEROĞLU
