### ISSUE TITLE
sysctl.conf ignored on M1, Big Sur, Mac Mini

### ISSUE THREAD

**Issue by tgroshon** [facebook/watchman#880]
I put the following values into an `/etc/sysctl.conf` as per the documentation:

```
$ sudo cat /etc/sysctl.conf
kern.maxfiles=10485760
kern.maxfilesperproc=1048576
```

> Putting the following into a file named /etc/sysctl.conf on macOS will cause these values to persist across reboots

However after a reboot, the values were reset to normal:

```
$ sudo sysctl kern.maxfiles
kern.maxfiles: 49152
$ sudo sysctl kern.maxfilesperproc
kern.maxfilesperproc: 24576
```

Is there a missing step or perhaps a new configuration method to make these values persist on the latest M1 machines?

System Details:

Mac mini (M1, 2020)
Chip: Apple M1
Memory: 16 GB
OS: macOS Big Sur version 11.0.1

Also, I'm running my terminal session under Rosetta 2.

**Comment by wez** [comment]
You don't need to set anything in sysctl.conf for watchman on Big Sur.  The documentation at https://facebook.github.io/watchman/docs/install.html#mac-os-file-descriptor-limits states that those settings are only applicable on macOS 10.6 and _earlier_.
The sysctl configuration only applies to the `kqueue` based watcher.  On 10.7 and up, watchman uses `fsevents` and doesn't need sysctl adjustments.
