### ISSUE TITLE
macOS 11.1 Big Sur can't use watchman

### ISSUE THREAD

**Issue by tuantvk** [facebook/watchman#884]
I have update macOS to 11.1 and Xcode version 12.3. When i run project react native display error **jest-haste-map: Watchman crawl failed. Retrying once with node crawler**. I have reinstall watchman with brew but it not working.

I follow with comment [https://github.com/facebook/watchman/issues/751#issuecomment-542300670](https://github.com/facebook/watchman/issues/751#issuecomment-542300670) but not found **watchman**

How to fix it ?

**Comment by fanzeyi** [comment]
Do you get anything if you run `watchman` in command line? Can you also post the output from `watchman-diag` in a gist? Thanks.

**Comment by vjpr** [comment]
I'm getting the following whenever I call `query` with the node.js api.

```
Error: Watchman error: The watchman connection was closed. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting
```

**Comment by vjpr** [comment]
@fanzeyi How do I run `watchman-diag`?

**Comment by tuantvk** [comment]
I moved project to **/Users/{myuser}/** and it worked. [https://github.com/facebook/watchman/issues/751#issuecomment-540684524](https://github.com/facebook/watchman/issues/751#issuecomment-540684524)
