### ISSUE TITLE
Microsoft Defender Virus false positive issue

### ISSUE THREAD

**Issue by dfcarpenter** [facebook/watchman#886]
It seems Microsoft Windows Defender is throwing a false positive with the Windows build. This also happens on several co-workers machines as well.
![microsoft_defender_watchman](https://user-images.githubusercontent.com/4450286/105903363-41646e00-5fcc-11eb-9aad-77a09baf65be.png)
I would report this myself if I could upload the file. Below is a link to report for review.
https://www.microsoft.com/en-us/wdsi/filesubmission

**Comment by fanzeyi** [comment]
Thanks for the report! This is very unfortunate. :(  I will try to submit a report to Microsoft.

**Comment by fanzeyi** [comment]
Hi, Microsoft has removed the detection and it suggested the following command to clear cached detection.

>     1. Open command prompt as administrator and change directory to c:\Program Files\Windows Defender 
>     2. Run “MpCmdRun.exe -removedefinitions -dynamicsignatures”
>     3. Run "MpCmdRun.exe -SignatureUpdate"
>
> Alternatively, the latest definition is available for download here: https://www.microsoft.com/en-us/wdsi/definitions/

Please try following these instructions and it should stop flagging Watchman as malware now. Thanks again for reporting.

<img width="1174" alt="image" src="https://user-images.githubusercontent.com/409951/106204288-98577800-6171-11eb-823c-e2830fadfbe9.png">
