### ISSUE TITLE
What is the leading `10` in file mode (when converted to octal) ?

### ISSUE THREAD

**Issue by Atralb** [facebook/watchman#887]
Let's say you have a file with 7000 permissions. `watchman` will report file mode as :

```
"mode": 36532
```
which is 107000 in octal. 

What does this leading 10 represent ? In other words, why is the decimal number reported  as `32948 + to_decimal(octal_mode)` ?

**Comment by wez** [comment]
`mode` is the `struct stat` `st_mode` field, which encodes both the *file type* as well as the access permissions.
The precise meaning is system dependent and interpreted using `S_ISREG` and similar macros (see: https://linux.die.net/man/2/stat).

**Comment by Atralb** [comment]
I understand, thanks for your answer.
