### ISSUE TITLE
No configure file generated after running autogen.sh

### ISSUE THREAD

**Issue by YoghurtSheep** [facebook/watchman#888]
Hi!

I am following your installation steps from source to get watchman built: [Installation steps](https://facebook.github.io/watchman/docs/install.html)
commit id: commit a0cab427d7ab27047ebbabffa913bf86bdfc01a8 (HEAD -> master, origin/master, origin/HEAD)

```
$ # use the latest stable release
$ git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
$ cd watchman 
$ ./autogen.sh
$ ./configure
$ make
$ sudo make install
```
However, when I finished running `./autogen.sh` command, no target configure file generated and I can not continue to follow your step `./configure` to build.

My machine information:  Fedora32

Here is my output after `./autogen.sh` :

```
Building on {distro=fedora, distro_vers=32, fb=off, os=linux, test=on}
Assessing boost...
Assessing ninja...
Assessing cmake...
Assessing cpptoml...
Assessing googletest...
Assessing pcre...
Assessing fmt...
Assessing python-six...
Assessing zstd...
Assessing double-conversion...
Assessing gflags...
Assessing glog...
Assessing libevent...
Assessing lz4...
Assessing snappy...
Using pinned rev 65c55155549d6b1abf1366d67890b673b5842fbe for https://github.com/facebook/folly.git
Assessing folly...
Using pinned rev 65c55155549d6b1abf1366d67890b673b5842fbe for https://github.com/facebook/folly.git
Assessing autoconf...
Assessing automake...
Assessing libtool...
Assessing bison...
Assessing libsodium...
Assessing fizz...
Assessing flex...
Using pinned rev b51baaeaf51950fcd491c987ff993b6a03015b66 for https://github.com/facebook/wangle.git
Assessing wangle...
Using pinned rev b51baaeaf51950fcd491c987ff993b6a03015b66 for https://github.com/facebook/wangle.git
Using pinned rev 4b136c1a708d0af53b1f96e86471d28662956b42 for https://github.com/facebook/fbthrift.git
Assessing fbthrift...
Using pinned rev 4b136c1a708d0af53b1f96e86471d28662956b42 for https://github.com/facebook/fbthrift.git
Assessing fb303...
Assessing watchman...
Building watchman...
Building on {distro=fedora, distro_vers=32, fb=off, os=linux, test=on}
Assessing autoconf...
Assessing automake...
Assessing libtool...
Assessing patchelf...
Consider bin/watchman
Munging built/bin/watchman
dep: libgflags.so.2.2 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/gflags-HuQazByAUsAezmlFbvkeYp43fwnE4XlQsjo28zBKaJs/lib/libgflags.so.2.2
Munging built/lib/libgflags.so.2.2
dep: libpthread.so.0 -> None
dep: libstdc++.so.6 -> None
dep: libm.so.6 -> None
dep: libgcc_s.so.1 -> None
dep: libc.so.6 -> None
dep: libglog.so.0 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/glog-rseVU44AhrWvy38GDo7TVAq1VprQfjf_nZk8zPQp-BA/lib64/libglog.so.0
Munging built/lib/libglog.so.0
dep: libunwind.so.8 -> None
dep: libpthread.so.0 -> None
dep: libgflags.so.2.2 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/gflags-HuQazByAUsAezmlFbvkeYp43fwnE4XlQsjo28zBKaJs/lib/libgflags.so.2.2
dep: libstdc++.so.6 -> None
dep: libm.so.6 -> None
dep: libgcc_s.so.1 -> None
dep: libc.so.6 -> None
dep: ld-linux-x86-64.so.2 -> None
dep: libz.so.1 -> None
dep: libssl.so.1.1 -> None
dep: libcrypto.so.1.1 -> None
dep: libbz2.so.1 -> None
dep: liblzma.so.5 -> None
dep: libzstd.so.1 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/zstd-Hw7XOd8ajUigRGELVa7WcIii9BFjEUqOo6RciUJYzPw/lib64/libzstd.so.1
Munging built/lib/libzstd.so.1
dep: libpthread.so.0 -> None
dep: libc.so.6 -> None
dep: libsnappy.so.1 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/snappy-kRjHjfXZ5iVwTe1PktipBrhP5WDGwB47s8jjWzQJZbc/lib64/libsnappy.so.1
Munging built/lib/libsnappy.so.1
dep: libstdc++.so.6 -> None
dep: libm.so.6 -> None
dep: libgcc_s.so.1 -> None
dep: libc.so.6 -> None
dep: libdwarf.so.1 -> None
dep: libaio.so.1 -> None
dep: libsodium.so.23 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/libsodium-5E-XmQw7Q4TIyAIW7jjEsvyMAb7SaXE3Th1GM72oWIg/lib/libsodium.so.23
Munging built/lib/libsodium.so.23
dep: libpthread.so.0 -> None
dep: libc.so.6 -> None
dep: ld-linux-x86-64.so.2 -> None
dep: libdl.so.2 -> None
dep: libunwind.so.8 -> None
dep: libpthread.so.0 -> None
dep: libstdc++.so.6 -> None
dep: libm.so.6 -> None
dep: libgcc_s.so.1 -> None
dep: libc.so.6 -> None
dep: ld-linux-x86-64.so.2 -> None
 16032445      4 drwxr-s---   4 pengy    icg_src      4096 Jan 28 15:56 built
 16032446      4 drwxr-s---   2 pengy    icg_src      4096 Jan 28 15:57 built/lib
 16031690   3016 -rwxr-xr-x   1 pengy    icg_src   3085920 Jan 28 15:58 built/lib/libgflags.so.2.2
 16031691   1436 -rwxr-xr-x   1 pengy    icg_src   1467256 Jan 28 15:58 built/lib/libglog.so.0
 16031694   3600 -rwxr-xr-x   1 pengy    icg_src   3685368 Jan 28 15:59 built/lib/libsodium.so.23
 16031693    340 -rwxr-xr-x   1 pengy    icg_src    346232 Jan 28 15:58 built/lib/libsnappy.so.1
 16031692   6664 -rwxr-xr-x   1 pengy    icg_src   6819952 Jan 28 15:58 built/lib/libzstd.so.1
 16032447      4 drwxr-s---   2 pengy    icg_src      4096 Jan 28 15:56 built/bin
 16031689 231916 -rwxr-xr-x   1 pengy    icg_src  237475560 Jan 28 15:59 built/bin/watchman


```

Could you please help me?

**Comment by fanzeyi** [comment]
That build instruction is only valid for 4.9.0 and it looks like you are building from the latest master. `./autogen.sh` is sufficient to build Watchman and your log seems to suggest it has been built at `./built/bin` directory.

**Comment by YoghurtSheep** [comment]
> Hi!
> 
> I am following your installation steps from source to get watchman built: [Installation steps](https://facebook.github.io/watchman/docs/install.html)
> commit id: commit [a0cab42](https://github.com/facebook/watchman/commit/a0cab427d7ab27047ebbabffa913bf86bdfc01a8) (HEAD -> master, origin/master, origin/HEAD)
> 
> ```
> $ # use the latest stable release
> $ git clone https://github.com/facebook/watchman.git -b v4.9.0 --depth 1
> $ cd watchman 
> $ ./autogen.sh
> $ ./configure
> $ make
> $ sudo make install
> ```
> 
> However, when I finished running `./autogen.sh` command, no target configure file generated and I can not continue to follow your step `./configure` to build.
> 
> My machine information: Fedora32
> 
> Here is my output after `./autogen.sh` :
> 
> ```
> Building on {distro=fedora, distro_vers=32, fb=off, os=linux, test=on}
> Assessing boost...
> Assessing ninja...
> Assessing cmake...
> Assessing cpptoml...
> Assessing googletest...
> Assessing pcre...
> Assessing fmt...
> Assessing python-six...
> Assessing zstd...
> Assessing double-conversion...
> Assessing gflags...
> Assessing glog...
> Assessing libevent...
> Assessing lz4...
> Assessing snappy...
> Using pinned rev 65c55155549d6b1abf1366d67890b673b5842fbe for https://github.com/facebook/folly.git
> Assessing folly...
> Using pinned rev 65c55155549d6b1abf1366d67890b673b5842fbe for https://github.com/facebook/folly.git
> Assessing autoconf...
> Assessing automake...
> Assessing libtool...
> Assessing bison...
> Assessing libsodium...
> Assessing fizz...
> Assessing flex...
> Using pinned rev b51baaeaf51950fcd491c987ff993b6a03015b66 for https://github.com/facebook/wangle.git
> Assessing wangle...
> Using pinned rev b51baaeaf51950fcd491c987ff993b6a03015b66 for https://github.com/facebook/wangle.git
> Using pinned rev 4b136c1a708d0af53b1f96e86471d28662956b42 for https://github.com/facebook/fbthrift.git
> Assessing fbthrift...
> Using pinned rev 4b136c1a708d0af53b1f96e86471d28662956b42 for https://github.com/facebook/fbthrift.git
> Assessing fb303...
> Assessing watchman...
> Building watchman...
> Building on {distro=fedora, distro_vers=32, fb=off, os=linux, test=on}
> Assessing autoconf...
> Assessing automake...
> Assessing libtool...
> Assessing patchelf...
> Consider bin/watchman
> Munging built/bin/watchman
> dep: libgflags.so.2.2 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/gflags-HuQazByAUsAezmlFbvkeYp43fwnE4XlQsjo28zBKaJs/lib/libgflags.so.2.2
> Munging built/lib/libgflags.so.2.2
> dep: libpthread.so.0 -> None
> dep: libstdc++.so.6 -> None
> dep: libm.so.6 -> None
> dep: libgcc_s.so.1 -> None
> dep: libc.so.6 -> None
> dep: libglog.so.0 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/glog-rseVU44AhrWvy38GDo7TVAq1VprQfjf_nZk8zPQp-BA/lib64/libglog.so.0
> Munging built/lib/libglog.so.0
> dep: libunwind.so.8 -> None
> dep: libpthread.so.0 -> None
> dep: libgflags.so.2.2 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/gflags-HuQazByAUsAezmlFbvkeYp43fwnE4XlQsjo28zBKaJs/lib/libgflags.so.2.2
> dep: libstdc++.so.6 -> None
> dep: libm.so.6 -> None
> dep: libgcc_s.so.1 -> None
> dep: libc.so.6 -> None
> dep: ld-linux-x86-64.so.2 -> None
> dep: libz.so.1 -> None
> dep: libssl.so.1.1 -> None
> dep: libcrypto.so.1.1 -> None
> dep: libbz2.so.1 -> None
> dep: liblzma.so.5 -> None
> dep: libzstd.so.1 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/zstd-Hw7XOd8ajUigRGELVa7WcIii9BFjEUqOo6RciUJYzPw/lib64/libzstd.so.1
> Munging built/lib/libzstd.so.1
> dep: libpthread.so.0 -> None
> dep: libc.so.6 -> None
> dep: libsnappy.so.1 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/snappy-kRjHjfXZ5iVwTe1PktipBrhP5WDGwB47s8jjWzQJZbc/lib64/libsnappy.so.1
> Munging built/lib/libsnappy.so.1
> dep: libstdc++.so.6 -> None
> dep: libm.so.6 -> None
> dep: libgcc_s.so.1 -> None
> dep: libc.so.6 -> None
> dep: libdwarf.so.1 -> None
> dep: libaio.so.1 -> None
> dep: libsodium.so.23 -> /tmp/fbcode_builder_getdeps-ZexportZusersZpengyZworkspaceZicxZ1ZwatchmanZbuildZfbcode_builder/installed/libsodium-5E-XmQw7Q4TIyAIW7jjEsvyMAb7SaXE3Th1GM72oWIg/lib/libsodium.so.23
> Munging built/lib/libsodium.so.23
> dep: libpthread.so.0 -> None
> dep: libc.so.6 -> None
> dep: ld-linux-x86-64.so.2 -> None
> dep: libdl.so.2 -> None
> dep: libunwind.so.8 -> None
> dep: libpthread.so.0 -> None
> dep: libstdc++.so.6 -> None
> dep: libm.so.6 -> None
> dep: libgcc_s.so.1 -> None
> dep: libc.so.6 -> None
> dep: ld-linux-x86-64.so.2 -> None
>  16032445      4 drwxr-s---   4 pengy    icg_src      4096 Jan 28 15:56 built
>  16032446      4 drwxr-s---   2 pengy    icg_src      4096 Jan 28 15:57 built/lib
>  16031690   3016 -rwxr-xr-x   1 pengy    icg_src   3085920 Jan 28 15:58 built/lib/libgflags.so.2.2
>  16031691   1436 -rwxr-xr-x   1 pengy    icg_src   1467256 Jan 28 15:58 built/lib/libglog.so.0
>  16031694   3600 -rwxr-xr-x   1 pengy    icg_src   3685368 Jan 28 15:59 built/lib/libsodium.so.23
>  16031693    340 -rwxr-xr-x   1 pengy    icg_src    346232 Jan 28 15:58 built/lib/libsnappy.so.1
>  16031692   6664 -rwxr-xr-x   1 pengy    icg_src   6819952 Jan 28 15:58 built/lib/libzstd.so.1
>  16032447      4 drwxr-s---   2 pengy    icg_src      4096 Jan 28 15:56 built/bin
>  16031689 231916 -rwxr-xr-x   1 pengy    icg_src  237475560 Jan 28 15:59 built/bin/watchman
> ```
> 
> Could you please help me?

**Comment by YoghurtSheep** [comment]
> That build instruction is only valid for 4.9.0 and it looks like you are building from the latest master. `./autogen.sh` is sufficient to build Watchman for laest master, and your log seems to suggest it has been built at `./built/bin` directory.

Thanks for answering!

BTW, **how can I build watchman by clang?** 
It seems unsuccessful to add `CC=clang` flag after `./autogen.sh`.

**Comment by YoghurtSheep** [comment]
Do you plan to support compiling watchman by clang on Linux?

**Comment by fanzeyi** [comment]
Hi, Watchman should be build-able with Clang. Internally we run build with both GCC and Clang. I haven't really tested but I guess you can specify the compiler with `CC` environment variable *and* `--extra-cmake-defines=CMAKE_C_COMPILER=` and other CMake related compiler variables. Something like:

```
CC=compiler python build/fbcode_builder/getdeps.py build watchman --extra-cmake-defines=CMAKE_C_COMPILER=
```

Getdeps will be driving boost's B2 and CMake build systems under the hood, so you'll need to make sure these build systems can find the compiler you specified correctly.

**Comment by rnmp** [comment]
@fanzeyi Attempting to compile from source as well using just `./autogen.sh`. It ran fine but I was also expecting a `./configure` file so that I can pass `--disable-statedir` flag. Where should I pass these compile time configuration options now that that file is gone?

**Comment by chadaustin** [comment]
I'm closing this because the original issue is resolved, but please open a new issue if you have further questions.
