### ISSUE TITLE
Installations instructions don't work for ARM64 architecture

### ISSUE THREAD

**Issue by ddahan** [facebook/watchman#897]
I installed watchman, following [these instructions](https://facebook.github.io/watchman/docs/install.html#linux-and-macos), in a debian Docker Container, running on a mac M1 (arm64 architecture):

```bash
ARG WATCHMAN_VERSION=2021.03.15.00
RUN cd /tmp \
    && wget -q https://github.com/facebook/watchman/releases/download/v${WATCHMAN_VERSION}/watchman-v${WATCHMAN_VERSION}-linux.zip \
    && unzip watchman-*-linux.zip \
    && mkdir -p /usr/local/{bin,lib} /usr/local/var/run/watchman \
    && cd watchman-*-linux \
    && cp bin/* /usr/local/bin \
    && cp lib/* /usr/local/lib \
    && chmod 755 /usr/local/bin/watchman \
    && chmod 2777 /usr/local/var/run/watchman
```

Then, when I run `watchman --version`, I get the error:

```
qemu-x86_64: Could not open '/lib64/ld-linux-x86-64.so.2': No such file or directory
```

What should I do? Thanks.

**Comment by fanzeyi** [comment]
What base image do you have? Watchman prebuilt binary requires glibc to be present in the environment. Certain base image won't include them IIRC (alpine only provides musl glibc for example).

**Comment by ddahan** [comment]
@fanzeyi Thanks, I managed to get it working by building sources directly on my ARM64 container.
However, since it's a long process, I can not afford to add this build phase to the Dockerfile itself.
There must be a way to extract the build, put in on a public GH repo, to be downloaded and installed by the Dockerfile.
However, I'm exactly sure how to do this correctly (with the right dependencies, etc.). Based on the setup  instructions for a classic release, I would say that copying lib/ and bin/ folder extracted from the build should do the job, am I right?

Thanks again.

**Comment by fanzeyi** [comment]
@ddahan Yeah copying lib/ and bin/ should be sufficient to run Watchman.

**Comment by ddahan** [comment]
It works with v4.9.0. For those interested, I made the build using [these instructions](https://medium.com/@kanikamittal0606/installing-watchman-on-ubuntu-20-04-664012d934c9).

Then I put the generated binary on a public GH repo (no additional`/lib` files required in my case, not sure why) and wrote this instruction in my Dockerfile:

```bash
RUN cd /tmp \
    && git clone https://github.com/ddahan/watchman-binary.git \
    && mkdir -p /usr/local/bin /usr/local/var/run/watchman \
    && cd watchman-binary \
    && cp watchman /usr/local/bin \
    && chmod 755 /usr/local/bin/watchman \
    && chmod 2777 /usr/local/var/run/watchman
```

**Comment by fanzeyi** [comment]
@ddahan Glad it works. If you don't have other questions I'm going to close this issue. Feel free to re-open if you have follow-up questions on this topic.
