### ISSUE TITLE
[rust] watchman_client no longer builds on windows

### ISSUE THREAD

**Issue by davidkna** [facebook/watchman#898]
#882 updated tokio to 1.0 but the windows-only `named_pipe.rs` was not updated to support the new version of tokio.

The main issues appear to be the removal of `tokio::prelude`
```
   |
11 | use tokio::prelude::*;
   |            ^^^^^^^ could not find `prelude` in `tokio`
```
and `tokio::io::PollEvented` becoming private.
```
    |
10  | use tokio::io::PollEvented;
    |                ^^^^^^^^^^^ private struct
```

**Comment by robatwilliams** [comment]
Possibly the reason that there hasn't been a Windows zip on any release after v2021.01.11.00 ?

**Comment by RoadTrain** [comment]
Prelude was removed in https://github.com/tokio-rs/tokio/pull/3299, looks like the changes aren't big.

**Comment by kassens** [comment]
I'm sorry for breaking this :(

I only have access to windows in a virtual machine and debugging there is a bit tricky. Would appreciate help with a PR!
