### ISSUE TITLE
Expo not automaticallg invoking Watchman in the foreground

### ISSUE THREAD

**Issue by yaozhang-this** [facebook/watchman#901]
I am on a Mac OS 11 Big Sur with M1 Apple Silicon ARM architecture.

My homebrew in installed on opt/homebrew following their official guideline for M1 homebrew installation.

When installing expo I also installed watchman via homebrew. Everything seems to be working fine, I have my var/run/watchman and it has my <username>-state file in it. 

However, when starting the Expo project from metro builder and sending the link to an iOS simulator, below error occurred accompanying a failed connection display on the simulator itself.

Here is the terminal message I got after starting the project.

```
2021-04-06T23:32:40,440: [cli] unable to talk to your watchman on /opt/homebrew/var/run/watchman/seseme-state/sock! (Connection refused)

Watchman:  watchman --no-pretty get-sockname returned with exit code=1, signal=null, stderr= 2021-04-06T23:32:40,440: [cli] unable to talk to your watchman on /opt/homebrew/var/run/watchman/seseme-state/sock! (Connection refused)

```
I have looked at all the solution existent on the internet. I reinstalled watchman, chmod the watchman folder, the <username>-state folder and everything. I restarted my Mac several times as well. Before everything, I have checked that my iOS simulator is using the same IP address (at least public address) as my development machine.

**Comment by Gamusren** [comment]
Seems like this is caused by Expo not automatically invoking watchman to watch in the foreground. The fix is yo manually invoke 

watchman watch --foreground MyProject

**Comment by fanzeyi** [comment]
Hi, you might want to raise this issue with Expo folks. It looks like Watchman is being called with incorrect path.
