### ISSUE TITLE
Can't Install watchman on macOS big sur M1

### ISSUE THREAD

**Issue by EmmanuelObua** [facebook/watchman#903]
# Terminal Results

      brew install watchman
      Updating Homebrew...
      ==> Auto-updated Homebrew!
      Updated 2 taps (shivammathur/php and homebrew/core).
      ==> Updated Formulae
      Updated 1 formula.
      
      Error: watchman dependencies not built for the arm64 CPU architecture:
        python@3.9 was built for x86_64

Any help on this shall be appreciated

**Comment by fanzeyi** [comment]
This is probably a question to Homebrew folks. We don't manage Watchman's Homebrew distribution. Sorry.
