### ISSUE TITLE
File /etc/watchman.json.default needed

### ISSUE THREAD

**Issue by carlosala** [facebook/watchman#905]
Hi!
With this week build, `watchman` needs to read (and also needs writing permissions) something like a default config in `/etc/watchman.json.default` and without it spawns an error and `watchman` doesn't work. I have done:
```
sudo touch /etc/watchman.json.default
sudo chmod 666 /etc/watchman.json.default
echo {} > /etc/watchman.default.json
```
This evades the exception and it works, but I should have something in this file?
Thanks!

**Comment by genevievehelsel** [comment]
Thanks for the report @carlosala! This will be fixed, you should not need to have a `/etc/watchman.json.default` file

**Comment by carlosala** [comment]
Great!
Thanks!

**Comment by carlosala** [comment]
Hey! I think this should be closed, now It works perfectly!
Thanks
