### ISSUE TITLE
watchman rust client panics on an unknown filetype in query results

### ISSUE THREAD

**Issue by cjhopman** [facebook/watchman#911]
Steps to reproduce:

get clock from a query with Expr::True as the expression
make changes that will cause watchman to have events with an unknown filetype (see https://github.com/facebook/watchman/issues/892 for ideas, or maybe simply edit a file in vscode)
do a since query with Expr::True as the expression

See:
panic with message containing "Watchman Server returned impossible file type ?', <...>/watchman_client-0.6.1/src/pdu.rs:674:24"

**Comment by viveksjain** [comment]
I hit this same issue, any update here?
