### ISSUE TITLE
No builds available

### ISSUE THREAD

**Issue by conartist6** [facebook/watchman#914]
The documentation says "You can find the binary downloads in the [latest release](https://github.com/facebook/watchman/releases/latest)". This is untrue, only source archives can be found there. Some searching reveals that watchman is in the apt repos for Ubuntu focal.

**Comment by fanzeyi** [comment]
Hi, the build is currently failing due to issues in our dependencies. We are working on getting this resolved.

Meanwhile please find the *latest release that has build for your platform available*. Thanks.

**Comment by mrojas18** [comment]
looks like the last build for windows is https://github.com/facebook/watchman/releases/tag/v2021.01.11.00

**Comment by chadaustin** [comment]
I goofed and when I updated the GitHub Actions jobs to run on the newer Windows image, I did not apply that change to the release Windows job. I'm hoping https://github.com/facebook/watchman/commit/c98f3928edb3d28654b74f7ad807f8dd905b410a fixes this, for Windows at least.

I'll leave the issue open until we've made one successful release.

**Comment by chadaustin** [comment]
Windows was fixed by https://github.com/facebook/watchman/commit/c98f3928edb3d28654b74f7ad807f8dd905b410a

Windows releases should be available now. See https://github.com/facebook/watchman/releases/tag/v2022.03.07.00

I'm still working on macOS.

**Comment by chadaustin** [comment]
The macOS tests were fixed in ea163cd7dc57277ac3ac8e5a9c8bad3c66842491, e627e786d8b92076075e8fb12b90fafa44b073d0, and d536fa95858f4e3fb4b6d73b37ba2351e163d148. Now the issue is the Watchman packaging script not understanding the homebrew openssl dylib dependencies on GitHub Actions's VM. I have a fix - I hope to land it this week.

**Comment by jwatt** [comment]
Thank you for fixing this!
