### ISSUE TITLE
 brew install --HEAD watchman not working

### ISSUE THREAD

**Issue by irohitb** [facebook/watchman#916]
## What did I do 

 brew install --HEAD watchman

## Error
```
/tmp/watchman-20210615-20921-1vuu15n/PendingCollection.cpp:325:21: error: no member named 'as_lock' in 'folly::LockedPtr<folly::Synchronized<PendingCollectionBase, std::__1::mutex>, folly::LockPolicyExclusive>'
    cond_.wait(lock.as_lock());
               ~~~~ ^
/tmp/watchman-20210615-20921-1vuu15n/PendingCollection.cpp:327:25: error: no member named 'as_lock' in 'folly::LockedPtr<folly::Synchronized<PendingCollectionBase, std::__1::mutex>, folly::LockPolicyExclusive>'
    cond_.wait_for(lock.as_lock(), timeoutms);
                   ~~~~ ^
2 errors generated.
make[2]: *** [CMakeFiles/testsupport.dir/PendingCollection.cpp.o] Error 1
make[1]: *** [CMakeFiles/testsupport.dir/all] Error 2
make: *** [all] Error 2
```

### More Details

Device: MacBook Pro (13-inch, M1, 2020)
 
   
Homebrew 3.1.12
Homebrew/homebrew-core (git revision b7623bc97d; last commit 2021-06-14)
Homebrew/homebrew-cask (git revision 6ec53cc50f; last commit 2021-06-14)

**Comment by chenrui333** [comment]
Seen the same issue with this PR Homebrew/homebrew-core#79383

**Comment by kmancini** [comment]
This change caused this: https://github.com/facebook/watchman/commit/b7ab7e5a6c298aec6b1c3e9769b5c0115af8b047

The corresponding change has been landed in folly, but has not propagated to open source, investigating.

**Comment by kmancini** [comment]
We are unfortunately blocked here by our folly dependency.

**Comment by arxanas** [comment]
Any update on this?

**Comment by carlocab** [comment]
@kmancini would reverting https://github.com/facebook/watchman/commit/b7ab7e5a6c298aec6b1c3e9769b5c0115af8b047 work while we're waiting for changes to land in open-source folly? We might consider doing so at Homebrew, since `watchman`, `folly`, `fizz`, and `wangle` have been blocked on version bumps for us for a while now, but I'd like to know whether this is even worth pursuing.

**Comment by chadaustin** [comment]
Is this fixed now?

**Comment by carlocab** [comment]
AFAIK, yes. Thanks!

**Comment by chadaustin** [comment]
Thanks! I've spent a chunk of this year working on getting the open source builds healthy. Let me know if you run into more issues!
