### ISSUE TITLE
Build failure on Ubuntu 20.04 LTS with v4.9.0

### ISSUE THREAD

**Issue by blockodyssey-whlee** [facebook/watchman#931]
I'm following the installation guide and trying to install watchman from the source.
However, when I try to build with the command 'make,' it shows the following error and fails to build:
![image](https://user-images.githubusercontent.com/78720229/126119231-9b1cfab0-8765-4096-9e86-65d872152572.png)

Is there anything I can do for this error?

**Comment by ppk42** [comment]
I faced the same issue today, when I foolowed (intended typo ;-))  the installation guide. 

Look at the Date of V4.9.0. It's about 4 years old. In the meanwhile the compilers (C++20 perhaps) are far more pedantic with memoy initialization. 

I think the best way to solve this, is to use the latest released version like mentioned in the comment above the shell commands: 
`git clone https://github.com/facebook/watchman.git -b  v2021.07.19.00 --depth 1` . 

I  vote for changing the documentation at least to a version following the new versioning schema.

I alos realized that the latest version can be build with CMake (started by autogen.sh), I still wait for the completion (on my slow box)  but I expect not to have to use configure and make anymore. So the installation instructions may be a outdated.

**Comment by baudneo** [comment]
> Compilers aren't more pedantic--this is a warning, not an error, but the build is using -Werror.
> 
> For anyone else still running into this, the real fix is to remove -Werror. -Werror shouldn't be enabled in released code. Warnings change all the time between compilers and toolchains and libraries, and -Werror guarantees that the build will randomly break for users like it did here.
> 
> (I tried using the newer tag as ppk42 suggested, but when it downloaded Boost, spent over an hour building CMake and then failed trying to run a git checkout, I stopped wondering how a simple build process became so complicated and just fixed the much simpler problem in 4.9.)

I just spent 30 mins compiling for it to error out at that git checkout command as well -->
```

Cloning https://github.com/facebookincubator/fizz.git...
---
+ cd /tmp/fbcode_builder_getdeps-ZhomeZtylerZwatchman-2021.09.27.00ZbuildZfbcode_builder/repos && \
+ git \
+      clone \
+      --depth=1 \
+      -- \
+      https://github.com/facebookincubator/fizz.git \
+      github.com-facebookincubator-fizz.git
Cloning into 'github.com-facebookincubator-fizz.git'...
remote: Enumerating objects: 589, done.
remote: Counting objects: 100% (589/589), done.
remote: Compressing objects: 100% (542/542), done.
remote: Total 589 (delta 72), reused 260 (delta 36), pack-reused 0
Receiving objects: 100% (589/589), 686.09 KiB | 2.22 MiB/s, done.
Resolving deltas: 100% (72/72), done.
fatal: ambiguous argument 'master': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
Command '['git', 'rev-parse', 'master']' returned non-zero exit status 128.
!! Failed
```

**Comment by chadaustin** [comment]
Agreed we should not be building with -Werror in the open source CMake build. If you'd like to put up a PR that removes that, I'd land it.

**Comment by chadaustin** [comment]
This has been fixed on both dimensions! Both -Werror and the offending code.
