### ISSUE TITLE
Windows Build missing

### ISSUE THREAD

**Issue by matale** [facebook/watchman#935]
Installation instructions at https://facebook.github.io/watchman/docs/install.html point to here https://github.com/facebook/watchman/releases/latest but there is no windows zip.

**Comment by manuc66** [comment]
See also https://github.com/facebook/watchman/issues/910

**Comment by n0mer** [comment]
still missing, @kassens any timeline to restore build ?

**Comment by chadaustin** [comment]
Duplicate of #910, will comment there
