### ISSUE TITLE
cant run ./autogen.sh even i use sudo

### ISSUE THREAD

**Issue by dewaranggafrontend** [facebook/watchman#937]
hi, i have install watchman using brew for react-native on my bigsur macos, but i got error "version not supported", i already clone watchman version 4.9.0 from git but when i run sudo ./autogen.sh i got error "pkg-config appears to be missing (not available to autoconf tools) please install the pkg-config package for your system.". fyi i already have pkg-config 0.29.2 version installed. anyone can help or maybe any solution for install watchman 4.9.0 version ?

**Comment by aweeraman** [comment]
Try this:

--- a/autogen.sh
+++ b/autogen.sh
@@ -21,7 +21,7 @@ automake --add-missing --foreign
 # should be the case provided pkg-config is installed AND the above commands
 # have been run to prep the source tree with local set-up.
 CHECK_PKG_CONFIG_M4='m4_ifdef([PKG_CHECK_MODULES], [errprint([ok])])'
-if [ "x$(autoconf <(echo "$CHECK_PKG_CONFIG_M4") 2>&1)" != "xok" ] ; then
+if [ "x$(autoconf --warnings=none <(echo "$CHECK_PKG_CONFIG_M4") 2>&1)" != "xok" ] ; then
   echo 'pkg-config appears to be missing (not available to autoconf tools)'
   echo 'please install the pkg-config package for your system.'
   exit 1

**Comment by chadaustin** [comment]
Definitely don't build with sudo! We should be releasing macOS binaries. Let me look into why that's not happening.

**Comment by klardotsh** [comment]
> Try this:
> 
> ```
> --- a/autogen.sh
> +++ b/autogen.sh
> @@ -21,7 +21,7 @@ automake --add-missing --foreign
>  # should be the case provided pkg-config is installed AND the above commands
>  # have been run to prep the source tree with local set-up.
>  CHECK_PKG_CONFIG_M4='m4_ifdef([PKG_CHECK_MODULES], [errprint([ok])])'
> -if [ "x$(autoconf <(echo "$CHECK_PKG_CONFIG_M4") 2>&1)" != "xok" ] ; then
> +if [ "x$(autoconf --warnings=none <(echo "$CHECK_PKG_CONFIG_M4") 2>&1)" != "xok" ] ; then
>    echo 'pkg-config appears to be missing (not available to autoconf tools)'
>    echo 'please install the pkg-config package for your system.'
>    exit 1
> ```

This fixed watchman 4.9.0 builds on Alpine 3.15 for me, thanks!

**Comment by chadaustin** [comment]
macOS releases being broken is tracked in #914, so I'll close this issue.
