### ISSUE TITLE
unable to install watchman on Ubuntu 18.06

### ISSUE THREAD

**Issue by jeremywhittington** [facebook/watchman#945]
When I try to install watchman using brew it just hangs on cmake. I have reinstalled brew, rebooted my system, let it sit for hours. It doesnt move past this.

> ~$ brew install watchman
> ==> Downloading https://github.com/google/googletest/archive/release-1.10.0.tar.
> Already downloaded: /home/jeremy/.cache/Homebrew/downloads/da44d988e96f6b92d58714b799f573289491c0fd541ef2edf95f9573d463fe95--googletest-release-1.10.0.tar.gz
> ==> Downloading https://github.com/facebook/watchman/archive/v2021.08.30.00.tar.
> Already downloaded: /home/jeremy/.cache/Homebrew/downloads/e1941adde10f4fd57ea192cf57c45a173ef00a10066986ea3033ff08071b1932--watchman-2021.08.30.00.tar.gz
> ==> cmake . -DCMAKE_INSTALL_PREFIX=/tmp/watchman-20210902-7241-33ijzy/watchman-2
> ==> make install
> ==> cmake -S . -B build -DBUILD_SHARED_LIBS=ON -DWATCHMAN_VERSION_OVERRIDE=2021.
> ==> cmake --build build

**Comment by chadaustin** [comment]
@jeremywhittington I'm going to close this, but let me know if it's still stuck.
