### ISSUE TITLE
fstype.c:18:25: error: linux/magic.h: No such file or directory make[1]: *** [watchman-fstype.o] 

### ISSUE THREAD

**Issue by jusfeel** [facebook/watchman#95]
fstype.c:18:25: error: linux/magic.h: No such file or directory
make[1]: *** [watchman-fstype.o] Error 1
make[1]: Leaving directory `/root/npm/watchman'
make: *** [all] Error 2

Have this on make. Please help!

**Comment by wez** [comment]
Sounds like you are missing a kernel-headers package.  If you're on a redhat style system, `yum install kernel-headers` should get you going.  There's likely a similar command you can run on a debian style system, but I don't know if off the top

**Comment by jusfeel** [comment]
Tried, no go.

**Comment by jusfeel** [comment]
Tried, no go.

**Comment by jusfeel** [comment]
Tried, no go.

**Comment by wez** [comment]
Keep in mind that we don't know anything about your system and that we can't see your screen; you haven't even told us what operating system you're on or what error message(s) you're now encountering.

Please take a few moments to read through https://developer.mozilla.org/en-US/docs/Mozilla/QA/Bug_writing_guidelines which has some general guidelines on how to report issues and a lot of Mozilla specific stuff that doesn't apply to watchman.

Then update this issue with more details that will help us to understand more about the system and the problems you are hitting.

**Comment by jusfeel** [comment]
It's CentOS 5.x. I changed the fstype.c to use the absolute path to linux/magic.h. It seems going through. 

Just FYI, during "./configure", I got:

checking build system type... x86_64-unknown-linux-gnu
checking host system type... x86_64-unknown-linux-gnu
checking target system type... x86_64-unknown-linux-gnu

Maybe it's related to the reason, the C file cannot find the header file in the system.

**Comment by wez** [comment]
It sounds like there's something not quite right with your system's build environment; we didn't have this issue on our CentOS 5 machines.
Sounds like you've gotten past your immediate problem, so I'm closing this out.
