### ISSUE TITLE
`--HEAD` with brew says "master branch not found"

### ISSUE THREAD

**Issue by maraisr** [facebook/watchman#961]
Might be related to #916 — but "master" branch doesn't exist as this is `main` now.

**Comment by fanzeyi** [comment]
This issue probably should be filed with homebrew/homebrew.

**Comment by fanzeyi** [comment]
https://github.com/Homebrew/homebrew-core/pull/84929

**Comment by maraisr** [comment]
Sorry about that 😅 no idea how brew works under the hood. Actually thought they was just a package manager and `--HEAD` was simply a user defined post install flag.

Thanks for getting that one sorted for me ❤️ owe you big time! Just let me know.

**Comment by fanzeyi** [comment]
Closing here as Homebrew/homebrew-core#84929 is now merged.
