### ISSUE TITLE
Tags Names Are Inconsistent

### ISSUE THREAD

**Issue by jherdman** [facebook/watchman#97]
I'm writing a Chef cookbook to install Watchman. The gist of the behaviour is to download a release from Github, and install it accordingly. The problem I'm experiencing is that the release names aren't consistent. Some names include the major and minor number, some include the patch number.

Can future releases include the major, minor AND patch version going forward? This would make life much easier.

**Comment by sid0** [comment]
To be clear, Watchman doesn't do semantic versioning in the traditional sense. "Major" releases aren't ever going to break interfaces, just deprecate them. So code that's written against Watchman 3.x will continue to work against a hypothetical 10.x.

But we can standardize on a particular numbering scheme. Does the following format work for you?

`v\d+.\d+.\d+`?

**Comment by sid0** [comment]
(here deprecation doesn't mean scheduled for removal -- it just means there's a better way to do it.)

**Comment by jherdman** [comment]
Absolutely! It doesn't really matter to me if Watchman is semver, just that the release names are predictable :)

**Comment by sid0** [comment]
We've decided to make all future versions have just two components. https://reviews.facebook.net/D38061 will document this.

**Comment by wez** [comment]
We've documented this at http://facebook.github.io/watchman/docs/compatibility.html
Thanks for prompting us to formalize this!
