### ISSUE TITLE
Plan to remove PCRE support in Watchman

### ISSUE THREAD

**Issue by fanzeyi** [facebook/watchman#973]
We (watchman maintainers) are looking to remove the existing PCRE support in Watchman.

Specifically, we are looking to remove PCRE expression support in Watchman queries, see: https://facebook.github.io/watchman/docs/expr/pcre.html

Globing and extension name queries are not affected. We want to ask if anyone in the open source community relies on this feature, and if we should continue supporting this feature.

Please comment here if you use it!

**Comment by carlocab** [comment]
I use it on occasion, so it would be nice to keep it. How difficult would it be to port this to PCRE2?

Note that removing PCRE support would go against Watchman's compatibility promise: https://facebook.github.io/watchman/docs/compatibility.html

**Comment by chadaustin** [comment]
Thanks for reporting that you use it. We aren't going to remove PCRE support after all, and will port to PCRE2 if it becomes necessary.
