### ISSUE TITLE
autogen.sh fails due to dead link to pcre-8.43.tar.gz

### ISSUE THREAD

**Issue by shearichard** [facebook/watchman#974]
In following the instructions here https://facebook.github.io/watchman/docs/install.html#installing-from-source and attempting to invoke ...

$ ./autogen.sh

.... the script dies as it cannot fetch https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz . Judging by the authors comments on www.pcre.org it seems likely its absence is not just transitory, he makes it pretty clear that pcre2 is his focus of interest.

You can find pcre-8.43.tar.gz elsewhere , eg https://sourceforge.net/projects/pcre/files/pcre/8.43/ . If I did a PR to change /build/fbcode_builder/manifests/pcre to point at the sourceforge file would that be acceptable ? Given that a transitions to pcre2 is necessary in the longer term and this issue suggests it might not be around for long anyway https://github.com/facebook/watchman/issues/973 it would only be a temporary fix but I don't don't know if that type of third-party source for pcre would be considered acceptable ?

**Comment by fanzeyi** [comment]
If you don't mind waiting a bit, I'm working on getting watchman to pcre2 atm. I should be able to unblock it by the end of this week if things go well.

**Comment by shearichard** [comment]
Hey Fanzeyi, that's absolutely fine and thanks for your efforts. 

As it turned out I had been overlooking the possibility of just using apt to install Watchman on Ubuntu and so I have now done that which means there's no rush on my part.

Thanks again for your work.

**Comment by atomic-tang** [comment]
> If you don't mind waiting a bit, I'm working on getting watchman to pcre2 atm. I should be able to unblock it by the end of this week if things go well.

I am also running into this issue on my Macbook pro. Running mojave and I don't want to rely on brew as support for mojave will be dropped.

**Comment by shearichard** [comment]
> 
> 
> > If you don't mind waiting a bit, I'm working on getting watchman to pcre2 atm. I should be able to unblock it by the end of this week if things go well.
> 
> I am also running into this issue on my Macbook pro. Running mojave and I don't want to rely on brew as support for mojave will be dropped.

If you can't wait you could : 

- download the sourceforge file I mentioned; 
- setup a local server ("python -m http.server") and; 
- change the url your copy of  the pcre manifest file. 

That should do it. 

I tried using the url for the sourceforge download directly but there's some weird thing that sourceforge does and so the approach of "serving yourself" is probably easier.

**Comment by atomic-tang** [comment]
> > > If you don't mind waiting a bit, I'm working on getting watchman to pcre2 atm. I should be able to unblock it by the end of this week if things go well.
> > 
> > 
> > I am also running into this issue on my Macbook pro. Running mojave and I don't want to rely on brew as support for mojave will be dropped.
> 
> If you can't wait you could :
> 
> * download the sourceforge file I mentioned;
> * setup a local server ("python -m http.server") and;
> * change the url your copy of  the pcre manifest file.
> 
> That should do it.
> 
> I tried using the url for the sourceforge download directly but there's some weird thing that sourceforge does and so the approach of "serving yourself" is probably easier.

Thanks for the workaround. I hosted the file in a bucket and updated the manifest and the build process was able to continue however it still failed. This is the following error I got:

`/private/var/folders/69/y908lqbs163f2r5_z0pclm4c0000gn/T/fbcode_builder_getdeps-ZUsersZUserZDesktopZwatchmanZbuildZfbcode_builder/repos/github.com-facebook-folly.git/folly/portability/Time.h:52:17: error: typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t') typedef uint8_t clockid_t;`

**Comment by shearichard** [comment]
> 
> 
> > > > If you don't mind waiting a bit, I'm working on getting watchman to pcre2 atm. I should be able to unblock it by the end of this week if things go well.
> > > 
> > > 
> > > I am also running into this issue on my Macbook pro. Running mojave and I don't want to rely on brew as support for mojave will be dropped.
> > 
> > 
> > If you can't wait you could :
> > 
> > * download the sourceforge file I mentioned;
> > * setup a local server ("python -m http.server") and;
> > * change the url your copy of  the pcre manifest file.
> > 
> > That should do it.
> > I tried using the url for the sourceforge download directly but there's some weird thing that sourceforge does and so the approach of "serving yourself" is probably easier.
> 
> Thanks for the workaround. I hosted the file in a bucket and updated the manifest and the build process was able to continue however it still failed. This is the following error I got:
> 
> ```
> .../repos/github.com-facebook-folly.git/folly/portability/Time.h:52:17: error: typedef redefinition with different types ('uint8_t' (aka 'unsigned char') vs 'enum clockid_t')
> typedef uint8_t clockid_t;
> ```

Please don't spend too much time following my advice because I really didn't know what I was doing when I was trying to do this manually .... 

however ... 

if you read this https://medium.com/@mayankarora/install-watchman-by-facebook-on-ubuntu-19-04-b10de51be7c8 and in particular the list of arguments which are used with `configure.sh`. I've forgotten the details now but I remember (a whole 48 hours ago ;-) that when I added those arguments (`./configure --without-python --without-pcre --enable-lenient`) I was able to get past some similar type related error (although I'm pretty sure not exactly the one you're seeing there). You might at least try that if you haven't already ?

**Comment by atomic-tang** [comment]
@shearichard I am getting this error when running autogen.sh. Also there is no configure.sh file in the project?

**Comment by fanzeyi** [comment]
Closing this because 3b9533bcd560775dec42ebd902d3852303237e53
