### ISSUE TITLE
Operation not permitted

### ISSUE THREAD

**Issue by QSJSI** [facebook/watchman#977]
Try to build react native clear project and getting watchman error:

`jest-haste-map: Watchman crawl failed. Retrying once with node crawler.
  Usually this happens when watchman isn't running. Create an empty `.watchmanconfig` file in your project's root folder or initialize a git or hg repository in your project.
  Error: Watchman error: std::__1::system_error: open: /Users/sliokkory/Documents/myteam/star: Operation not permitted. Make sure watchman is running for this project. See https://facebook.github.io/watchman/docs/troubleshooting.`

Watchman -v: 2021.11.15.00
MacOs: 12.0.1 Monterey (m1)

**Comment by Desintegrator** [comment]
Hi. You should move the entire project directory outside of the Documents directory

**Comment by IlyaPodlesnyi** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

Worked for me!! kudos man!!

**Comment by khazaddoom** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

This worked for me too :) I tried adding access to watman executable via System Preferences but couldnt manage to do it.
but this worked perfectly.

**Comment by ccamisoss** [comment]
For me it worked with moving the project directory to Users/myuser/

**Comment by BruceSuperProgramer** [comment]
Yep have to be right under Users/myuser/ directory. If you placed them under other folders it still not working for example Users/myuser/Download/

**Comment by brabus786** [comment]
Просто перенес в корень, и то-же сработало

**Comment by robbporto** [comment]
Is there a permanent fix for this? Moving my project to another folder is not a fix.

**Comment by Desintegrator** [comment]
No, it's permanent. System forbid access to Documents folder. It's security issue otherwise. Maybe there is a possibility to give a permissions, but I wouldn't do that

**Comment by TwanLuttik** [comment]
> No, it's permanent. System forbid access to Documents folder. It's security issue otherwise. Maybe there is a possibility to give a permissions, but I wouldn't do that

Is this something that has been changed recently or just specific for M1 chips because i have always been working on react native apps and using it inside my documents folder but just today, It appeared that i got that error too?

**Comment by TwanLuttik** [comment]
So i have factory reseted my macbook and i still have the same issue where i have to put it into `users/${name}/` folder.

**Comment by legion-zver** [comment]
It didn't work until I allowed sh to access the disk.

**Comment by MzkZeeshan** [comment]
We can resolved this when we put our project outside from those folder Desktop,Download and Document then run

npm start

It will be work thanks

**Comment by Xidiyixiwocao** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

work for me . thanks

**Comment by Xidiyixiwocao** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

May I ask how do you think out this solution, cause it really bother me a lot

**Comment by Desintegrator** [comment]
@SufianBabri Ok, if you filling good about allowing permissions which are not supposed to be allowed, that could be a solution. As for me moving the project somewhere outside of document folder better idea.

**Comment by mushtaque87** [comment]
brew upgrade watchman fixed my issue

**Comment by rishiankush** [comment]
First run `watchman watch-del-all`
then run `watchman shutdown-server` fixed my issue

**Comment by fcamargo10** [comment]
> First run `watchman watch-del-all`
> then run `watchman shutdown-server` fixed my issue

FIXED!

**Comment by Ade-Joshe** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

This works.

**Comment by Baljkaa33** [comment]
it worked for me
watchman watch-del-all
watchman shutdown-server

**Comment by cctv1005s** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

Works for me!

**Comment by OPvishal** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

thanks man, by the way how did u find it?

**Comment by OswalDev** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

This worked perfectly for me, thank you.

**Comment by faerylay** [comment]
watchman watch-del-all them run 
watchman shutdown-server after finish these two command 

just type npm start and accept watchman permission allow

**Comment by edward-hunt** [comment]
> watchman watch-del-all them run watchman shutdown-server after finish these two command
> 
> just type npm start and accept watchman permission allow

Exactly this. For whatever reason Watchman had lost it's permission to access my desktop/apps folder. This just allowed me to re-grant permission.

**Comment by rezkiy37** [comment]
> First run `watchman watch-del-all`
> then run `watchman shutdown-server` fixed my issue

THANK YOU!

**Comment by efe3535** [comment]
Privacy & Security -> Files and Folders
<img width="456" alt="image" src="https://user-images.githubusercontent.com/46342237/215080946-f6bb6435-8501-4e26-9a47-dd59cd0c0ba6.png">

**Comment by ol4juwon** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

this worked for me. thanks.

**Comment by bkamrani** [comment]
> Hi. You should move the entire project directory outside of the Documents directory
This was the solution for me (`watchman watch-del-all` then run `watchman shutdown-server` was not effective in my case).

**Comment by zhangfuchao** [comment]
> Privacy & Security -> Files and Folders <img alt="image" width="456" src="https://user-images.githubusercontent.com/46342237/215080946-f6bb6435-8501-4e26-9a47-dd59cd0c0ba6.png">

Thank you! Works for me!

**Comment by joshuabalduff** [comment]
> watchman shutdown-server

This is the way

**Comment by namti** [comment]
Running `sudo npm run start` fixes it. It will ask full disk access

**Comment by kashifansari786** [comment]
sometime watchman is not able to access your folder where your actual project is located so for that reason it shows **Operation not permitted** to resolve this issue 

1. run `sudo npx react-native start` so it will start the server 
2. when the server is started, a popup appears that **allows access to the folder for watchman** allows it.
3. then run your project in Android/IOS it will run as expected.

**Comment by Aakash359** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

Wow this solutions worked for me great

**Comment by Hoang-Phong-2122** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

THANK YOU!

**Comment by KalanaPallemulla** [comment]
> watchman shutdown-server

Thank you man. This worked for me.

**Comment by KalanaPallemulla** [comment]
> Privacy & Security -> Files and Folders <img alt="image" width="456" src="https://user-images.githubusercontent.com/46342237/215080946-f6bb6435-8501-4e26-9a47-dd59cd0c0ba6.png">

Thank you man. This worked for me.

**Comment by ovieimara** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue
worked for me. Thanks.

**Comment by deepbag** [comment]
If you are using mac go to setting > Privacy & Setting > Full Disk Access > Allow Watchman and Terminals

**Comment by kingingcole** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

The perfect fix!

**Comment by BaseMax** [comment]
> Hi. You should move the entire project directory outside of the Documents directory


You saved my time. I moved the project from `Downloads` dir to somewhere else.

Thanks

**Comment by erickcrus** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

I love you!

**Comment by deivyrene** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

A majestic solution!

**Comment by Dr-Wrong-Mo** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

Thanks for this!

**Comment by peterng014** [comment]
> Privacy & Security -> Files and Folders
> <img alt="image" width="456" src="https://user-images.githubusercontent.com/46342237/215080946-f6bb6435-8501-4e26-9a47-dd59cd0c0ba6.png">

this is the root cause for me, wondering why having a lot of watchman instances there

**Comment by sholleyonline** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

This worked for me. Thanks

**Comment by muhammadqazi** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

Thanks, worked for me.

**Comment by 1pretom** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

this worked to me, tks

**Comment by dannyboyjr** [comment]
This worked as of Jan 2024

**Comment by hmadJutt** [comment]
This is easiest fix 
https://stackoverflow.com/a/74032225

**Comment by hakansaglam29** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

why?

**Comment by Desintegrator** [comment]
> Hi. You should move the entire project directory outside of the Documents directory

Cause Documents folder has some permission restrictions for security reasons by default

**Comment by usmanabid94** [comment]
> watchman shutdown-server

Bro you saved me I updated homebrew and suddenly this issue came but your solution worked as a savior.

**Comment by 9589589661** [comment]
My project work when i move my project outside from desktop,downlaod and document folder.

**Comment by RomanDivkovic** [comment]
> First run `watchman watch-del-all` then run `watchman shutdown-server` fixed my issue

Works great thanks, no need to move the project for me!
