### ISSUE TITLE
docs: broken link to watch-project; homepage recommends deprecated command

### ISSUE THREAD

**Issue by shamrin** [facebook/watchman#98]
Two documentation issues I've noticed:

1. The link from cmd/watch.html to cmd/watch-project is broken: https://facebook.github.io/watchman/docs/cmd/watch.html

2. Homepage recommends deprecated command: https://facebook.github.io/watchman/

**Comment by wez** [comment]
Thanks for noticing :-)

https://reviews.facebook.net/D37701 has a fix for the former.

For the latter, it is a little more complex to use `watch-project` than `watch`.  We're overdue to add some more recipe-style help documentation and will take care of that as part of that effort.

**Comment by wez** [comment]
Finally got around to pushing the doc fix
