### ISSUE TITLE
PCRE Download points at the wrong URL

### ISSUE THREAD

**Issue by arrjayh** [facebook/watchman#996]
`Download https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz -> /tmp/fbcode_builder_getdeps-ZhomeZarobhickZwatchmanZbuildZfbcode_builder/downloads/pcre-pcre-8.43.tar.gz ...`

`TransientFailure: Failed to download https://ftp.pcre.org/pub/pcre/pcre-8.43.tar.gz to /tmp/fbcode_builder_getdeps-ZhomeZarobhickZwatchmanZbuildZfbcode_builder/downloads/pcre-pcre-8.43.tar.gz: <urlopen error [Errno -2] Name or service not known>`

Per their documentation:
> You can check out the PCRE2 source code via Git or Subversion:
> 
> git clone https://github.com/PhilipHazel/pcre2.git
> Note that the former ftp.pcre.org FTP site is no longer available. You will need to update any scripts that download PCRE source code to download via HTTPS, Git, or Subversion from the new home on GitHub instead.

**Comment by chadaustin** [comment]
This is fixed. We've been downloading from SourceForge for a while: https://github.com/facebook/watchman/blob/main/build/fbcode_builder/manifests/pcre
